export interface C1Word {
  id: string;
  category: string;
  word: string;
  ipa: string;
  spanish: string;
  example: string;
}

export const C1_WORDS: C1Word[] = [
  { id: "c1w_1", category: "Prefix", word: "unpredictable", ipa: "/ˌʌnprɪˈdɪktəbl/", spanish: "impredecible", example: "El clima de esta ciudad es totalmente impredecible." },
  { id: "c1w_2", category: "Prefix", word: "unable", ipa: "/ʌnˈeɪbl/", spanish: "incapaz", example: "Me siento incapaz de resolver este problema matemático." },
  { id: "c1w_3", category: "Prefix", word: "uncomfortable", ipa: "/ʌnˈkʌmfərtəbl/", spanish: "incómodo", example: "Esta silla de la oficina es demasiado incómoda." },
  { id: "c1w_4", category: "Prefix", word: "unexpected", ipa: "/ˌʌnɪkˈspɛktɪd/", spanish: "inesperado", example: "Tuvimos un gasto inesperado este mes." },
  { id: "c1w_5", category: "Prefix", word: "unhappy", ipa: "/ʌnˈhæpi/", spanish: "infeliz", example: "Él se sentía muy infeliz en su antiguo trabajo." },
  { id: "c1w_6", category: "Prefix", word: "unknown", ipa: "/ʌnˈnoʊn/", spanish: "desconocido", example: "El autor de este antiguo poema es desconocido." },
  { id: "c1w_7", category: "Prefix", word: "unlikely", ipa: "/ʌnˈlaɪkli/", spanish: "improbable", example: "Es muy improbable que nieve en esta época del año." },
  { id: "c1w_8", category: "Prefix", word: "unlock", ipa: "/ʌnˈlɑk/", spanish: "desbloquear", example: "Necesito tu huella para desbloquear el teléfono." },
  { id: "c1w_9", category: "Prefix", word: "unpack", ipa: "/ʌnˈpæk/", spanish: "desempacar", example: "Lo primero que haré al llegar al hotel es desempacar." },
  { id: "c1w_10", category: "Prefix", word: "unsafe", ipa: "/ʌnˈseɪf/", spanish: "inseguro", example: "Caminar por esa calle oscura es muy inseguro." },
  { id: "c1w_11", category: "Prefix", word: "unusual", ipa: "/ʌnˈjuʒəwəl/", spanish: "inusual", example: "Es inusual que el jefe llegue tan tarde." },
  { id: "c1w_12", category: "Prefix", word: "impossible", ipa: "/ɪmˈpɑsəbl/", spanish: "imposible", example: "Es imposible terminar todo el proyecto hoy." },
  { id: "c1w_13", category: "Prefix", word: "impatient", ipa: "/ɪmˈpeɪʃənt/", spanish: "impaciente", example: "No seas impaciente, el vuelo ya casi va a despegar." },
  { id: "c1w_14", category: "Prefix", word: "imperfect", ipa: "/ɪmˈpɜrfɪkt/", spanish: "imperfecto", example: "Sabemos que el sistema actual es bastante imperfecto." },
  { id: "c1w_15", category: "Prefix", word: "impolite", ipa: "/ˌɪmpəˈlaɪt/", spanish: "descortés", example: "Es muy descortés interrumpir a alguien mientras habla." },
  { id: "c1w_16", category: "Prefix", word: "inactive", ipa: "/ɪnˈæktɪv/", spanish: "inactivo", example: "Mi cuenta de correo estuvo inactiva por seis meses." },
  { id: "c1w_17", category: "Prefix", word: "incapable", ipa: "/ɪnˈkeɪpəbl/", spanish: "incapaz", example: "El gerente parece incapaz de tomar decisiones." },
  { id: "c1w_18", category: "Prefix", word: "incomplete", ipa: "/ˌɪnkəmˈplit/", spanish: "incompleto", example: "El informe que me entregaste está incompleto." },
  { id: "c1w_19", category: "Prefix", word: "incorrect", ipa: "/ˌɪnkəˈrɛkt/", spanish: "incorrecto", example: "Me temo que el código de seguridad es incorrecto." },
  { id: "c1w_20", category: "Prefix", word: "independent", ipa: "/ˌɪndɪˈpɛndənt/", spanish: "independiente", example: "Ella ha sido económicamente independiente desde joven." },
  { id: "c1w_21", category: "Prefix", word: "informal", ipa: "/ɪnˈfɔrməl/", spanish: "informal", example: "La reunión de hoy será muy breve e informal." },
  { id: "c1w_22", category: "Prefix", word: "invisible", ipa: "/ɪnˈvɪzəbl/", spanish: "invisible", example: "El gas que se escapa es peligroso porque es invisible." },
  { id: "c1w_23", category: "Prefix", word: "illegal", ipa: "/ɪˈligəl/", spanish: "ilegal", example: "Estacionar frente a un hospital es totalmente ilegal." },
  { id: "c1w_24", category: "Prefix", word: "illogical", ipa: "/ɪˈlɑʤɪkəl/", spanish: "ilógico", example: "Su argumento para no ir me pareció muy ilógico." },
  { id: "c1w_25", category: "Prefix", word: "irregular", ipa: "/ɪˈrɛgjələr/", spanish: "irregular", example: "El terreno donde vamos a construir es muy irregular." },
  { id: "c1w_26", category: "Prefix", word: "irresponsible", ipa: "/ˌɪrɪˈspɑnsəbl/", spanish: "irresponsable", example: "Dejar la puerta abierta fue un acto irresponsable." },
  { id: "c1w_27", category: "Prefix", word: "disadvantage", ipa: "/ˌdɪsədˈvæntɪʤ/", spanish: "desventaja", example: "No hablar otro idioma es una gran desventaja." },
  { id: "c1w_28", category: "Prefix", word: "disagree", ipa: "/ˌdɪsəˈgri/", spanish: "discrepar", example: "Tengo que discrepar contigo en ese punto de vista." },
  { id: "c1w_29", category: "Prefix", word: "disappear", ipa: "/ˌdɪsəˈpɪr/", spanish: "desaparecer", example: "El mago hizo desaparecer un conejo frente a todos." },
  { id: "c1w_30", category: "Prefix", word: "disappoint", ipa: "/ˌdɪsəˈpɔɪnt/", spanish: "decepcionar", example: "Me esforcé mucho para no decepcionar a mis padres." },
  { id: "c1w_31", category: "Prefix", word: "disconnect", ipa: "/ˌdɪskəˈnɛkt/", spanish: "desconectar", example: "Recuerda desconectar la máquina antes de limpiarla." },
  { id: "c1w_32", category: "Prefix", word: "discount", ipa: "/ˈdɪskaʊnt/", spanish: "descuento", example: "Pude conseguir un buen descuento en la tienda." },
  { id: "c1w_33", category: "Prefix", word: "discover", ipa: "/dɪˈskʌvər/", spanish: "descubrir", example: "Los científicos acaban de descubrir una nueva estrella." },
  { id: "c1w_34", category: "Prefix", word: "dislike", ipa: "/dɪsˈlaɪk/", spanish: "desagradar", example: "Me desagrada mucho el sabor de la comida picante." },
  { id: "c1w_35", category: "Prefix", word: "disobey", ipa: "/ˌdɪsəˈbeɪ/", spanish: "desobedecer", example: "Nunca debes desobedecer las reglas de seguridad." },
  { id: "c1w_36", category: "Prefix", word: "disqualify", ipa: "/dɪsˈkwɑləˌfaɪ/", spanish: "descalificar", example: "Decidieron descalificar al atleta por usar trampas." },
  { id: "c1w_37", category: "Prefix", word: "mistake", ipa: "/mɪˈsteɪk/", spanish: "error", example: "Pagué de más porque cometí un error de cálculo." },
  { id: "c1w_38", category: "Prefix", word: "misbehave", ipa: "/ˌmɪsbɪˈheɪv/", spanish: "portarse mal", example: "Si te sigues portando mal te quedarás sin postre." },
  { id: "c1w_39", category: "Prefix", word: "misunderstand", ipa: "/ˌmɪsʌndərˈstænd/", spanish: "malinterpretar", example: "Por favor, no vayas a malinterpretar mis palabras." },
  { id: "c1w_40", category: "Prefix", word: "misspell", ipa: "/mɪsˈspɛl/", spanish: "escribir mal", example: "Mi apellido es difícil, siempre lo suelen escribir mal." },
  { id: "c1w_41", category: "Prefix", word: "mislead", ipa: "/mɪsˈlid/", spanish: "engañar", example: "El anuncio estaba diseñado para engañar a los compradores." },
  { id: "c1w_42", category: "Prefix", word: "antibiotic", ipa: "/ˌæntibaɪˈɑtɪk/", spanish: "antibiótico", example: "El médico me recetó un antibiótico para la infección." },
  { id: "c1w_43", category: "Prefix", word: "antisocial", ipa: "/ˌæntiˈsoʊʃəl/", spanish: "antisocial", example: "Últimamente prefiero quedarme en casa, estoy algo antisocial." },
  { id: "c1w_44", category: "Prefix", word: "antivirus", ipa: "/ˌæntiˈvaɪrəs/", spanish: "antivirus", example: "Asegúrate de actualizar el programa antivirus de tu laptop." },
  { id: "c1w_45", category: "Prefix", word: "antibody", ipa: "/ˈæntiˌbɑdi/", spanish: "anticuerpo", example: "Las vacunas ayudan a crear el anticuerpo necesario." },
  { id: "c1w_46", category: "Prefix", word: "anticlockwise", ipa: "/ˌæntiˈklɑkˌwaɪz/", spanish: "en sentido contrario a las agujas del reloj", example: "Gira la perilla en sentido contrario a las agujas del reloj." },
  { id: "c1w_47", category: "Prefix", word: "deactivate", ipa: "/diˈæktəˌveɪt/", spanish: "desactivar", example: "Necesitas un código especial para desactivar la alarma." },
  { id: "c1w_48", category: "Prefix", word: "decode", ipa: "/dɪˈkoʊd/", spanish: "decodificar", example: "La computadora tardó horas en decodificar el mensaje." },
  { id: "c1w_49", category: "Prefix", word: "decrease", ipa: "/dɪˈkris/", spanish: "disminuir", example: "Las ventas van a disminuir si no bajamos los precios." },
  { id: "c1w_50", category: "Prefix", word: "deform", ipa: "/dɪˈfɔrm/", spanish: "deformar", example: "El calor extremo puede deformar las piezas de plástico." },
  { id: "c1w_51", category: "Prefix", word: "dehydrate", ipa: "/diˈhaɪdreɪt/", spanish: "deshidratar", example: "Hacer ejercicio al sol sin agua te va a deshidratar." },
  { id: "c1w_52", category: "Prefix", word: "devalue", ipa: "/diˈvælju/", spanish: "devaluar", example: "Esa política económica podría devaluar nuestra moneda." },
  { id: "c1w_53", category: "Prefix", word: "detach", ipa: "/dɪˈtæʧ/", spanish: "separar", example: "Por favor, asegúrese de separar el cupón antes de pagar." },
  { id: "c1w_54", category: "Prefix", word: "nonsense", ipa: "/ˈnɑnsɛns/", spanish: "tontería", example: "Lo que dices no tiene sentido alguno, es una tontería." },
  { id: "c1w_55", category: "Prefix", word: "nonstop", ipa: "/ˈnɑnˈstɑp/", spanish: "sin parar", example: "Tomamos un vuelo directo y viajamos sin parar." },
  { id: "c1w_56", category: "Prefix", word: "nonexistent", ipa: "/ˌnɑnɪgˈzɪstənt/", spanish: "inexistente", example: "El apoyo del gobierno para este proyecto fue inexistente." },
  { id: "c1w_57", category: "Prefix", word: "non-profit", ipa: "/nɑn-ˈprɑfɪt/", spanish: "sin fines de lucro", example: "Hago voluntariado en una organización sin fines de lucro." },
  { id: "c1w_58", category: "Prefix", word: "rebuild", ipa: "/riˈbɪld/", spanish: "reconstruir", example: "Tomará años reconstruir la ciudad tras el terremoto." },
  { id: "c1w_59", category: "Prefix", word: "recall", ipa: "/rɪˈkɔl/", spanish: "recordar", example: "No logro recordar dónde dejé las llaves del coche." },
  { id: "c1w_60", category: "Prefix", word: "recharge", ipa: "/riˈʧɑrʤ/", spanish: "recargar", example: "Préstame tu cargador, necesito recargar mi celular." },
  { id: "c1w_61", category: "Prefix", word: "recover", ipa: "/rɪˈkʌvər/", spanish: "recuperar", example: "Espero que el paciente logre recuperar su salud pronto." },
  { id: "c1w_62", category: "Prefix", word: "recycle", ipa: "/riˈsaɪkəl/", spanish: "reciclar", example: "En mi casa tenemos tres botes diferentes para reciclar." },
  { id: "c1w_63", category: "Prefix", word: "redo", ipa: "/riˈdu/", spanish: "rehacer", example: "Hubo un error de guardado y tendré que rehacer el documento." },
  { id: "c1w_64", category: "Prefix", word: "replace", ipa: "/rɪˈpleɪs/", spanish: "reemplazar", example: "El mecánico dijo que debemos reemplazar los frenos." },
  { id: "c1w_65", category: "Prefix", word: "replay", ipa: "/riˈpleɪ/", spanish: "repetir", example: "La jugada fue dudosa, vamos a repetir el video." },
  { id: "c1w_66", category: "Prefix", word: "reuse", ipa: "/riˈjuz/", spanish: "reutilizar", example: "Lava esa botella de vidrio, la podemos reutilizar." },
  { id: "c1w_67", category: "Prefix", word: "review", ipa: "/rɪˈvju/", spanish: "revisar", example: "Esta noche vamos a revisar todos los temas del examen." },
  { id: "c1w_68", category: "Prefix", word: "rewrite", ipa: "/riˈraɪt/", spanish: "reescribir", example: "Tuve que reescribir la introducción de mi tesis." },
  { id: "c1w_69", category: "Prefix", word: "reappear", ipa: "/ˌriəˈpɪr/", spanish: "reaparecer", example: "Esperamos que el animal en peligro vuelva a reaparecer." },
  { id: "c1w_70", category: "Prefix", word: "reorganize", ipa: "/riˈɔrgəˌnaɪz/", spanish: "reorganizar", example: "Aproveché el domingo para reorganizar mi armario." },
  { id: "c1w_71", category: "Prefix", word: "reconsider", ipa: "/ˌrikənˈsɪdər/", spanish: "reconsiderar", example: "Por favor, te pido reconsiderar tu renuncia a la empresa." },
  { id: "c1w_72", category: "Prefix", word: "prearrange", ipa: "/ˌpriəˈreɪndʒ/", spanish: "preorganizar", example: "Tuvimos que preorganizar todos los detalles del evento." },
  { id: "c1w_73", category: "Prefix", word: "precondition", ipa: "/ˌprikənˈdɪʃən/", spanish: "precondición", example: "La puntualidad es una precondición para este empleo." },
  { id: "c1w_74", category: "Prefix", word: "prehistoric", ipa: "/ˌprihɪˈstɔrɪk/", spanish: "prehistórico", example: "El museo exhibe un esqueleto prehistórico gigante." },
  { id: "c1w_75", category: "Prefix", word: "prepay", ipa: "/priˈpeɪ/", spanish: "prepagar", example: "La aerolínea exige prepagar el equipaje extra en línea." },
  { id: "c1w_76", category: "Prefix", word: "preschool", ipa: "/ˈpriˌskul/", spanish: "preescolar", example: "Mi hija menor empieza el preescolar el próximo mes." },
  { id: "c1w_77", category: "Prefix", word: "preview", ipa: "/ˈpriˌvju/", spanish: "vista previa", example: "El cine ofreció una vista previa exclusiva de la película." },
  { id: "c1w_78", category: "Prefix", word: "preheat", ipa: "/priˈhit/", spanish: "precalentar", example: "La receta dice que debemos precalentar el horno a 180°C." },
  { id: "c1w_79", category: "Prefix", word: "postgraduate", ipa: "/poʊstˈgræʤuɪt/", spanish: "posgrado", example: "Terminó la carrera y ahora busca un curso de posgrado." },
  { id: "c1w_80", category: "Prefix", word: "postpone", ipa: "/poʊstˈpoʊn/", spanish: "posponer", example: "Lamentablemente tuvimos que posponer la reunión de hoy." },
  { id: "c1w_81", category: "Prefix", word: "postwar", ipa: "/poʊstˈwɔr/", spanish: "posguerra", example: "El período de posguerra trajo muchos cambios sociales." },
  { id: "c1w_82", category: "Prefix", word: "postscript", ipa: "/ˈpoʊstˌskrɪpt/", spanish: "posdata", example: "Al final de la carta, agregó una romántica posdata." },
  { id: "c1w_83", category: "Prefix", word: "overcook", ipa: "/ˌoʊvərˈkʊk/", spanish: "cocinar de más", example: "Ten cuidado con el fuego, no queremos cocinar de más el arroz." },
  { id: "c1w_84", category: "Prefix", word: "overeat", ipa: "/ˌoʊvərˈit/", spanish: "comer en exceso", example: "En las fiestas de diciembre es muy común comer en exceso." },
  { id: "c1w_85", category: "Prefix", word: "overestimate", ipa: "/ˌoʊvərˈɛstəmət/", spanish: "sobreestimar", example: "Nunca es bueno sobreestimar a tus propios competidores." },
  { id: "c1w_86", category: "Prefix", word: "oversleep", ipa: "/ˌoʊvərˈslip/", spanish: "quedarse dormido", example: "Olvidé poner la alarma y me volví a quedar dormido." },
  { id: "c1w_87", category: "Prefix", word: "overwork", ipa: "/ˌoʊvərˈwɜrk/", spanish: "trabajar en exceso", example: "El médico le advirtió sobre los peligros de trabajar en exceso." },
  { id: "c1w_88", category: "Prefix", word: "overcome", ipa: "/ˌoʊvərˈkʌm/", spanish: "superar", example: "Con esfuerzo, podrás superar esta difícil situación." },
  { id: "c1w_89", category: "Prefix", word: "overreact", ipa: "/ˌoʊvəriˈækt/", spanish: "reaccionar exageradamente", example: "Trata de mantener la calma y no reaccionar exageradamente." },
  { id: "c1w_90", category: "Prefix", word: "undercook", ipa: "/ˌʌndərˈkʊk/", spanish: "cocinar poco", example: "Cocinar poco el pollo puede causarte una infección." },
  { id: "c1w_91", category: "Prefix", word: "underestimate", ipa: "/ˌʌndərˈɛstəmət/", spanish: "subestimar", example: "Muchas veces tendemos a subestimar el poder de la mente." },
  { id: "c1w_92", category: "Prefix", word: "underpay", ipa: "/ˌʌndərˈpeɪ/", spanish: "pagar mal", example: "Esa cadena de supermercados es famosa por pagar mal." },
  { id: "c1w_93", category: "Prefix", word: "underwater", ipa: "/ˌʌndərˈwɔtər/", spanish: "bajo el agua", example: "Compré una cámara especial para tomar fotos bajo el agua." },
  { id: "c1w_94", category: "Prefix", word: "underline", ipa: "/ˈʌndərˌlaɪn/", spanish: "subrayar", example: "Recuerda subrayar los conceptos clave en tu libro de texto." },
  { id: "c1w_95", category: "Prefix", word: "outdo", ipa: "/ˌaʊtˈdu/", spanish: "superar", example: "El atleta se entrenó duramente para superar su propia marca." },
  { id: "c1w_96", category: "Prefix", word: "outdoors", ipa: "/ˌaʊtˈdɔrz/", spanish: "al aire libre", example: "Siempre es preferible hacer ejercicio al aire libre." },
  { id: "c1w_97", category: "Prefix", word: "outperform", ipa: "/ˌaʊt-pərˈfɔrm/", spanish: "superar el rendimiento", example: "Las nuevas acciones lograron superar el rendimiento esperado." },
  { id: "c1w_98", category: "Prefix", word: "outsmart", ipa: "/aʊtˈsmɑrt/", spanish: "ser más astuto que", example: "Logró ser más astuto que los estafadores and no perdió su dinero." },
  { id: "c1w_99", category: "Prefix", word: "submarine", ipa: "/ˈsʌbməˌrin/", spanish: "submarino", example: "La marina cuenta con un submarino nuclear muy avanzado." },
  { id: "c1w_100", category: "Prefix", word: "subtitle", ipa: "/ˈsʌbˌtaɪtəl/", spanish: "subtítulo", example: "La película rusa venía con un conveniente subtítulo en español." },
  { id: "c1w_101", category: "Prefix", word: "subway", ipa: "/ˈsʌbˌweɪ/", spanish: "metro", example: "En Nueva York, la forma más rápida de viajar es el metro." },
  { id: "c1w_102", category: "Suffix", word: "development", ipa: "/dɪˈvɛləpmənt/", spanish: "desarrollo", example: "El desarrollo de la tecnología es muy rápido." },
  { id: "c1w_103", category: "Suffix", word: "government", ipa: "/ˈgʌvərnmənt/", spanish: "gobierno", example: "El gobierno tomó nuevas medidas económicas." },
  { id: "c1w_104", category: "Suffix", word: "management", ipa: "/ˈmænɪdʒmənt/", spanish: "gestión", example: "La gestión de recursos es fundamental aquí." },
  { id: "c1w_105", category: "Suffix", word: "agreement", ipa: "/əˈgrimənt/", spanish: "acuerdo", example: "Ayer llegamos a un buen acuerdo comercial." },
  { id: "c1w_106", category: "Suffix", word: "investment", ipa: "/ɪnˈvɛstmənt/", spanish: "inversión", example: "Comprar esta casa fue una gran inversión." },
  { id: "c1w_107", category: "Suffix", word: "assessment", ipa: "/əˈsɛsmənt/", spanish: "evaluación", example: "Mañana haremos una evaluación del proyecto." },
  { id: "c1w_108", category: "Suffix", word: "information", ipa: "/ˌɪnfərˈmeɪʃən/", spanish: "información", example: "Necesito más información sobre el caso." },
  { id: "c1w_109", category: "Suffix", word: "education", ipa: "/ˌɛdʒuˈkeɪʃən/", spanish: "educación", example: "La educación es clave para un buen futuro." },
  { id: "c1w_110", category: "Suffix", word: "decision", ipa: "/dɪˈsɪʒən/", spanish: "decisión", example: "Tomar una decisión tan grande puede ser difícil." },
  { id: "c1w_111", category: "Suffix", word: "attention", ipa: "/əˈtɛnʃən/", spanish: "atención", example: "Por favor, presta mucha atención en la clase." },
  { id: "c1w_112", category: "Suffix", word: "action", ipa: "/ˈækʃən/", spanish: "acción", example: "Debemos tomar acción inmediatamente hoy." },
  { id: "c1w_113", category: "Suffix", word: "conclusion", ipa: "/kənˈkluʒən/", spanish: "conclusión", example: "Finalmente llegamos a una conclusión clara." },
  { id: "c1w_114", category: "Suffix", word: "awareness", ipa: "/əˈwɛrnəs/", spanish: "conciencia", example: "Debemos crear conciencia sobre el clima." },
  { id: "c1w_115", category: "Suffix", word: "happiness", ipa: "/ˈhæpinəs/", spanish: "felicidad", example: "Dicen que el dinero no compra la felicidad." },
  { id: "c1w_116", category: "Suffix", word: "darkness", ipa: "/ˈdɑrknəs/", spanish: "oscuridad", example: "No podía ver absolutamente nada en la oscuridad." },
  { id: "c1w_117", category: "Suffix", word: "weakness", ipa: "/ˈwiknəs/", spanish: "debilidad", example: "Mi mayor debilidad siempre han sido los dulces." },
  { id: "c1w_118", category: "Suffix", word: "kindness", ipa: "/ˈkaɪndnəs/", spanish: "amabilidad", example: "Te agradezco tu amabilidad de siempre." },
  { id: "c1w_119", category: "Suffix", word: "effectiveness", ipa: "/ɪˈfɛktɪvnəs/", spanish: "efectividad", example: "Dudan de la efectividad de esa nueva pastilla." },
  { id: "c1w_120", category: "Suffix", word: "ability", ipa: "/əˈbɪlɪti/", spanish: "habilidad", example: "Tiene una habilidad única para resolver problemas." },
  { id: "c1w_121", category: "Suffix", word: "security", ipa: "/sɪˈkjʊrɪti/", spanish: "seguridad", example: "La seguridad del sistema informático fue vulnerada." },
  { id: "c1w_122", category: "Suffix", word: "quality", ipa: "/ˈkwɑlɪti/", spanish: "calidad", example: "Esta ropa de invierno es de muy alta calidad." },
  { id: "c1w_123", category: "Suffix", word: "activity", ipa: "/ækˈtɪvɪti/", spanish: "actividad", example: "Nadar en la piscina es mi actividad favorita." },
  { id: "c1w_124", category: "Suffix", word: "community", ipa: "/kəˈmjunɪti/", spanish: "comunidad", example: "Nuestra comunidad vecinal es muy unida." },
  { id: "c1w_125", category: "Suffix", word: "safety", ipa: "/ˈseɪfti/", spanish: "seguridad", example: "Ponte el cinturón por tu propia seguridad." },
  { id: "c1w_126", category: "Suffix", word: "experience", ipa: "/ɪkˈspɪriəns/", spanish: "experiencia", example: "Tengo mucha experiencia en el área de ventas." },
  { id: "c1w_127", category: "Suffix", word: "difference", ipa: "/ˈdɪfərəns/", spanish: "diferencia", example: "La verdad no noto la diferencia entre ellos." },
  { id: "c1w_128", category: "Suffix", word: "performance", ipa: "/pərˈfɔrməns/", spanish: "rendimiento", example: "Su rendimiento deportivo mejoró bastante." },
  { id: "c1w_129", category: "Suffix", word: "importance", ipa: "/ɪmˈpɔrtəns/", spanish: "importancia", example: "Entiendo la gran importancia de este asunto." },
  { id: "c1w_130", category: "Suffix", word: "confidence", ipa: "/ˈkɑnfɪdəns/", spanish: "confianza", example: "Debes tener mucha más confianza en ti mismo." },
  { id: "c1w_131", category: "Suffix", word: "distance", ipa: "/ˈdɪstəns/", spanish: "distancia", example: "El atleta corrió una gran distancia esta mañana." },
  { id: "c1w_132", category: "Suffix", word: "teacher", ipa: "/ˈtiʧər/", spanish: "profesor", example: "Mi profesor de ciencias explica muy bien." },
  { id: "c1w_133", category: "Suffix", word: "doctor", ipa: "/ˈdɑktər/", spanish: "doctor", example: "El doctor me recetó descanso por una semana." },
  { id: "c1w_134", category: "Suffix", word: "worker", ipa: "/ˈwɜrkər/", spanish: "trabajador", example: "Él es un trabajador muy puntual y responsable." },
  { id: "c1w_135", category: "Suffix", word: "manager", ipa: "/ˈmænɪdʒər/", spanish: "gerente", example: "El gerente de la tienda aprobó mis vacaciones." },
  { id: "c1w_136", category: "Suffix", word: "director", ipa: "/dɪˈrɛktər/", spanish: "director", example: "El director de la película ganó un gran premio." },
  { id: "c1w_137", category: "Suffix", word: "writer", ipa: "/ˈraɪtər/", spanish: "escritor", example: "Ese escritor publicó una nueva novela ayer." },
  { id: "c1w_138", category: "Suffix", word: "artist", ipa: "/ˈɑrtɪst/", spanish: "artista", example: "El artista pintó un cuadro muy realista." },
  { id: "c1w_139", category: "Suffix", word: "scientist", ipa: "/ˈsaɪəntɪst/", spanish: "científico", example: "El científico hizo un gran descubrimiento hoy." },
  { id: "c1w_140", category: "Suffix", word: "tourist", ipa: "/ˈtʊrɪst/", spanish: "turista", example: "Un turista me preguntó cómo llegar al museo." },
  { id: "c1w_141", category: "Suffix", word: "specialist", ipa: "/ˈspɛʃəlɪst/", spanish: "especialista", example: "Necesitas consultar a un médico especialista." },
  { id: "c1w_142", category: "Suffix", word: "journalist", ipa: "/ˈdʒɜrnəlɪst/", spanish: "periodista", example: "El periodista escribió la noticia de primera plana." },
  { id: "c1w_143", category: "Suffix", word: "available", ipa: "/əˈveɪləbl/", spanish: "disponible", example: "El director de la escuela no está disponible ahora." },
  { id: "c1w_144", category: "Suffix", word: "comfortable", ipa: "/ˈkʌmfərtəbl/", spanish: "cómodo", example: "Esta cama de hotel es extremadamente cómoda." },
  { id: "c1w_145", category: "Suffix", word: "impossible", ipa: "/ɪmˈpɑsəbl/", spanish: "imposible", example: "Es casi imposible terminar todo el trabajo hoy." },
  { id: "c1w_146", category: "Suffix", word: "valuable", ipa: "/ˈvæljəbl/", spanish: "valioso", example: "El tiempo es el recurso más valioso que tenemos." },
  { id: "c1w_147", category: "Suffix", word: "responsible", ipa: "/rɪˈspɑnsəbl/", spanish: "responsable", example: "Tú eres el único responsable de tu equipo." },
  { id: "c1w_148", category: "Suffix", word: "acceptable", ipa: "/əkˈsɛptəbl/", spanish: "aceptable", example: "Me parece que tu propuesta es bastante aceptable." },
  { id: "c1w_149", category: "Suffix", word: "beautiful", ipa: "/ˈbjutɪfəl/", spanish: "hermoso", example: "Mi abuela tiene un jardín de rosas muy hermoso." },
  { id: "c1w_150", category: "Suffix", word: "successful", ipa: "/səkˈsɛsfəl/", spanish: "exitoso", example: "Mi tío tuvo un negocio de comida muy exitoso." },
  { id: "c1w_151", category: "Suffix", word: "useful", ipa: "/ˈjusfəl/", spanish: "útil", example: "Esa nueva herramienta de software te será útil." },
  { id: "c1w_152", category: "Suffix", word: "powerful", ipa: "/ˈpaʊərfəl/", spanish: "poderoso", example: "El motor de este coche deportivo es muy poderoso." },
  { id: "c1w_153", category: "Suffix", word: "careful", ipa: "/ˈkɛrfəl/", spanish: "cuidadoso", example: "Sé cuidadoso con esas copas de cristal fino." },
  { id: "c1w_154", category: "Suffix", word: "helpful", ipa: "/ˈhɛlpfəl/", spanish: "servicial", example: "El asistente de la tienda de ropa fue muy servicial." },
  { id: "c1w_155", category: "Suffix", word: "flawless", ipa: "/ˈflɔləs/", spanish: "impecable", example: "Después del maquillaje, su piel se ve impecable." },
  { id: "c1w_156", category: "Suffix", word: "careless", ipa: "/ˈkɛrləs/", spanish: "descuidado", example: "Perdió su teléfono por ser alguien muy descuidado." },
  { id: "c1w_157", category: "Suffix", word: "useless", ipa: "/ˈjusləs/", spanish: "inútil", example: "Intentar discutir contigo cuando estás enojado es inútil." },
  { id: "c1w_158", category: "Suffix", word: "homeless", ipa: "/ˈhoʊmləs/", spanish: "sin hogar", example: "En la ciudad hay un refugio para personas sin hogar." },
  { id: "c1w_159", category: "Suffix", word: "endless", ipa: "/ˈɛndləs/", spanish: "interminable", example: "El viaje en tren por las montañas pareció interminable." },
  { id: "c1w_160", category: "Suffix", word: "hopeless", ipa: "/ˈhoʊpləs/", spanish: "desesperanzado", example: "La situación parecía desesperanzada al inicio del mes." },
  { id: "c1w_161", category: "Suffix", word: "serious", ipa: "/ˈsɪriəs/", spanish: "serio", example: "Por favor, escúchame porque esto es un asunto muy serio." },
  { id: "c1w_162", category: "Suffix", word: "obvious", ipa: "/ˈɑbviəs/", spanish: "obvio", example: "El error de cálculo en la factura era muy obvio." },
  { id: "c1w_163", category: "Suffix", word: "previous", ipa: "/ˈpriviəs/", spanish: "anterior", example: "En mi puesto de trabajo anterior aprendí muchas cosas." },
  { id: "c1w_164", category: "Suffix", word: "dangerous", ipa: "/ˈdeɪndʒərəs/", spanish: "peligroso", example: "No camines solo de noche por ese barrio tan peligroso." },
  { id: "c1w_165", category: "Suffix", word: "religious", ipa: "/rɪˈlɪdʒəs/", spanish: "religioso", example: "La ceremonia de la boda tuvo un tono muy religioso." },
  { id: "c1w_166", category: "Suffix", word: "enormous", ipa: "/ɪˈnɔrməs/", spanish: "enorme", example: "En el restaurante nos sirvieron una porción enorme." },
  { id: "c1w_167", category: "Suffix", word: "effective", ipa: "/ɪˈfɛktɪv/", spanish: "efectivo", example: "Ese nuevo tratamiento médico resultó ser muy efectivo." },
  { id: "c1w_168", category: "Suffix", word: "active", ipa: "/ˈæktɪv/", spanish: "activo", example: "Siempre trato de mantenerme físicamente activo en casa." },
  { id: "c1w_169", category: "Suffix", word: "positive", ipa: "/ˈpɑzɪtɪv/", spanish: "positivo", example: "A pesar de todo, siempre hay que ver el lado positivo." },
  { id: "c1w_170", category: "Suffix", word: "expensive", ipa: "/ɪkˈspɛnsɪv/", spanish: "caro", example: "El vuelo a la ciudad de París está muy caro ahora." },
  { id: "c1w_171", category: "Suffix", word: "creative", ipa: "/kriˈeɪtɪv/", spanish: "creativo", example: "Para esta clase de arte necesitas ser muy creativo." },
  { id: "c1w_172", category: "Suffix", word: "attractive", ipa: "/əˈtræktɪv/", spanish: "atractivo", example: "Ese nuevo modelo de automóvil es visualmente atractivo." },
  { id: "c1w_173", category: "Suffix", word: "economic", ipa: "/ˌɛkəˈnɑmɪk/", spanish: "económico", example: "Lamentablemente el país sufre un problema económico." },
  { id: "c1w_174", category: "Suffix", word: "political", ipa: "/pəˈlɪtɪkəl/", spanish: "político", example: "El debate político en la televisión fue muy tenso." },
  { id: "c1w_175", category: "Suffix", word: "medical", ipa: "/ˈmɛdɪkəl/", spanish: "médico", example: "Necesitas pedir un certificado médico en la clínica." },
  { id: "c1w_176", category: "Suffix", word: "physical", ipa: "/ˈfɪzɪkəl/", spanish: "físico", example: "El trabajo físico pesado me deja totalmente agotado." },
  { id: "c1w_177", category: "Suffix", word: "historic", ipa: "/hɪˈstɔrɪk/", spanish: "histórico", example: "Ese edificio antiguo es considerado un monumento histórico." },
  { id: "c1w_178", category: "Suffix", word: "specific", ipa: "/spəˈsɪfɪk/", spanish: "específico", example: "Por favor, dame un ejemplo específico de ese problema." },
  { id: "c1w_179", category: "Suffix", word: "realize", ipa: "/ˈriəˌlaɪz/", spanish: "darse cuenta", example: "Acabo de darme cuenta del gran error que cometí." },
  { id: "c1w_180", category: "Suffix", word: "recognize", ipa: "/ˈrɛkəgˌnaɪz/", spanish: "reconocer", example: "Pude reconocer su voz por teléfono de inmediato." },
  { id: "c1w_181", category: "Suffix", word: "organize", ipa: "/ˈɔrgəˌnaɪz/", spanish: "organizar", example: "Me gusta organizar mis tareas and metas semanalmente." },
  { id: "c1w_182", category: "Suffix", word: "apologize", ipa: "/əˈpɑləˌdʒaɪz/", spanish: "disculparse", example: "Debes disculparte con ella por llegar tan tarde." },
  { id: "c1w_183", category: "Suffix", word: "memorize", ipa: "/ˈmɛməˌraɪz/", spanish: "memorizar", example: "Tuve que memorizar todo el discurso para la boda." },
  { id: "c1w_184", category: "Suffix", word: "criticize", ipa: "/ˈkrɪtɪˌsaɪz/", spanish: "criticar", example: "Definitivamente no es bueno criticar el trabajo de los demás." },
  { id: "c1w_185", category: "Suffix", word: "shorten", ipa: "/ˈʃɔrtən/", spanish: "acortar", example: "Puedes acortar el pantalón si sientes que te queda largo." },
  { id: "c1w_186", category: "Suffix", word: "widen", ipa: "/ˈwaɪdən/", spanish: "ensanchar", example: "El alcalde anunció que van a ensanchar la avenida principal." },
  { id: "c1w_187", category: "Suffix", word: "darken", ipa: "/ˈdɑrkən/", spanish: "oscurecer", example: "El cielo empezó a oscurecer rápidamente por la tormenta." },
  { id: "c1w_188", category: "Suffix", word: "threaten", ipa: "/ˈθrɛtən/", spanish: "amenazar", example: "El ladrón intentó amenazar a la cajera del banco." },
  { id: "c1w_189", category: "Suffix", word: "strengthen", ipa: "/ˈstreŋθən/", spanish: "fortalecer", example: "Hacer pesas diariamente va a fortalecer todos tus brazos." },
  { id: "c1w_190", category: "Suffix", word: "identify", ipa: "/aɪˈdɛntɪˌfaɪ/", spanish: "identificar", example: "Necesito que me ayudes a identificar al ladrón de ayer." },
  { id: "c1w_191", category: "Suffix", word: "justify", ipa: "/ˈdʒʌstəˌfaɪ/", spanish: "justificar", example: "No hay ninguna forma lógica de justificar sus acciones." },
  { id: "c1w_192", category: "Suffix", word: "satisfy", ipa: "/ˈsætɪsˌfaɪ/", spanish: "satisfacer", example: "Esa sopa caliente va a satisfacer tu hambre de inmediato." },
  { id: "c1w_193", category: "Suffix", word: "clarify", ipa: "/ˈklærəˌfaɪ/", spanish: "aclarar", example: "Llamé a la oficina para aclarar una duda sobre la factura." },
  { id: "c1w_194", category: "Suffix", word: "certify", ipa: "/ˈsɜrtɪˌfaɪ/", spanish: "certificar", example: "El abogado notario debe certificar las firmas del contrato." },
  { id: "c1w_195", category: "Suffix", word: "simply", ipa: "/ˈsɪmpli/", spanish: "simplemente", example: "Yo simplemente quería ayudar un poco con la limpieza." },
  { id: "c1w_196", category: "Suffix", word: "quickly", ipa: "/ˈkwɪkli/", spanish: "rápidamente", example: "Por favor, responde el mensaje de texto rápidamente." },
  { id: "c1w_197", category: "Suffix", word: "especially", ipa: "/əˈspɛʃəli/", spanish: "especialmente", example: "Me encanta escuchar música, especialmente el jazz clásico." },
  { id: "c1w_198", category: "Suffix", word: "completely", ipa: "/kəmˈplitli/", spanish: "completamente", example: "Estoy completamente de acuerdo con lo que acabas de decir." },
  { id: "c1w_199", category: "Suffix", word: "exactly", ipa: "/ɪgˈzæktli/", spanish: "exactamente", example: "El tren llegó a la estación exactamente a las ocho." },
  { id: "c1w_200", category: "Suffix", word: "finally", ipa: "/ˈfaɪnəli/", spanish: "finalmente", example: "Ellos finalmente compraron la casa de sus sueños." },
  { id: "c1w_201", category: "Suffix", word: "recently", ipa: "/ˈrisəntli/", spanish: "recientemente", example: "Empecé a hacer clases de yoga muy recientemente." },
  { id: "c1w_202", category: "Root", word: "aspect", ipa: "/ˈæspɛkt/", spanish: "aspecto", example: "Consideramos cada aspecto del nuevo proyecto." },
  { id: "c1w_203", category: "Root", word: "respect", ipa: "/rɪˈspɛkt/", spanish: "respeto", example: "El respeto mutuo es clave en el trabajo." },
  { id: "c1w_204", category: "Root", word: "inspect", ipa: "/ɪnˈspɛkt/", spanish: "inspeccionar", example: "El oficial va a inspeccionar el vehículo." },
  { id: "c1w_205", category: "Root", word: "prospect", ipa: "/ˈprɑspɛkt/", spanish: "perspectiva", example: "Tiene una gran perspectiva de ascenso laboral." },
  { id: "c1w_206", category: "Root", word: "suspect", ipa: "/səˈspɛkt/", spanish: "sospechar", example: "La policía empezó a sospechar del testigo." },
  { id: "c1w_207", category: "Root", word: "expect", ipa: "/ɪkˈspɛkt/", spanish: "esperar (expectativa)", example: "No puedes esperar que todo sea fácil." },
  { id: "c1w_208", category: "Root", word: "spectacle", ipa: "/ˈspɛktəkəl/", spanish: "espectáculo", example: "Los fuegos artificiales fueron un gran espectáculo." },
  { id: "c1w_209", category: "Root", word: "spectacular", ipa: "/spɛkˈtækjələr/", spanish: "espectacular", example: "La vista desde la montaña es espectacular." },
  { id: "c1w_210", category: "Root", word: "spectator", ipa: "/ˈspɛkˌteɪtər/", spanish: "espectador", example: "El estadio estaba lleno de espectadores." },
  { id: "c1w_211", category: "Root", word: "retrospect", ipa: "/ˈrɛtrəˌspɛkt/", spanish: "retrospectiva", example: "En retrospectiva, fue una excelente decisión." },
  { id: "c1w_212", category: "Root", word: "perspective", ipa: "/pərˈspɛktɪv/", spanish: "perspectiva", example: "Cambiar de perspectiva te ayuda a entender." },
  { id: "c1w_213", category: "Root", word: "introspective", ipa: "/ˌɪntrəˈspɛktɪv/", spanish: "introspectivo", example: "Él tuvo un momento muy introspectivo hoy." },
  { id: "c1w_214", category: "Root", word: "spectrum", ipa: "/ˈspɛktrəm/", spanish: "espectro", example: "El espectro de luz incluye muchos colores." },
  { id: "c1w_215", category: "Root", word: "inspector", ipa: "/ɪnˈspɛktər/", spanish: "inspector", example: "El inspector revisó las normas de seguridad." },
  { id: "c1w_216", category: "Root", word: "unexpected", ipa: "/ˌʌnɪkˈspɛktɪd/", spanish: "inesperado", example: "Tuvimos un gasto inesperado este mes." },
  { id: "c1w_217", category: "Root", word: "irrespective", ipa: "/ˌɪrɪˈspɛktɪv/", spanish: "independientemente", example: "Todos irán, independientemente del clima." },
  { id: "c1w_218", category: "Root", word: "circumspect", ipa: "/ˈsɜrkəmˌspɛkt/", spanish: "cauto", example: "Debes ser cauto con tus nuevas inversiones." },
  { id: "c1w_219", category: "Root", word: "respectable", ipa: "/rɪˈspɛktəbl/", spanish: "respetable", example: "Es un hombre muy respetable en su ciudad." },
  { id: "c1w_220", category: "Root", word: "predict", ipa: "/prɪˈdɪkt/", spanish: "predecir", example: "Nadie puede predecir el futuro con certeza." },
  { id: "c1w_221", category: "Root", word: "predictable", ipa: "/prɪˈdɪktəbl/", spanish: "predecible", example: "El final de la película fue muy predecible." },
  { id: "c1w_222", category: "Root", word: "dictate", ipa: "/ˈdɪkteɪt/", spanish: "dictar", example: "El profesor empezó a dictar las nuevas reglas." },
  { id: "c1w_223", category: "Root", word: "dictator", ipa: "/ˈdɪkteɪtər/", spanish: "dictador", example: "El dictador gobernó el país con mano dura." },
  { id: "c1w_224", category: "Root", word: "dictionary", ipa: "/ˈdɪkʃəˌnɛri/", spanish: "diccionario", example: "Busca esa palabra en el diccionario de inglés." },
  { id: "c1w_225", category: "Root", word: "contradict", ipa: "/ˌkɑntrəˈdɪkt/", spanish: "contradecir", example: "No me vuelvas a contradecir en público." },
  { id: "c1w_226", category: "Root", word: "contradiction", ipa: "/ˌkɑntrəˈdɪkʃən/", spanish: "contradicción", example: "Su testimonio fue una completa contradicción." },
  { id: "c1w_227", category: "Root", word: "verdict", ipa: "/ˈvɜrdɪkt/", spanish: "veredicto", example: "El jurado leyó el veredicto final hoy." },
  { id: "c1w_228", category: "Root", word: "addict", ipa: "/ˈædɪkt/", spanish: "adicto", example: "Él se volvió adicto a los videojuegos." },
  { id: "c1w_229", category: "Root", word: "addiction", ipa: "/əˈdɪkʃən/", spanish: "adicción", example: "Superar una adicción requiere mucho esfuerzo." },
  { id: "c1w_230", category: "Root", word: "indicate", ipa: "/ˈɪndɪˌkeɪt/", spanish: "indicar", example: "La señal debe indicar la salida de emergencia." },
  { id: "c1w_231", category: "Root", word: "indicator", ipa: "/ˈɪndɪˌkeɪtər/", spanish: "indicador", example: "El termómetro es un indicador de la temperatura." },
  { id: "c1w_232", category: "Root", word: "dedicate", ipa: "/ˈdɛdɪˌkeɪt/", spanish: "dedicar", example: "Quiero dedicar esta canción a mi familia." },
  { id: "c1w_233", category: "Root", word: "vindicate", ipa: "/ˈvɪndɪˌkeɪt/", spanish: "vindicarse", example: "Las pruebas lograron vindicar su innocence." },
  { id: "c1w_234", category: "Root", word: "jurisdiction", ipa: "/ˌdʒʊrɪsˈdɪkʃən/", spanish: "jurisdicción", example: "Ese caso no está en mi jurisdicción legal." },
  { id: "c1w_235", category: "Root", word: "edict", ipa: "/ˈidɪkt/", spanish: "edicto", example: "El rey emitió un nuevo edicto oficial." },
  { id: "c1w_236", category: "Root", word: "dictation", ipa: "/dɪkˈteɪʃən/", spanish: "dictado", example: "Haremos un ejercicio de dictado en clase." },
  { id: "c1w_237", category: "Root", word: "project", ipa: "/ˈprɑdʒɛkt/", spanish: "proyecto", example: "El proyecto de ciencias tomará dos meses." },
  { id: "c1w_238", category: "Root", word: "reject", ipa: "/rɪˈdʒɛkt/", spanish: "rechazar", example: "Tuvieron que rechazar la oferta de trabajo." },
  { id: "c1w_239", category: "Root", word: "inject", ipa: "/ɪnˈdʒɛkt/", spanish: "inyectar", example: "El médico te va a inyectar la vacuna." },
  { id: "c1w_240", category: "Root", word: "subject", ipa: "/ˈsʌbdʒɪkt/", spanish: "sujeto / tema", example: "Ese es un tema muy delicado de tratar." },
  { id: "c1w_241", category: "Root", word: "object", ipa: "/ˈɑbdʒɛkt/", spanish: "objetar", example: "No tengo razón para objetar tu gran idea." },
  { id: "c1w_242", category: "Root", word: "objective", ipa: "/əbˈdʒɛktɪv/", spanish: "objetivo", example: "Nuestro objetivo es aumentar las ventas." },
  { id: "c1w_243", category: "Root", word: "objection", ipa: "/əbˈdʒɛkʃən/", spanish: "objeción", example: "El abogado presentó una fuerte objeción." },
  { id: "c1w_244", category: "Root", word: "trajectory", ipa: "/trəˈdʒɛktəri/", spanish: "trayectoria", example: "El cohete desvió su trayectoria inicial." },
  { id: "c1w_245", category: "Root", word: "conjecture", ipa: "/kənˈdʒɛktʃər/", spanish: "conjetura", example: "Eso es solo una conjetura, no un hecho." },
  { id: "c1w_246", category: "Root", word: "dejected", ipa: "/dɪˈdʒɛktɪd/", spanish: "abatido", example: "Se sintió abatido después de perder el partido." },
  { id: "c1w_247", category: "Root", word: "eject", ipa: "/ɪˈdʒɛkt/", spanish: "expulsar", example: "El piloto tuvo que expulsar su asiento." },
  { id: "c1w_248", category: "Root", word: "projector", ipa: "/prəˈdʒɛktər/", spanish: "proyector", example: "Enciende el proyector para la presentación." },
  { id: "c1w_249", category: "Root", word: "interject", ipa: "/ˌɪntərˈdʒɛkt/", spanish: "interrumpir", example: "Déjame interrumpir con un comentario rápido." },
  { id: "c1w_250", category: "Root", word: "subjective", ipa: "/səbˈdʒɛktɪv/", spanish: "subjetivo", example: "El arte es siempre un tema muy subjetivo." },
  { id: "c1w_251", category: "Root", word: "projection", ipa: "/prəˈdʒɛkʃən/", spanish: "proyección", example: "La proyección de ventas es muy positiva." },
  { id: "c1w_252", category: "Root", word: "rejection", ipa: "/rɪˈdʒɛkʃən/", spanish: "rechazo", example: "El miedo al rechazo es algo muy común." },
  { id: "c1w_253", category: "Root", word: "extract", ipa: "/ɪkˈstrækt/", spanish: "extraer", example: "El dentista tuvo que extraer una muela." },
  { id: "c1w_254", category: "Root", word: "contract", ipa: "/ˈkɑntrækt/", spanish: "contrato", example: "Ayer firmamos el contrato de arrendamiento." },
  { id: "c1w_255", category: "Root", word: "attract", ipa: "/əˈtrækt/", spanish: "atraer", example: "Las flores coloridas suelen atraer abejas." },
  { id: "c1w_256", category: "Root", word: "attractive", ipa: "/əˈtræktɪv/", spanish: "atractivo", example: "El diseño del coche es visualmente atractivo." },
  { id: "c1w_257", category: "Root", word: "distract", ipa: "/dɪˈstrækt/", spanish: "distraer", example: "El ruido de la calle me suele distraer." },
  { id: "c1w_258", category: "Root", word: "distraction", ipa: "/dɪˈstrækʃən/", spanish: "distracción", example: "El celular es una gran distracción al estudiar." },
  { id: "c1w_259", category: "Root", word: "subtract", ipa: "/səbˈtrækt/", spanish: "restar", example: "Si vas a restar dos, el resultado es diez." },
  { id: "c1w_260", category: "Root", word: "tractor", ipa: "/ˈtræktər/", spanish: "tractor", example: "El granjero compró un nuevo tractor rojo." },
  { id: "c1w_261", category: "Root", word: "abstract", ipa: "/ˈæbstrækt/", spanish: "abstracto", example: "Esa pintura es de estilo muy abstracto." },
  { id: "c1w_262", category: "Root", word: "retract", ipa: "/rɪˈretract/", spanish: "retractarse", example: "Él tuvo que retractarse de sus palabras." },
  { id: "c1w_263", category: "Root", word: "protracted", ipa: "/proʊˈtræktɪd/", spanish: "prolongado", example: "Tuvieron una batalla legal muy prolongada." },
  { id: "c1w_264", category: "Root", word: "intractable", ipa: "/ɪnˈtræktəbl/", spanish: "intratable", example: "El problema de matemáticas resultó intratable." },
  { id: "c1w_265", category: "Root", word: "traction", ipa: "/ˈtrækʃən/", spanish: "tracción", example: "Las llantas nuevas tienen una excelente tracción." },
  { id: "c1w_266", category: "Root", word: "contraction", ipa: "/kənˈtrækʃən/", spanish: "contracción", example: "El frío extremo causa la contracción del metal." },
  { id: "c1w_267", category: "Root", word: "extraction", ipa: "/ɪkˈstrækʃən/", spanish: "extracción", example: "La extracción de petróleo es muy costosa." },
  { id: "c1w_268", category: "Root", word: "detract", ipa: "/dɪˈtrækt/", spanish: "restar valor", example: "El mal clima no pudo restar valor al viaje." },
  { id: "c1w_269", category: "Root", word: "benefit", ipa: "/ˈbɛnəfɪt/", spanish: "beneficio", example: "El ejercicio tiene un gran beneficio para ti." },
  { id: "c1w_270", category: "Root", word: "beneficial", ipa: "/ˌbɛnəˈfɪʃəl/", spanish: "beneficioso", example: "Beber agua es muy beneficioso para la salud." },
  { id: "c1w_271", category: "Root", word: "benefactor", ipa: "/ˈbɛnəˌfæktər/", spanish: "benefactor", example: "El hospital fue donado por un benefactor." },
  { id: "c1w_272", category: "Root", word: "benevolent", ipa: "/bəˈnɛvələnt/", spanish: "benevolente", example: "El rey fue un líder sabio y benevolente." },
  { id: "c1w_273", category: "Root", word: "benediction", ipa: "/ˌbɛnɪˈdɪkʃən/", spanish: "bendición", example: "El sacerdote dio su bendición al final." },
  { id: "c1w_274", category: "Root", word: "beneficiary", ipa: "/ˌbɛnəˈfɪʃiˌɛri/", spanish: "beneficiario", example: "Ella es la única beneficiaria del seguro." },
  { id: "c1w_275", category: "Root", word: "benign", ipa: "/bɪˈnaɪn/", spanish: "benigno", example: "Afortunadamente, el tumor resultó ser benigno." },
  { id: "c1w_276", category: "Root", word: "beneficent", ipa: "/bɪˈnɛfɪsənt/", spanish: "benéfico", example: "Realizaron una gran obra de carácter benéfico." },
  { id: "c1w_277", category: "Root", word: "benevolently", ipa: "/bəˈnɛvələntli/", spanish: "benevolentemente", example: "El líder sonrió benevolentemente a su pueblo." },
  { id: "c1w_278", category: "Root", word: "beneficence", ipa: "/bɪˈnɛfɪsəns/", spanish: "beneficencia", example: "La beneficencia ayuda a los más necesitados." },
  { id: "c1w_279", category: "Root", word: "malicious", ipa: "/məˈlɪʃəs/", spanish: "malicioso", example: "El virus borró todo por un código malicioso." },
  { id: "c1w_280", category: "Root", word: "malfunction", ipa: "/mælˈfʌŋkʃən/", spanish: "falla", example: "Hubo una falla mecánica en el motor del avión." },
  { id: "c1w_281", category: "Root", word: "malnutrition", ipa: "/ˌmælnuˈtrɪʃən/", spanish: "desnutrición", example: "Muchos niños sufren de desnutrición aguda." },
  { id: "c1w_282", category: "Root", word: "malignant", ipa: "/məˈlɪgnənt/", spanish: "maligno", example: "El doctor confirmó que el tejido era maligno." },
  { id: "c1w_283", category: "Root", word: "malice", ipa: "/ˈmælɪs/", spanish: "malicia", example: "Él me habló sin ninguna malicia en su tono." },
  { id: "c1w_284", category: "Root", word: "malevolent", ipa: "/məˈlɛvələnt/", spanish: "malévolo", example: "El villano tenía un plan bastante malévolo." },
  { id: "c1w_285", category: "Root", word: "malware", ipa: "/ˈmælwɛr/", spanish: "software malicioso", example: "Instala un antivirus para evitar el malware." },
  { id: "c1w_286", category: "Root", word: "malpractice", ipa: "/mælˈpræktɪs/", spanish: "negligencia", example: "El doctor fue demandado por negligencia médica." },
  { id: "c1w_287", category: "Root", word: "malady", ipa: "/ˈmælədi/", spanish: "enfermedad", example: "Padecía una extraña enfermedad tropical grave." },
  { id: "c1w_288", category: "Root", word: "dismal", ipa: "/ˈdɪzməl/", spanish: "deprimente", example: "El clima durante las vacaciones fue deprimente." },
  { id: "c1w_289", category: "Root", word: "malnourished", ipa: "/mælˈnɜrɪʃt/", spanish: "desnutrido", example: "Encontraron un perrito desnutrido en la calle." },
  { id: "c1w_290", category: "Root", word: "chronic", ipa: "/ˈɑnɪk/", spanish: "crónico", example: "Mi abuelo sufre de dolor de espalda crónico." },
  { id: "c1w_291", category: "Root", word: "chronicle", ipa: "/ˈkrɑnɪkəl/", spanish: "crónica", example: "El libro es una detallada crónica de la guerra." },
  { id: "c1w_292", category: "Root", word: "chronology", ipa: "/krəˈnɑlədʒi/", spanish: "cronología", example: "Necesito entender la cronología de los eventos." },
  { id: "c1w_293", category: "Root", word: "chronological", ipa: "/ˌkrɑnəˈlɑdʒɪkəl/", spanish: "cronológico", example: "Ordena los documentos en orden cronológico." },
  { id: "c1w_294", category: "Root", word: "synchronize", ipa: "/ˈsɪŋkrəˌnaɪz/", spanish: "sincronizar", example: "Vamos a sincronizar nuestros relojes ahora." },
  { id: "c1w_295", category: "Root", word: "synchronous", ipa: "/ˈsɪŋkrənəs/", spanish: "sincrónico", example: "La clase en línea será en formato sincrónico." },
  { id: "c1w_296", category: "Root", word: "anachronism", ipa: "/əˈnækrəˌnɪzəm/", spanish: "anacronismo", example: "Ver un reloj en esa película antigua es un anacronismo." },
  { id: "c1w_297", category: "Root", word: "chronometer", ipa: "/krəˈnɑmɪtər/", spanish: "cronómetro", example: "El entrenador usó un cronómetro para la carrera." },
  { id: "c1w_298", category: "Root", word: "synchronization", ipa: "/ˌsɪŋkrənəˈzeɪʃən/", spanish: "sincronización", example: "La sincronización de datos de la red falló ayer." },
  { id: "c1w_299", category: "Root", word: "asynchronous", ipa: "/eɪˈsɪŋkrənəs/", spanish: "asincrónico", example: "El curso permite un aprendizaje asincrónico flexible." },
  { id: "c1w_300", category: "Root", word: "chronically", ipa: "/ˈkrɑnɪkli/", spanish: "crónicamente", example: "El hospital está crónicamente falto de personal." },
  { id: "c1w_301", category: "Root", word: "anachronistic", ipa: "/əˌnækrəˈnɪstɪk/", spanish: "anacrónico", example: "Su forma de pensar es muy anticuada and anacrónica." },
  { id: "c1w_302", category: "Collocation", word: "mitigate the risk", ipa: "/ˈmɪtɪgeɪt ðə rɪsk/", spanish: "mitigar el riesgo", example: "La empresa tomó medidas para mitigar el riesgo financiero." },
  { id: "c1w_303", category: "Collocation", word: "mitigate the impact", ipa: "/ˈmɪtɪgeɪt ði ˈɪmpækt/", spanish: "mitigar el impacto", example: "Plantaron árboles para mitigar el impacto ambiental." },
  { id: "c1w_304", category: "Collocation", word: "utterly ridiculous", ipa: "/ˈʌtərli rɪˈdɪkjələs/", spanish: "completamente ridículo", example: "El precio de esa chaqueta es completamente ridículo." },
  { id: "c1w_305", category: "Collocation", word: "utterly exhausted", ipa: "/ˈʌtərli ɪgˈzɔstɪd/", spanish: "completamente exhausto", example: "Después de correr, quedé completamente exhausto." },
  { id: "c1w_306", category: "Collocation", word: "foster a relationship", ipa: "/ˈfɑstər ə rɪˈleɪʃənˌʃɪp/", spanish: "fomentar una relación", example: "Es vital fomentar una relación de confianza." },
  { id: "c1w_307", category: "Collocation", word: "foster growth", ipa: "/ˈfɑstər groʊθ/", spanish: "fomentar el crecimiento", example: "El nuevo plan busca fomentar el crecimiento económico." },
  { id: "c1w_308", category: "Collocation", word: "conceive of", ipa: "/kənˈsiv ʌv/", spanish: "concebir (la idea de)", example: "No puedo concebir la idea de vivir sin internet." },
  { id: "c1w_309", category: "Collocation", word: "detrimental effect", ipa: "/ˌdɛtrəˈmɛntəl ɪˈfɛkt/", spanish: "efecto perjudicial", example: "Fumar tiene un efecto perjudicial en los pulmones." },
  { id: "c1w_310", category: "Collocation", word: "highly unlikely", ipa: "/ˈhaɪli ənˈlaɪkli/", spanish: "muy improbable", example: "Es muy improbable que el tren llegue temprano hoy." },
  { id: "c1w_311", category: "Collocation", word: "highly successful", ipa: "/ˈhaɪli səkˈsɛsfəl/", spanish: "muy exitoso", example: "Su última novela fue un proyecto muy exitoso." },
  { id: "c1w_312", category: "Collocation", word: "heavily influenced", ipa: "/ˈhɛvəli ˈinfluənst/", spanish: "fuertemente influenciado", example: "Su estilo está fuertemente influenciado por el jazz." },
  { id: "c1w_313", category: "Collocation", word: "heavily rely on", ipa: "/ˈhɛvəli rɪˈlaɪ ɑn/", spanish: "depender fuertemente de", example: "No deberías depender fuertemente de una sola fuente." },
  { id: "c1w_314", category: "Collocation", word: "deeply offended", ipa: "/ˈdipli əˈfɛndɪd/", spanish: "profundamente ofendido", example: "Él se sintió profundamente ofendido por tu comentario." },
  { id: "c1w_315", category: "Collocation", word: "deeply divided", ipa: "/ˈdipli dɪˈvaɪdɪd/", spanish: "profundamente dividido", example: "El país estaba profundamente dividido por la nueva ley." },
  { id: "c1w_316", category: "Collocation", word: "deeply concerned", ipa: "/ˈdipli kənˈsɜrnd/", spanish: "profundamente preocupado", example: "Estamos profundamente preocupados por la situación actual." },
  { id: "c1w_317", category: "Collocation", word: "strictly forbidden", ipa: "/ˈstrɪktli fərˈbɪdən/", spanish: "estrictamente prohibido", example: "Usar el celular aquí está estrictamente prohibido." },
  { id: "c1w_318", category: "Collocation", word: "strictly limited", ipa: "/ˈstrɪktli ˈlɪmɪtɪd/", spanish: "estrictamente limitado", example: "El acceso a esta zona está estrictamente limitado." },
  { id: "c1w_319", category: "Collocation", word: "strictly speaking", ipa: "/ˈstrɪktli ˈspikɪŋ/", spanish: "estrictamente hablando", example: "Estrictamente hablando, un tomate es una fruta." },
  { id: "c1w_320", category: "Collocation", word: "blissfully unaware", ipa: "/ˈblɪsfəli ˌʌnəˈwɛr/", spanish: "felizmente ignorante", example: "Él vivía felizmente ignorante del peligro real." },
  { id: "c1w_321", category: "Collocation", word: "bitterly cold", ipa: "/ˈbɪtərli koʊld/", spanish: "amargamente frío", example: "El viento de esta mañana era amargamente frío." },
  { id: "c1w_322", category: "Collocation", word: "bitterly disappointed", ipa: "/ˈbɪtərli ˌdɪsəˈpɔɪntɪd/", spanish: "amargamente decepcionado", example: "Quedé amargamente decepcionado con los resultados." },
  { id: "c1w_323", category: "Collocation", word: "fiercely competitive", ipa: "/ˈfɪrsli kəmˈpɛtɪtɪv/", spanish: "ferozmente competitivo", example: "El mercado tecnológico es ferozmente competitivo." },
  { id: "c1w_324", category: "Collocation", word: "fiercely loyal", ipa: "/ˈfɪrsli ˈlɔɪəl/", spanish: "ferozmente leal", example: "Ese perro es ferozmente leal a su dueño." },
  { id: "c1w_325", category: "Collocation", word: "fiercely independent", ipa: "/ˈfɪrsli ˌɪndɪˈpɛndənt/", spanish: "ferozmente independiente", example: "Ella siempre ha sido una mujer ferozmente independiente." },
  { id: "c1w_326", category: "Collocation", word: "strongly agree", ipa: "/ˈstrɔŋli əˈgri/", spanish: "totalmente de acuerdo", example: "Estoy totalmente de acuerdo con tu propuesta." },
  { id: "c1w_327", category: "Collocation", word: "strongly advise", ipa: "/ˈstrɔŋli ædˈvaɪz/", spanish: "recomendar encarecidamente", example: "Te recomiendo encarecidamente que leas este libro." },
  { id: "c1w_328", category: "Collocation", word: "strongly opposed", ipa: "/ˈstrɔŋli əˈpoʊzd/", spanish: "fuertemente opuesto", example: "El comité está fuertemente opuesto a la medida." },
  { id: "c1w_329", category: "Collocation", word: "widely accepted", ipa: "/ˈwaɪdli ækˈsɛptɪd/", spanish: "ampliamente aceptado", example: "Esa teoría científica es ampliamente aceptada." },
  { id: "c1w_330", category: "Collocation", word: "widely available", ipa: "/ˈwaɪdli əˈveɪləbl/", spanish: "ampliamente disponible", example: "La medicina ahora está ampliamente disponible en farmacias." },
  { id: "c1w_331", category: "Collocation", word: "widely recognized", ipa: "/ˈwaɪdli ˈrɛkəgˌnaɪzd/", spanish: "ampliamente reconocido", example: "Es un artista ampliamente reconocido en Europa." },
  { id: "c1w_332", category: "Collocation", word: "vaguely remember", ipa: "/ˈvɛgli rɪˈmɛmbər/", spanish: "recordar vagamente", example: "Solo logro recordar vagamente nuestro primer encuentro." },
  { id: "c1w_333", category: "Collocation", word: "distinctly remember", ipa: "/dɪˈstɪŋktli rɪˈmɛmbər/", spanish: "recordar claramente", example: "Puedo recordar claramente el día que nos conocimos." },
  { id: "c1w_334", category: "Collocation", word: "acutely aware", ipa: "/əˈkjutli əˈwɛr/", spanish: "plenamente consciente", example: "Soy plenamente consciente de los riesgos involucrados." },
  { id: "c1w_335", category: "Collocation", word: "abundantly clear", ipa: "/əˈbʌndəntli klɪr/", spanish: "sumamente claro", example: "Su mensaje de rechazo fue sumamente claro." },
  { id: "c1w_336", category: "Collocation", word: "painfully obvious", ipa: "/ˈpeɪnfəli ˈɑbviəs/", spanish: "dolorosamente obvio", example: "Era dolorosamente obvio que él estaba mintiendo." },
  { id: "c1w_337", category: "Collocation", word: "perfectly normal", ipa: "/ˈpɜrfɪktli ˈnɔrməl/", spanish: "perfectamente normal", example: "Es perfectamente normal sentirse nervioso antes del examen." },
  { id: "c1w_338", category: "Collocation", word: "perfectly capable", ipa: "/ˈpɜrfɪktli ˈkeɪpəbl/", spanish: "perfectamente capaz", example: "Ella es perfectamente capaz de hacer el trabajo sola." },
  { id: "c1w_339", category: "Collocation", word: "readily available", ipa: "/ˈrɛdəli əˈveɪləbl/", spanish: "fácilmente disponible", example: "La información está fácilmente disponible en la web." },
  { id: "c1w_340", category: "Collocation", word: "virtually impossible", ipa: "/ˈvɜrʧuəli ɪmˈpɑsəbl/", spanish: "prácticamente imposible", example: "Es prácticamente imposible terminar esto hoy." },
  { id: "c1w_341", category: "Collocation", word: "somewhat reluctant", ipa: "/ˈsʌmwʌt rɪˈlʌktənt/", spanish: "algo reacio", example: "Él se mostró algo reacio a firmar el contrato." },
  { id: "c1w_342", category: "Collocation", word: "relatively speaking", ipa: "/ˈrɛlətɪvli ˈspikɪŋ/", spanish: "relativamente hablando", example: "Relativamente hablando, esta ciudad es muy económica." },
  { id: "c1w_343", category: "Collocation", word: "fundamentally different", ipa: "/ˌfʌndəˈmɛntəli ˈdɪfərənt/", spanish: "fundamentalmente diferente", example: "Ambas ideas son fundamentalmente diferentes en la práctica." },
  { id: "c1w_344", category: "Collocation", word: "completely ignore", ipa: "/kəmˈplitli ɪgˈnɔr/", spanish: "ignorar por completo", example: "Decidió ignorar por completo mis advertencias." },
  { id: "c1w_345", category: "Collocation", word: "entirely sure", ipa: "/ɪnˈtaɪərli ʃʊr/", spanish: "completamente seguro", example: "No estoy completamente seguro de poder asistir a la cena." },
  { id: "c1w_346", category: "Collocation", word: "fully understand", ipa: "/ˈfʊli ˌʌndərˈstænd/", spanish: "entender completamente", example: "Aún no logro entender completamente tus verdaderos motivos." },
  { id: "c1w_347", category: "Collocation", word: "gravely ill", ipa: "/ˈgreɪvli ɪl/", spanish: "gravemente enfermo", example: "Su abuelo ha estado gravemente enfermo todo este mes." },
  { id: "c1w_348", category: "Collocation", word: "desperately need", ipa: "/ˈdɛspərətli nid/", spanish: "necesitar desesperadamente", example: "El hospital necesita desesperadamente más fondos este año." },
  { id: "c1w_349", category: "Collocation", word: "actively encourage", ipa: "/ˈæktɪvli ɛnˈkɜrɪdʒ/", spanish: "fomentar activamente", example: "El colegio busca fomentar activamente la lectura diaria." },
  { id: "c1w_350", category: "Collocation", word: "tentatively agree", ipa: "/ˈtɛntətɪvli əˈgri/", spanish: "acordar tentativamente", example: "Decidimos acordar tentativamente una fecha para el evento." },
  { id: "c1w_351", category: "Collocation", word: "unanimously vote", ipa: "/juˈnænəməsli voʊt/", spanish: "votar por unanimidad", example: "El comité decidió votar por unanimidad la nueva ley." },
  { id: "c1w_352", category: "Collocation", word: "cautiously optimistic", ipa: "/ˈkɔʃəsli ˌɑptəˈmɪstɪk/", spanish: "cautelosamente optimista", example: "Soy cautelosamente optimista sobre nuestra victoria final." },
  { id: "c1w_353", category: "Collocation", word: "profoundly impact", ipa: "/prəˈfaʊndli ˈɪmpækt/", spanish: "impactar profundamente", example: "La noticia logró impactar profundamente a toda la familia." },
  { id: "c1w_354", category: "Collocation", word: "seriously doubt", ipa: "/ˈsɪriəsli daʊt/", spanish: "dudar seriamente", example: "Empiezo a dudar seriamente de su capacidad de liderazgo." },
  { id: "c1w_355", category: "Collocation", word: "sincerely hope", ipa: "/sɪnˈsɪrli hoʊp/", spanish: "esperar sinceramente", example: "Yo de verdad espero sinceramente que te mejores pronto." },
  { id: "c1w_356", category: "Collocation", word: "address the issue", ipa: "/əˈdrɛs ði ˈɪʃu/", spanish: "abordar el problema", example: "Es urgente abordar el problema de la contaminación local." },
  { id: "c1w_357", category: "Collocation", word: "tackle the problem", ipa: "/ˈtækəl ðə ˈprɑbləm/", spanish: "atajar el problema", example: "El gobierno prometió atajar el problema del desempleo." },
  { id: "c1w_358", category: "Collocation", word: "pose a threat", ipa: "/poʊz ə θrɛt/", spanish: "suponer una amenaza", example: "El cambio climático supone una amenaza global inminente." },
  { id: "c1w_359", category: "Collocation", word: "pose a risk", ipa: "/poʊz ə rɪsk/", spanish: "representar un riesgo", example: "Esa gran grieta puede representar un riesgo estructural." },
  { id: "c1w_360", category: "Collocation", word: "pose a challenge", ipa: "/poʊz ə ˈʧælənʤ/", spanish: "suponer un reto", example: "El nuevo mercado va a suponer un reto para nosotros." },
  { id: "c1w_361", category: "Collocation", word: "implement a policy", ipa: "/ˈɪmpləmənt ə ˈpɑləsi/", spanish: "implementar una política", example: "Van a implementar una política de cero papel pronto." },
  { id: "c1w_362", category: "Collocation", word: "implement a strategy", ipa: "/ˈɪmpləmənt ə ˈstrætəʤi/", spanish: "implementar una estrategia", example: "Necesitamos implementar una estrategia de ventas mejor." },
  { id: "c1w_363", category: "Collocation", word: "allocate resources", ipa: "/ˈæləˌkeɪt ˈrisɔrsɪz/", spanish: "asignar recursos", example: "Es difícil asignar recursos cuando hay poco dinero extra." },
  { id: "c1w_364", category: "Collocation", word: "allocate funds", ipa: "/ˈæləˌkeɪt fʌndz/", spanish: "asignar fondos", example: "El congreso debe asignar fondos para la educación pública." },
  { id: "c1w_365", category: "Collocation", word: "yield results", ipa: "/jild rɪˈzʌlts/", spanish: "dar resultados", example: "El nuevo método de estudio empezó a dar resultados positivos." },
  { id: "c1w_366", category: "Collocation", word: "provoke a reaction", ipa: "/prəˈvoʊk ə riˈækʃən/", spanish: "provocar una reacción", example: "Su discurso buscaba provocar una reacción en el público." },
  { id: "c1w_367", category: "Collocation", word: "provoke outrage", ipa: "/prəˈvoʊk ˈaʊtˌreɪdʒ/", spanish: "provocar indignación", example: "El escándalo no tardó en provocar indignación general." },
  { id: "c1w_368", category: "Collocation", word: "trigger a response", ipa: "/ˈtrɪgər ə rɪˈspɑns/", spanish: "desencadenar una respuesta", example: "El medicamento puede desencadenar una respuesta alérgica." },
  { id: "c1w_369", category: "Collocation", word: "trigger a memory", ipa: "/ˈtrɪgər ə ˈmɛməri/", spanish: "evocar un recuerdo", example: "Ese olor a café suele evocar un recuerdo de mi infancia." },
  { id: "c1w_370", category: "Collocation", word: "undergo surgery", ipa: "/ˌʌndərˈgoʊ ˈsɜrʤəri/", spanish: "someterse a cirugía", example: "El atleta profesional tendrá que someterse a cirugía de rodilla." },
  { id: "c1w_371", category: "Collocation", word: "undergo a transformation", ipa: "/ˌʌndərˈgoʊ ə ˌtrænsfərˈmeɪʃən/", spanish: "experimentar una transformación", example: "La ciudad logró experimentar una transformación increíble ayer." },
  { id: "c1w_372", category: "Collocation", word: "exceed expectations", ipa: "/ɪkˈsid ˌɛkspɛkˈteɪʃənz/", spanish: "superar las expectativas", example: "El hotel logró superar las expectativas de todos los huéspedes." },
  { id: "c1w_373", category: "Collocation", word: "meet the criteria", ipa: "/mit ðə kraɪˈtɪriə/", spanish: "cumplir los criterios", example: "Su currículum lamentablemente no logra cumplir los criterios exigidos." },
  { id: "c1w_374", category: "Collocation", word: "fulfill a requirement", ipa: "/fʊlˈfɪl ə rɪˈkwaɪərmənt/", spanish: "cumplir un requisito", example: "Debes cumplir un requisito de edad para ingresar al club." },
  { id: "c1w_375", category: "Collocation", word: "violate a rule", ipa: "/ˈvaɪəˌleɪt ə rul/", spanish: "violar una regla", example: "Si decides violar una regla, habrá graves consecuencias legales." },
  { id: "c1w_376", category: "Collocation", word: "undermine authority", ipa: "/ˌʌndərˈmaɪn əˈθɔrəti/", spanish: "socavar la autoridad", example: "No intentes socavar la autoridad del jefe frente al equipo." },
  { id: "c1w_377", category: "Collocation", word: "undermine confidence", ipa: "/ˌʌndərˈmaɪn ˈkɑnfədəns/", spanish: "socavar la confianza", example: "Tantas críticas negativas pueden socavar la confianza del niño." },
  { id: "c1w_378", category: "Collocation", word: "lack credibility", ipa: "/læk ˌkrɛdəˈbɪlɪti/", spanish: "carecer de credibilidad", example: "El informe financiero parece carecer de credibilidad técnica hoy." },
  { id: "c1w_379", category: "Collocation", word: "gain insight", ipa: "/geɪn ˈinˌsaɪt/", spanish: "ganar perspectiva", example: "Leer este libro te ayuda a ganar perspectiva sobre el mundo." },
  { id: "c1w_380", category: "Collocation", word: "shed light on", ipa: "/ʃɛd laɪt ɑn/", spanish: "arrojar luz sobre", example: "El documental busca arrojar luz sobre este conflicto olvidado." },
  { id: "c1w_381", category: "Collocation", word: "cast doubt on", ipa: "/kæst daʊt ɑn/", spanish: "poner en duda", example: "Esa nueva prueba nos hace poner en duda su coartada oficial." },
  { id: "c1w_382", category: "Collocation", word: "draw a conclusion", ipa: "/drɔ ə kənˈkluʒən/", spanish: "sacar una conclusión", example: "Es muy pronto para sacar una conclusión definitiva del estudio." },
  { id: "c1w_383", category: "Collocation", word: "draw a comparison", ipa: "/drɔ ə kəmˈpɛrəsən/", spanish: "establecer una comparación", example: "Podemos establecer una comparación entre ambas leyes fiscales." },
  { id: "c1w_384", category: "Collocation", word: "strike a balance", ipa: "/straɪk ə ˈbæləns/", spanish: "encontrar un equilibrio", example: "Debes encontrar un equilibrio entre el trabajo and tu vida." },
  { id: "c1w_385", category: "Collocation", word: "reach a consensus", ipa: "/riʧ ə kənˈsɛnsəs/", spanish: "llegar a un consenso", example: "El grupo de trabajo no pudo llegar a un consenso ayer." },
  { id: "c1w_386", category: "Collocation", word: "reach an agreement", ipa: "/riʧ ən əˈgrimənt/", spanish: "llegar a un acuerdo", example: "Esperamos llegar a un acuerdo comercial antes del viernes." },
  { id: "c1w_387", category: "Collocation", word: "reach a compromise", ipa: "/riʧ ə ˈkɑmprəˌmaɪz/", spanish: "llegar a un compromiso", example: "Ambas partes tuvieron que llegar a un compromiso mutuo." },
  { id: "c1w_388", category: "Collocation", word: "compelling evidence", ipa: "/kəmˈpɛlɪŋ ˈɛvədəns/", spanish: "pruebas contundentes", example: "La fiscalía presentó pruebas contundentes al juez de turno." },
  { id: "c1w_389", category: "Collocation", word: "compelling argument", ipa: "/kəmˈpɛlɪŋ ˈɑrgjəmənt/", spanish: "argumento convincente", example: "Ella dio un argumento convincente para quedarse en el país." },
  { id: "c1w_390", category: "Collocation", word: "crucial role", ipa: "/ˈkruʃəl roʊl/", spanish: "papel crucial", example: "Las abejas juegan un papel crucial en nuestro ecosistema global." },
  { id: "c1w_391", category: "Collocation", word: "integral part", ipa: "/ˈɪntəgrəl pɑrt/", spanish: "parte integral", example: "El ejercicio físico es una parte integral de mi rutina." },
  { id: "c1w_392", category: "Collocation", word: "intrinsic value", ipa: "/ɪnˈtrɪnsɪk ˈvælju/", spanish: "valor intrínseco", example: "El oro tiene un alto valor intrínseco en el mercado mundial." },
  { id: "c1w_393", category: "Collocation", word: "dire consequences", ipa: "/daɪr ˈkɑnsəkwɛnsəz/", spanish: "consecuencias nefastas", example: "Ignorar el problema ecológico traerá consecuencias nefastas." },
  { id: "c1w_394", category: "Collocation", word: "severe shortage", ipa: "/səˈvɪr ˈʃɔrtɪdʒ/", spanish: "grave escasez", example: "El país enfrenta una grave escasez de agua potable limpia." },
  { id: "c1w_395", category: "Collocation", word: "staggering amount", ipa: "/ˈstægərɪŋ əˈmaʊnt/", spanish: "cantidad asombrosa", example: "Gastaron una cantidad asombrosa de dinero en publicidad digital." },
  { id: "c1w_396", category: "Collocation", word: "vast majority", ipa: "/væst məˈʤɔrəti/", spanish: "inmensa mayoría", example: "La inmensa mayoría de la gente apoya la nueva ley vial." },
  { id: "c1w_397", category: "Collocation", word: "heavy burden", ipa: "/ˈhɛvi ˈbɜrdən/", spanish: "pesada carga", example: "La enorme deuda nacional es una pesada carga para el país." },
  { id: "c1w_398", category: "Collocation", word: "daunting task", ipa: "/ˈdɔntɪŋ tæsk/", spanish: "tarea abrumadora", example: "Limpiar toda la casa gigante sola es una tarea abrumadora." },
  { id: "c1w_399", category: "Collocation", word: "heated debate", ipa: "/ˈhitɪd dɪˈbeɪt/", spanish: "acalorado debate", example: "El polémico tema generó un acalorado debate en el parlamento." },
  { id: "c1w_400", category: "Collocation", word: "profound impact", ipa: "/prəˈfaʊnd ˈɪmpækt/", spanish: "impacto profundo", example: "La tecnología moderna tiene un impacto profundo en la sociedad." },
  { id: "c1w_401", category: "Collocation", word: "foregone conclusion", ipa: "/ˈfɔrˌgɔn kənˈkluʒən/", spanish: "conclusión inevitable", example: "El resultado del partido final ya era una conclusión inevitable." },
  { id: "c1w_402", category: "Family", word: "sustainability", ipa: "/səˌsteɪnəˈbɪlɪti/", spanish: "sostenibilidad", example: "Es vital sostener el proyecto con un modelo de sostenibilidad a largo plazo. (sustainability | sustainable | sustainably | sustain)" },
  { id: "c1w_403", category: "Family", word: "analysis", ipa: "/əˈnæləsɪs/", spanish: "análisis", example: "Debemos analizar los datos de forma analítica para el análisis final. (analysis | analytical | analytically | analyze)" },
  { id: "c1w_404", category: "Family", word: "benefit", ipa: "/ˈbɛnəfɪt/", spanish: "beneficio", example: "El nuevo parque va a beneficiar a todos, será muy beneficioso. (benefit | beneficial | beneficially | benefit)" },
  { id: "c1w_405", category: "Family", word: "concept", ipa: "/ˈkɑnsɛpt/", spanish: "concepto", example: "Es difícil conceptualizar un concepto tan abstracto. (concept | conceptual | conceptually | conceptualize)" },
  { id: "c1w_406", category: "Family", word: "definition", ipa: "/ˌdɛfəˈnɪʃən/", spanish: "definición", example: "Debemos definir los términos antes de dar una definición definitiva. (definition | definitive | definitively | define)" },
  { id: "c1w_407", category: "Family", word: "economy", ipa: "/ɪˈkɑnəmi/", spanish: "economía", example: "Para ayudar a la economía, necesitamos economizar los recursos. (economy | economic | economically | economize)" },
  { id: "c1w_408", category: "Family", word: "environment", ipa: "/ɪnˈvaɪrənmənt/", spanish: "medio ambiente", example: "El impacto ambiental está dañando nuestro medio ambiente. (environment | environmental | environmentally)" },
  { id: "c1w_409", category: "Family", word: "establishment", ipa: "/ɪˈstæblɪʃmənt/", spanish: "establecimiento", example: "Acaban de establecer un nuevo establecimiento comercial. (establishment | established | establish)" },
  { id: "c1w_410", category: "Family", word: "estimation", ipa: "/ˌɛstəˈmeɪʃən/", spanish: "estimación", example: "Tuvieron que estimar el costo y enviar una estimación. (estimation | estimated | estimate)" },
  { id: "c1w_411", category: "Family", word: "evidence", ipa: "/ˈɛvədəns/", spanish: "evidencia", example: "Evidentemente, la evidencia muestra que él es culpable. (evidence | evident | evidently)" },
  { id: "c1w_412", category: "Family", word: "finance", ipa: "/ˈfaɪnæns/", spanish: "finanzas", example: "El banco va a financiar nuestro proyecto financiero. (finance | financial | financially | finance)" },
  { id: "c1w_413", category: "Family", word: "formulation", ipa: "/ˌfɔrmjəˈleɪʃən/", spanish: "formulación", example: "Necesitamos formular un plan tras la formulación del problema. (formulation | formulated | formulate)" },
  { id: "c1w_414", category: "Family", word: "identification", ipa: "/aɪˌdɛntəfəˈkeɪʃən/", spanish: "identificación", example: "Por favor, muestre su identificación para que lo podamos identificar. (identification | identifiable | identifiably | identify)" },
  { id: "c1w_415", category: "Family", word: "indication", ipa: "/ˌɪndəˈkeɪʃən/", spanish: "indicación", example: "El médico te va a indicar la indicación correcta a seguir. (indication | indicative | indicatively | indicate)" },
  { id: "c1w_416", category: "Family", word: "interpretation", ipa: "/ɪnˌtɜrprəˈteɪʃən/", spanish: "interpretación", example: "Es difícil interpretar esa obra sin una buena interpretación. (interpretation | interpretive | interpretively | interpret)" },
  { id: "c1w_417", category: "Family", word: "investment", ipa: "/ɪnˈvɛstmənt/", spanish: "inversión", example: "Voy a invertir mi dinero en una inversión segura. (investment | invested | invest)" },
  { id: "c1w_418", category: "Family", word: "legislation", ipa: "/ˌlɛʤɪˈsleɪʃən/", spanish: "legislación", example: "El parlamento debe legislar una nueva legislación laboral. (legislation | legislative | legislatively | legislate)" },
  { id: "c1w_419", category: "Family", word: "occurrence", ipa: "/əˈkɜrəns/", spanish: "suceso / ocurrencia", example: "Es raro que un suceso así vuelva a ocurrir. (occurrence | occurring | occur)" },
  { id: "c1w_420", category: "Family", word: "participation", ipa: "/pɑrˌtɪsəˈpeɪʃən/", spanish: "participación", example: "Tu participación es clave, anímate a participar. (participation | participatory | participate)" },
  { id: "c1w_421", category: "Family", word: "requirement", ipa: "/rɪˈkwaɪərmənt/", spanish: "requisito", example: "Este trabajo va a requerir un requisito muy estricto. (requirement | required | require)" },
  { id: "c1w_422", category: "Family", word: "response", ipa: "/rɪˈspɑns/", spanish: "respuesta", example: "Tienes que responder rápido, espero tu respuesta. (response | responsive | responsively | respond)" },
  { id: "c1w_423", category: "Family", word: "significance", ipa: "/sɪgˈnɪfɪkəns/", spanish: "importancia", example: "Este descubrimiento puede significar un avance significativo. (significance | significant | significantly | signify)" },
  { id: "c1w_424", category: "Family", word: "theory", ipa: "/ˈθɪri/", spanish: "teoría", example: "En teoría, la investigación teórica funciona bien. (theory | theoretical | theoretically | theorize)" },
  { id: "c1w_425", category: "Family", word: "assumption", ipa: "/əˈsʌmpʃən/", spanish: "suposición", example: "No es bueno asumir cosas sin pruebas, es solo una suposición. (assumption | assumptive | assume)" },
  { id: "c1w_426", category: "Family", word: "conclusion", ipa: "/kənˈkluʒən/", spanish: "conclusión", example: "Al concluir el debate, llegamos a una conclusión concluyente. (conclusion | conclusive | conclusively | conclude)" },
  { id: "c1w_427", category: "Family", word: "constitution", ipa: "/ˌkɑnstəˈtuʃən/", spanish: "constitución", example: "Eso va a constituir una violación a la constitución. (constitution | constitutional | constitutionally | constitute)" },
  { id: "c1w_428", category: "Family", word: "distribution", ipa: "/ˌdɪstrəˈbjuʃən/", spanish: "distribución", example: "Tienen que distribuir los paquetes desde el centro de distribución. (distribution | distributive | distributively | distribute)" },
  { id: "c1w_429", category: "Family", word: "evaluation", ipa: "/ɪˌvæljuˈeɪʃən/", spanish: "evaluación", example: "El profesor va a evaluar tu prueba en la próxima evaluación. (evaluation | evaluative | evaluatively | evaluate)" },
  { id: "c1w_430", category: "Family", word: "administration", ipa: "/ædˌmɪnɪˈstreɪʃən/", spanish: "administración", example: "Administrar esta empresa requiere una gran administración. (administration | administrative | administratively | administrate)" },
  { id: "c1w_431", category: "Family", word: "alternative", ipa: "/ɔlˈtɜrnətɪv/", spanish: "alternativa", example: "Como alternativa, podemos alternar los días de descanso. (alternative | alternatively | alternate)" },
  { id: "c1w_432", category: "Family", word: "contribution", ipa: "/ˌkɑntrəˈbjuʃən/", spanish: "contribución", example: "Tu contribución económica va a contribuir mucho a la causa. (contribution | contributory | contribute)" },
  { id: "c1w_433", category: "Family", word: "emphasis", ipa: "/ˈɛmfəsɪs/", spanish: "énfasis", example: "Quiero enfatizar este punto con mucho énfasis. (emphasis | emphatic | emphatically | emphasize)" },
  { id: "c1w_434", category: "Family", word: "illustration", ipa: "/ˌɪləˈstreɪʃən/", spanish: "ilustración", example: "Usó una ilustración visual para ilustrar su punto. (illustration | illustrative | illustratively | illustrate)" },
  { id: "c1w_435", category: "Family", word: "justification", ipa: "/ˌʤʌstəfəˈkeɪʃən/", spanish: "justificación", example: "Debes justificar tus faltas con una buena justificación. (justification | justifiable | justifiably | justify)" },
  { id: "c1w_436", category: "Family", word: "proportion", ipa: "/prəˈpɔrʃən/", spanish: "proporción", example: "El salario debe ser proporcional a la proporción de trabajo. (proportion | proportional | proportionally | proportion)" },
  { id: "c1w_437", category: "Family", word: "reliance", ipa: "/rɪˈlaɪəns/", spanish: "dependencia / confianza", example: "Puedes confiar en él, es un trabajador muy confiable. (reliance | reliable | reliably | rely)" },
  { id: "c1w_438", category: "Family", word: "strategy", ipa: "/ˈstrætəʤi/", spanish: "estrategia", example: "Debos crear una estrategia para este plan estratégico. (strategy | strategic | strategically | strategize)" },
  { id: "c1w_439", category: "Family", word: "variation", ipa: "/ˌvɛriˈeɪʃən/", spanish: "variación", example: "El clima puede variar mucho, hay mucha variación. (variation | variable | variably | vary)" },
  { id: "c1w_440", category: "Family", word: "acquisition", ipa: "/ˌækwəˈzɪʃən/", spanish: "adquisición", example: "Queremos adquirir esa empresa, será una gran adquisición. (acquisition | acquisitive | acquisitively | acquire)" },
  { id: "c1w_441", category: "Family", word: "deduction", ipa: "/dɪˈdʌkʃən/", spanish: "deducción", example: "Por lógica deductiva, pude deducir la respuesta. (deduction | deductive | deductively | deduct)" },
  { id: "c1w_442", category: "Family", word: "demonstration", ipa: "/ˌdɛmənˈstreɪʃən/", spanish: "demostración", example: "Haremos una demostración práctica para demostrar el producto. (demonstration | demonstrative | demonstratively | demonstrate)" },
  { id: "c1w_443", category: "Family", word: "dominance", ipa: "/ˈdɑmənəns/", spanish: "dominio", example: "Ese león dominante quiere dominar la manada. (dominance | dominant | dominantly | dominate)" },
  { id: "c1w_444", category: "Family", word: "implication", ipa: "/ˌɪmpləˈkeɪʃən/", spanish: "implicación", example: "Eso podría implicar una gran implicación legal. (implication | implicit | implicitly | imply)" },
  { id: "c1w_445", category: "Family", word: "prediction", ipa: "/prɪˈdɪkʃən/", spanish: "predicción", example: "Su predicción fue exacta, era muy predecible. (prediction | predictable | predictably | predict)" },
  { id: "c1w_446", category: "Family", word: "validation", ipa: "/ˌvæləˈdeɪʃən/", spanish: "validación", example: "Necesitamos validar el ticket en la máquina de validación. (validation | valid | validly | validate)" },
  { id: "c1w_447", category: "Family", word: "adaptation", ipa: "/ˌædæpˈteɪʃən/", spanish: "adaptación", example: "Es una especie muy adaptable, logró adaptar su dieta. (adaptation | adaptable | adaptably | adapt)" },
  { id: "c1w_448", category: "Family", word: "clarification", ipa: "/ˌklɛrəfəˈkeɪʃən/", spanish: "aclaración", example: "Déjame aclarar este punto claramente con una aclaración. (clarification | clear | clearly | clarify)" },
  { id: "c1w_449", category: "Family", word: "creation", ipa: "/kriˈeɪʃən/", spanish: "creación", example: "Hay que crear algo nuevo, usa tu mente creativa. (creation | creative | creatively | create)" },
  { id: "c1w_450", category: "Family", word: "diversity", ipa: "/dɪˈvɜrsəti/", spanish: "diversidad", example: "Para tener diversidad, debes diversificar tus inversiones. (diversity | diverse | diversely | diversify)" },
  { id: "c1w_451", category: "Family", word: "expansion", ipa: "/ɪkˈspænʃən/", spanish: "expansión", example: "Queremos expandir el negocio mediante una gran expansión. (expansion | expansive | expansively | expand)" },
  { id: "c1w_452", category: "Family", word: "innovation", ipa: "/ˌɪnəˈveɪʃən/", spanish: "innovación", example: "Es importante innovar con tecnología innovadora. (innovation | innovative | innovatively | innovate)" },
  { id: "c1w_453", category: "Family", word: "integration", ipa: "/ˌɪntəˈgreɪʃən/", spanish: "integración", example: "Vamos a integrar el nuevo sistema para una mejor integración. (integration | integrative | integratively | integrate)" },
  { id: "c1w_454", category: "Family", word: "motivation", ipa: "/ˌmoʊtəˈveɪʃən/", spanish: "motivación", example: "El orador logró motivar al equipo con su discurso motivacional. (motivation | motivational | motivationally | motivate)" },
  { id: "c1w_455", category: "Family", word: "observation", ipa: "/ˌɑbzərˈveɪʃən/", spanish: "observación", example: "El detective debe observar todo con gran capacidad de observación. (observation | observant | observantly | observe)" },
  { id: "c1w_456", category: "Family", word: "prevention", ipa: "/prɪˈvɛnʃən/", spanish: "prevención", example: "Tomaremos medidas de prevención para prevenir accidentes. (prevention | preventive | preventively | prevent)" },
  { id: "c1w_457", category: "Family", word: "production", ipa: "/prəˈdʌkʃən/", spanish: "producción", example: "Para producir más, necesitamos un equipo productivo. (production | productive | productively | produce)" },
  { id: "c1w_458", category: "Family", word: "regulation", ipa: "/ˌrɛgjəˈleɪʃən/", spanish: "regulación", example: "El gobierno debe regular el mercado con una nueva regulación. (regulation | regulatory | regulate)" },
  { id: "c1w_459", category: "Family", word: "transformation", ipa: "/ˌtrænsfərˈmeɪʃən/", spanish: "transformación", example: "Esta idea puede transformar el mundo; es muy transformadora. (transformation | transformative | transformatively | transform)" },
  { id: "c1w_460", category: "Family", word: "authorization", ipa: "/ˌɔθərəˈzeɪʃən/", spanish: "autorización", example: "Solo el personal autorizado puede autorizar esa autorización. (authorization | authorized | authorize)" },
  { id: "c1w_461", category: "Family", word: "capability", ipa: "/ˌkeɪpəˈbɪləti/", spanish: "capacidad", example: "Él es muy capaz y tiene la capacidad para el trabajo. (capability | capable | capably)" },
  { id: "c1w_462", category: "Family", word: "combination", ipa: "/ˌkɑmbəˈneɪʃən/", spanish: "combinación", example: "Debes combinar estos dos colores, es una gran combinación. (combination | combinative | combine)" },
  { id: "c1w_463", category: "Family", word: "complexity", ipa: "/kəmˈplɛksəti/", spanish: "complejidad", example: "No trates de complicar este asunto ya tan complejo. (complexity | complex | complexly | complicate)" },
  { id: "c1w_464", category: "Family", word: "confirmation", ipa: "/ˌkɑnfərˈmeɪʃən/", spanish: "confirmación", example: "Te llamaré para confirmar y enviar la confirmación. (confirmation | confirmatory | confirm)" },
  { id: "c1w_465", category: "Family", word: "consequence", ipa: "/ˈkɑnsəkwəns/", spanish: "consecuencia", example: "Hubo un error grave, y por consiguiente (consecuentemente), una gran consecuencia. (consequence | consequent | consequently)" },
  { id: "c1w_466", category: "Family", word: "continuity", ipa: "/ˌkɑntəˈnuəti/", spanish: "continuidad", example: "Debemos continuar trabajando para mantener la continuidad. (continuity | continuous | continuously | continue)" },
  { id: "c1w_467", category: "Family", word: "destruction", ipa: "/dɪˈstrʌkʃən/", spanish: "destrucción", example: "El huracán destructivo logró destruir casi toda la ciudad. (destruction | destructive | destructively | destroy)" },
  { id: "c1w_468", category: "Family", word: "differentiation", ipa: "/ˌdɪfəˌrɛnʃiˈeɪʃən/", spanish: "diferenciación", example: "Es importante diferenciar un producto diferente del resto. (differentiation | different | differently | differentiate)" },
  { id: "c1w_469", category: "Family", word: "elimination", ipa: "/ɪˌlɪməˈneɪʃən/", spanish: "eliminación", example: "El objetivo del juego es la eliminación al eliminar rivales. (elimination | eliminable | eliminate)" },
  { id: "c1w_470", category: "Family", word: "expectation", ipa: "/ˌɛkspɛkˈteɪʃən/", spanish: "expectativa", example: "Es normal esperar resultados, la expectativa es alta. (expectation | expectant | expectantly | expect)" },
  { id: "c1w_471", category: "Family", word: "generation", ipa: "/ˌʤɛnəˈreɪʃən/", spanish: "generación", example: "La energía solar va a generar electricidad para esta generación. (generation | generative | generatively | generate)" },
  { id: "c1w_472", category: "Family", word: "incorporation", ipa: "/ɪnˌkɔrpəˈreɪʃən/", spanish: "incorporación", example: "Van a incorporar nuevas normas en la vida corporativa. (incorporation | corporate | incorporate)" },
  { id: "c1w_473", category: "Family", word: "intensity", ipa: "/ɪnˈtɛnsəti/", spanish: "intensidad", example: "El calor se va a intensificar con gran intensidad. (intensity | intense | intensely | intensify)" },
  { id: "c1w_474", category: "Family", word: "modification", ipa: "/ˌmɑdəfəˈkeɪʃən/", spanish: "modificación", example: "Tuvimos que modificar el texto con una ligera modificación. (modification | modifiable | modify)" },
  { id: "c1w_475", category: "Family", word: "perception", ipa: "/pərˈsɛpʃən/", spanish: "percepción", example: "Él es muy perceptivo y logró percibir el engaño. (perception | perceptive | perceptively | perceive)" },
  { id: "c1w_476", category: "Family", word: "preference", ipa: "/ˈprɛfərəns/", spanish: "preferencia", example: "Es preferible que indiques tu preferencia al elegir. (preference | preferable | preferably | prefer)" },
  { id: "c1w_477", category: "Family", word: "promotion", ipa: "/prəˈmoʊʃən/", spanish: "promoción", example: "Esa campaña promocional va a promover las ventas. (promotion | promotional | promotionally | promote)" },
  { id: "c1w_478", category: "Family", word: "recovery", ipa: "/rɪˈkʌvəri/", spanish: "recuperación", example: "Espero que se logre recuperar pronto y tenga una rápida recuperación. (recovery | recoverable | recoverably | recover)" },
  { id: "c1w_479", category: "Family", word: "reduction", ipa: "/rɪˈdʌkʃən/", spanish: "reducción", example: "Es urgente reducir los gastos mediante una reducción presupuestal. (reduction | reductive | reductively | reduce)" },
  { id: "c1w_480", category: "Family", word: "rejection", ipa: "/rɪˈʤɛkʃən/", spanish: "rechazo", example: "Es triste rechazar la oferta, pero el rechazo era inevitable. (rejection | rejectable | reject)" },
  { id: "c1w_481", category: "Family", word: "resolution", ipa: "/ˌrɛzəˈluʃən/", spanish: "resolución / determinación", example: "Debemos resolver esto pacíficamente and llegar a una resolución. (resolution | resolute | resolutely | resolve)" },
  { id: "c1w_482", category: "Family", word: "restriction", ipa: "/riˈstrɪkʃən/", spanish: "restricción", example: "Esa regla tan restrictiva nos va a restringir mucho el paso. (restriction | restrictive | restrictively | restrict)" },
  { id: "c1w_483", category: "Family", word: "selection", ipa: "/səˈlɛkʃən/", spanish: "selección", example: "Al seleccionar el material, sé muy selectivo. (selection | selective | selectively | select)" },
  { id: "c1w_484", category: "Family", word: "separation", ipa: "/ˌsɛpəˈreɪʃən/", spanish: "separación", example: "Tienes que separar los papeles and guardarlos separadamente. (separation | separate | separately | separate)" },
  { id: "c1w_485", category: "Family", word: "substitution", ipa: "/ˌsʌbstəˈtuʃən/", spanish: "sustitución", example: "Voy a sustituir el azúcar por un sustituto artificial. (substitution | substitute)" },
  { id: "c1w_486", category: "Family", word: "transition", ipa: "/trænˈzɪʃən/", spanish: "transición", example: "El país debe transicionar hacia la democracia en este periodo de transición. (transition | transitional | transitionally | transition)" },
  { id: "c1w_487", category: "Family", word: "accuracy", ipa: "/ˈækjərəsi/", spanish: "exactitud (precisión)", example: "Mide el área exactamente para garantizar su exactitud. (accuracy | accurate | accurately)" },
  { id: "c1w_488", category: "Family", word: "adequacy", ipa: "/ˈædəkwəsi/", spanish: "idoneidad (suficiencia)", example: "Revisa si el presupuesto es adecuado y responde adecuadamente. (adequacy | adequate | adequately)" },
  { id: "c1w_489", category: "Family", word: "certainty", ipa: "/ˈsɜrtənti/", spanish: "certeza", example: "Debemos cerciorarnos con total certeza de los hechos. (certainty | certain | certainly | ascertain)" },
  { id: "c1w_490", category: "Family", word: "efficiency", ipa: "/ɪˈfɪʃənsi/", spanish: "eficiencia", example: "Un motor eficiente trabaja más eficientemente. (efficiency | efficient | efficiently)" },
  { id: "c1w_491", category: "Family", word: "flexibility", ipa: "/ˌflɛksəˈbɪləti/", spanish: "flexibilidad", example: "El trabajo flexible requiere mucha flexibilidad de horarios. (flexibility | flexible | flexiblemente)" },
  { id: "c1w_492", category: "Family", word: "frequency", ipa: "/ˈfrikwənsi/", spanish: "frecuencia", example: "Suele frecuentar este lugar con mucha frecuencia. (frequency | frequent | frequently | frequent)" },
  { id: "c1w_493", category: "Family", word: "likelihood", ipa: "/ˈlaɪkliˌhʊd/", spanish: "probabilidad", example: "Es muy probable que llueva; la probabilidad es alta. (likelihood | likely)" },
  { id: "c1w_494", category: "Family", word: "necessity", ipa: "/nəˈsɛsəti/", spanish: "necesidad", example: "Esta emergencia va a requerir la necesidad de fondos extra. (necessity | necessary | necessarily | necessitate)" },
  { id: "c1w_495", category: "Family", word: "probability", ipa: "/ˌprɑbəˈbɪləti/", spanish: "probabilidad", example: "Probablemente él ganará, hay gran probabilidad. (probability | probable | probably)" },
  { id: "c1w_496", category: "Family", word: "reality", ipa: "/riˈæləti/", spanish: "realidad", example: "Acabo de darme cuenta de que el peligro era realmente real. (reality | real | really | realize)" },
  { id: "c1w_497", category: "Family", word: "reliability", ipa: "/rɪˌlaɪəˈbɪləti/", spanish: "fiabilidad", example: "Necesitamos un sistema fiable por su alta fiabilidad. (reliability | reliable | reliably | rely)" },
  { id: "c1w_498", category: "Family", word: "safety", ipa: "/ˈseɪfti/", spanish: "seguridad", example: "Por tu seguridad, conduce a salvo y seguro. (safety | safe | safely | save)" },
  { id: "c1w_499", category: "Family", word: "similarity", ipa: "/ˌsɪməˈlɛrəti/", spanish: "similitud", example: "Ambos casos son muy similares y tienen gran similitud. (similarity | similar | similarly)" },
  { id: "c1w_500", category: "Family", word: "validity", ipa: "/vəˈlɪdəti/", spanish: "validez", example: "Debemos validar el contrato para darle validez legal. (validity | valid | validly | validate)" },
  { id: "c1w_501", category: "Family", word: "visibility", ipa: "/ˌvɪzəˈbɪləti/", spanish: "visibilidad", example: "La niebla afecta la visibilidad, casi nada es visible. (visibility | visible | visibly)" },
  { id: "c1w_502", category: "Family", word: "accessibility", ipa: "/ækˌsɛsəˈbɪləti/", spanish: "accesibilidad", example: "Para acceder al edificio, necesitamos rampas de accesibilidad. (accessibility | accessible | accessibly | access)" }
];
