import { Cognate } from '../types';

export const COGNATES_DATA: Cognate[] = [
  // --- COGNATES (1-100) ---
  { english: "Chocolate", spanish: "Chocolate", pronunciation: "ˈtʃɒklət", intonation: "Falling", type: 'COGNATE' },
  { english: "Actor", spanish: "Actor", pronunciation: "ˈæktər", intonation: "Rising-Falling", type: 'COGNATE' },
  { english: "Important", spanish: "Importante", pronunciation: "ɪmˈpɔːrtnt", intonation: "Falling", type: 'COGNATE' },
  { english: "Elegant", spanish: "Elegante", pronunciation: "ˈelɪɡənt", intonation: "Falling", type: 'COGNATE' },
  { english: "Final", spanish: "Final", pronunciation: "ˈfaɪnl", intonation: "Falling", type: 'COGNATE' },
  { english: "Action", spanish: "Acción", pronunciation: "ˈækʃn", intonation: "Falling", type: 'COGNATE' },
  { english: "Admirable", spanish: "Admirable", pronunciation: "ˈædmərəbl", intonation: "Falling", type: 'COGNATE' },
  { english: "Adopt", spanish: "Adoptar", pronunciation: "əˈdɒpt", intonation: "Falling", type: 'COGNATE' },
  { english: "Animal", spanish: "Animal", pronunciation: "ˈænɪml", intonation: "Falling", type: 'COGNATE' },
  { english: "Area", spanish: "Área", pronunciation: "ˈeəriə", intonation: "Falling", type: 'COGNATE' },
  { english: "Art", spanish: "Arte", pronunciation: "ɑːrt", intonation: "Falling", type: 'COGNATE' },
  { english: "Base", spanish: "Base", pronunciation: "beɪs", intonation: "Falling", type: 'COGNATE' },
  { english: "Capital", spanish: "Capital", pronunciation: "ˈkæpɪtl", intonation: "Falling", type: 'COGNATE' },
  { english: "Central", spanish: "Central", pronunciation: "ˈsentrəl", intonation: "Falling", type: 'COGNATE' },
  { english: "Color", spanish: "Color", pronunciation: "ˈkʌlər", intonation: "Falling", type: 'COGNATE' },
  { english: "Conclusion", spanish: "Conclusión", pronunciation: "kənˈkluːʒn", intonation: "Falling", type: 'COGNATE' },
  { english: "Control", spanish: "Control", pronunciation: "kənˈtrəʊl", intonation: "Falling", type: 'COGNATE' },
  { english: "Decision", spanish: "Decisión", pronunciation: "dɪˈsɪʒn", intonation: "Falling", type: 'COGNATE' },
  { english: "Direct", spanish: "Directo", pronunciation: "dəˈrekt", intonation: "Falling", type: 'COGNATE' },
  { english: "Distance", spanish: "Distancia", pronunciation: "ˈdɪstəns", intonation: "Falling", type: 'COGNATE' },
  { english: "Doctor", spanish: "Doctor", pronunciation: "ˈdɒktər", intonation: "Falling", type: 'COGNATE' },
  { english: "Double", spanish: "Doble", pronunciation: "ˈdʌbl", intonation: "Falling", type: 'COGNATE' },
  { english: "Error", spanish: "Error", pronunciation: "ˈerər", intonation: "Falling", type: 'COGNATE' },
  { english: "Example", spanish: "Ejemplo", pronunciation: "ɪɡˈzɑːmpl", intonation: "Falling", type: 'COGNATE' },
  { english: "Family", spanish: "Familia", pronunciation: "ˈfæməli", intonation: "Falling", type: 'COGNATE' },
  { english: "Future", spanish: "Futuro", pronunciation: "ˈfjuːtʃər", intonation: "Falling", type: 'COGNATE' },
  { english: "Gas", spanish: "Gas", pronunciation: "ɡæs", intonation: "Falling", type: 'COGNATE' },
  { english: "General", spanish: "General", pronunciation: "ˈdʒenrəl", intonation: "Falling", type: 'COGNATE' },
  { english: "History", spanish: "Historia", pronunciation: "ˈhɪstri", intonation: "Falling", type: 'COGNATE' },
  { english: "Hospital", spanish: "Hospital", pronunciation: "ˈhɒspɪtl", intonation: "Falling", type: 'COGNATE' },
  { english: "Idea", spanish: "Idea", pronunciation: "aɪˈdɪə", intonation: "Rising", type: 'COGNATE' },
  { english: "Imagine", spanish: "Imaginar", pronunciation: "ɪˈmædʒɪn", intonation: "Falling", type: 'COGNATE' },
  { english: "Local", spanish: "Local", pronunciation: "ˈləʊkl", intonation: "Falling", type: 'COGNATE' },
  { english: "Map", spanish: "Mapa", pronunciation: "mæp", intonation: "Falling", type: 'COGNATE' },
  { english: "Material", spanish: "Material", pronunciation: "məˈtɪəriəl", intonation: "Falling", type: 'COGNATE' },
  { english: "Metal", spanish: "Metal", pronunciation: "ˈmetl", intonation: "Falling", type: 'COGNATE' },
  { english: "Music", spanish: "Música", pronunciation: "ˈmjuːzɪk", intonation: "Falling", type: 'COGNATE' },
  { english: "Natural", spanish: "Natural", pronunciation: "ˈnætʃrəl", intonation: "Falling", type: 'COGNATE' },
  { english: "Night", spanish: "Noche", pronunciation: "naɪt", intonation: "Falling", type: 'COGNATE' },
  { english: "No", spanish: "No", pronunciation: "nəʊ", intonation: "Falling", type: 'COGNATE' },
  { english: "Operation", spanish: "Operación", pronunciation: "ˌɒpəˈreɪʃn", intonation: "Falling", type: 'COGNATE' },
  { english: "Opinion", spanish: "Opinión", pronunciation: "əˈpɪnjən", intonation: "Falling", type: 'COGNATE' },
  { english: "Option", spanish: "Opción", pronunciation: "ˈɒpʃn", intonation: "Falling", type: 'COGNATE' },
  { english: "Order", spanish: "Orden", pronunciation: "ˈɔːrdər", intonation: "Falling", type: 'COGNATE' },
  { english: "Paper", spanish: "Papel", pronunciation: "ˈpeɪpər", intonation: "Falling", type: 'COGNATE' },
  { english: "Parallel", spanish: "Paralelo", pronunciation: "ˈpærəlel", intonation: "Falling", type: 'COGNATE' },
  { english: "Part", spanish: "Parte", pronunciation: "pɑːrt", intonation: "Falling", type: 'COGNATE' },
  { english: "Patient", spanish: "Paciente", pronunciation: "ˈpeɪʃnt", intonation: "Falling", type: 'COGNATE' },
  { english: "Perfect", spanish: "Perfecto", pronunciation: "ˈpɜːrfɪkt", intonation: "Falling", type: 'COGNATE' },
  { english: "Personal", spanish: "Personal", pronunciation: "ˈpɜːrsənl", intonation: "Falling", type: 'COGNATE' },
  { english: "Plans", spanish: "Planes", pronunciation: "plænz", intonation: "Falling", type: 'COGNATE' },
  { english: "Police", spanish: "Policía", pronunciation: "pəˈliːs", intonation: "Falling", type: 'COGNATE' },
  { english: "Possible", spanish: "Posible", pronunciation: "ˈpɒsəbl", intonation: "Falling", type: 'COGNATE' },
  { english: "Preparation", spanish: "Preparación", pronunciation: "ˌprepəˈreɪʃn", intonation: "Falling", type: 'COGNATE' },
  { english: "Present", spanish: "Presente", pronunciation: "ˈpreznt", intonation: "Falling", type: 'COGNATE' },
  { english: "Problem", spanish: "Problema", pronunciation: "ˈprɒbləm", intonation: "Falling", type: 'COGNATE' },
  { english: "Public", spanish: "Público", pronunciation: "ˈpʌblɪk", intonation: "Falling", type: 'COGNATE' },
  { english: "Radio", spanish: "Radio", pronunciation: "ˈreɪdiəʊ", intonation: "Falling", type: 'COGNATE' },
  { english: "Recent", spanish: "Reciente", pronunciation: "ˈriːsnt", intonation: "Falling", type: 'COGNATE' },
  { english: "Region", spanish: "Región", pronunciation: "ˈriːdʒən", intonation: "Falling", type: 'COGNATE' },
  { english: "Regular", spanish: "Regular", pronunciation: "ˈreɡjələr", intonation: "Falling", type: 'COGNATE' },
  { english: "Religion", spanish: "Religión", pronunciation: "rɪˈlɪdʒən", intonation: "Falling", type: 'COGNATE' },
  { english: "Reservation", spanish: "Reservación", pronunciation: "ˌrezərˈveɪʃn", intonation: "Falling", type: 'COGNATE' },
  { english: "Responsible", spanish: "Responsable", pronunciation: "rɪˈspɒnsəbl", intonation: "Falling", type: 'COGNATE' },
  { english: "Result", spanish: "Resultado", pronunciation: "rɪˈzʌlt", intonation: "Falling", type: 'COGNATE' },
  { english: "Rules", spanish: "Reglas", pronunciation: "ruːlz", intonation: "Falling", type: 'COGNATE' },
  { english: "Secret", spanish: "Secreto", pronunciation: "ˈsiːkrət", intonation: "Falling", type: 'COGNATE' },
  { english: "Section", spanish: "Sección", pronunciation: "ˈsekʃn", intonation: "Falling", type: 'COGNATE' },
  { english: "Serious", spanish: "Serio", pronunciation: "ˈsɪəriəs", intonation: "Falling", type: 'COGNATE' },
  { english: "Signal", spanish: "Señal", pronunciation: "ˈsɪɡnəl", intonation: "Falling", type: 'COGNATE' },
  { english: "Simple", spanish: "Simple", pronunciation: "ˈsɪmpl", intonation: "Falling", type: 'COGNATE' },
  { english: "Situation", spanish: "Situación", pronunciation: "ˌsɪtʃuˈeɪʃn", intonation: "Falling", type: 'COGNATE' },
  { english: "Special", spanish: "Especial", pronunciation: "ˈspeʃl", intonation: "Falling", type: 'COGNATE' },
  { english: "Structure", spanish: "Estructura", pronunciation: "ˈstrʌktʃər", intonation: "Falling", type: 'COGNATE' },
  { english: "Total", spanish: "Total", pronunciation: "ˈtəʊtl", intonation: "Falling", type: 'COGNATE' },
  { english: "Traffic", spanish: "Tráfico", pronunciation: "ˈtræfɪk", intonation: "Falling", type: 'COGNATE' },
  { english: "Union", spanish: "Unión", pronunciation: "ˈjuːniən", intonation: "Falling", type: 'COGNATE' },
  { english: "Visit", spanish: "Visitar", pronunciation: "ˈvɪzɪt", intonation: "Falling", type: 'COGNATE' },
  { english: "Abandon", spanish: "Abandonar", pronunciation: "əˈbændən", intonation: "Falling", type: 'COGNATE' },
  { english: "Academic", spanish: "Académico", pronunciation: "ˌækəˈdemɪk", intonation: "Falling", type: 'COGNATE' },
  { english: "Accept", spanish: "Aceptar", pronunciation: "əkˈsept", intonation: "Falling", type: 'COGNATE' },
  { english: "Accident", spanish: "Accidente", pronunciation: "ˈæksɪdənt", intonation: "Falling", type: 'COGNATE' },
  { english: "Accuse", spanish: "Acusar", pronunciation: "əˈkjuːz", intonation: "Falling", type: 'COGNATE' },
  { english: "Active", spanish: "Activo", pronunciation: "ˈæktɪv", intonation: "Falling", type: 'COGNATE' },
  { english: "Adapt", spanish: "Adaptar", pronunciation: "əˈdæpt", intonation: "Falling", type: 'COGNATE' },
  { english: "Admit", spanish: "Admitir", pronunciation: "ədˈmɪt", intonation: "Falling", type: 'COGNATE' },
  { english: "Adventure", spanish: "Aventura", pronunciation: "ədˈventʃər", intonation: "Falling", type: 'COGNATE' },
  { english: "Agent", spanish: "Agente", pronunciation: "ˈeɪdʒənt", intonation: "Falling", type: 'COGNATE' },
  { english: "Alarm", spanish: "Alarma", pronunciation: "əˈlɑːrm", intonation: "Falling", type: 'COGNATE' },
  { english: "Alcohol", spanish: "Alcohol", pronunciation: "ˈælkəhɒl", intonation: "Falling", type: 'COGNATE' },
  { english: "Alphabet", spanish: "Alfabeto", pronunciation: "ˈælfəbet", intonation: "Falling", type: 'COGNATE' },
  { english: "Alternative", spanish: "Alternativa", pronunciation: "ɔːlˈtɜːrnətɪv", intonation: "Falling", type: 'COGNATE' },
  { english: "Ambition", spanish: "Ambición", pronunciation: "æmˈbɪʃn", intonation: "Falling", type: 'COGNATE' },
  { english: "Ambulance", spanish: "Ambulancia", pronunciation: "ˈæmbjələns", intonation: "Falling", type: 'COGNATE' },
  { english: "Analysis", spanish: "Análisis", pronunciation: "əˈnæləsɪs", intonation: "Falling", type: 'COGNATE' },
  { english: "Angel", spanish: "Ángel", pronunciation: "ˈeɪndʒl", intonation: "Falling", type: 'COGNATE' },
  { english: "Angle", spanish: "Ángulo", pronunciation: "ˈæŋɡl", intonation: "Falling", type: 'COGNATE' },
  { english: "Animal", spanish: "Animal", pronunciation: "ˈænɪml", intonation: "Falling", type: 'COGNATE' },
  { english: "Animation", spanish: "Animación", pronunciation: "ˌænɪˈmeɪʃn", intonation: "Falling", type: 'COGNATE' },
  { english: "Annual", spanish: "Anual", pronunciation: "ˈænjuəl", intonation: "Falling", type: 'COGNATE' },
  { english: "Appearance", spanish: "Apariencia", pronunciation: "əˈpɪərəns", intonation: "Falling", type: 'COGNATE' },
  { english: "Appetite", spanish: "Apetito", pronunciation: "ˈæpɪtaɪt", intonation: "Falling", type: 'COGNATE' },
  { english: "Association", spanish: "Asociación", pronunciation: "əˌsəʊsiˈeɪʃn", intonation: "Falling", type: 'COGNATE' },
  { english: "Attention", spanish: "Atención", pronunciation: "əˈtenʃn", intonation: "Falling", type: 'COGNATE' },
  { english: "Attitude", spanish: "Actitud", pronunciation: "ˈætɪtjuːd", intonation: "Falling", type: 'COGNATE' },
  { english: "Authority", spanish: "Autoridad", pronunciation: "ɔːˈθɒrəti", intonation: "Falling", type: 'COGNATE' },
  { english: "Balance", spanish: "Balance", pronunciation: "ˈbæləns", intonation: "Falling", type: 'COGNATE' },
  { english: "Billionaire", spanish: "Billonario", pronunciation: "ˌbɪljəˈneər", intonation: "Falling", type: 'COGNATE' },
  { english: "Cabinet", spanish: "Gabinete", pronunciation: "ˈkæbɪnət", intonation: "Falling", type: 'COGNATE' },
  { english: "Camp", spanish: "Campo", pronunciation: "kæmp", intonation: "Falling", type: 'COGNATE' },
  { english: "Cancel", spanish: "Cancelar", pronunciation: "ˈkænsl", intonation: "Falling", type: 'COGNATE' },
  { english: "Capacity", spanish: "Capacidad", pronunciation: "kəˈpæsəti", intonation: "Falling", type: 'COGNATE' },
  { english: "Caution", spanish: "Cautela", pronunciation: "ˈkɔːʃn", intonation: "Falling", type: 'COGNATE' },
  { english: "Celebrity", spanish: "Celebridad", pronunciation: "səˈlebrəti", intonation: "Falling", type: 'COGNATE' },
  { english: "Circular", spanish: "Circular", pronunciation: "ˈsɜːrkjələr", intonation: "Falling", type: 'COGNATE' },
  { english: "Collection", spanish: "Colección", pronunciation: "kəˈlekʃn", intonation: "Falling", type: 'COGNATE' },
  { english: "Combined", spanish: "Combinado", pronunciation: "kəmˈbaɪnd", intonation: "Falling", type: 'COGNATE' },
  { english: "Commercial", spanish: "Comercial", pronunciation: "kəˈmɜːrʃl", intonation: "Falling", type: 'COGNATE' },
  { english: "Committee", spanish: "Comité", pronunciation: "kəˈmɪti", intonation: "Falling", type: 'COGNATE' },
  { english: "Compromise", spanish: "Compromiso", pronunciation: "ˈkɒmprəmaɪz", intonation: "Falling", type: 'COGNATE' },
  { english: "Concentrate", spanish: "Concentrar", pronunciation: "ˈkɒnsntreɪt", intonation: "Falling", type: 'COGNATE' },
  { english: "Condition", spanish: "Condición", pronunciation: "kənˈdɪʃn", intonation: "Falling", type: 'COGNATE' },
  { english: "Conflict", spanish: "Conflicto", pronunciation: "ˈkɒnflɪkt", intonation: "Falling", type: 'COGNATE' },
  { english: "Constant", spanish: "Constante", pronunciation: "ˈkɒnstənt", intonation: "Falling", type: 'COGNATE' },
  { english: "Construct", spanish: "Construir", pronunciation: "kənˈstrʌkt", intonation: "Falling", type: 'COGNATE' },
  { english: "Contract", spanish: "Contrato", pronunciation: "ˈkɒntrækt", intonation: "Falling", type: 'COGNATE' },
  { english: "Contrast", spanish: "Contraste", pronunciation: "ˈkɒntrɑːst", intonation: "Falling", type: 'COGNATE' },
  { english: "Copy", spanish: "Copia", pronunciation: "ˈkɒpi", intonation: "Falling", type: 'COGNATE' },
  { english: "Counter", spanish: "Contador", pronunciation: "ˈkaʊntər", intonation: "Falling", type: 'COGNATE' },
  { english: "Course", spanish: "Curso", pronunciation: "kɔːrs", intonation: "Falling", type: 'COGNATE' },
  { english: "Critical", spanish: "Crítico", pronunciation: "ˈkrɪtɪkl", intonation: "Falling", type: 'COGNATE' },
  { english: "Cycle", spanish: "Ciclo", pronunciation: "ˈsaɪkl", intonation: "Falling", type: 'COGNATE' },
  { english: "Danger", spanish: "Danza (Danger no)", pronunciation: "ˈdeɪndʒər", intonation: "Falling", type: 'COGNATE', spanish: "Peligro (Not a direct cognate for Danza)" },
  { english: "Data", spanish: "Datos", pronunciation: "ˈdeɪtə", intonation: "Falling", type: 'COGNATE' },
  { english: "Decorate", spanish: "Decorar", pronunciation: "ˈdekəreɪt", intonation: "Falling", type: 'COGNATE' },
  { english: "Defend", spanish: "Defender", pronunciation: "dɪˈfend", intonation: "Falling", type: 'COGNATE' },
  { english: "Degree", spanish: "Grado", pronunciation: "dɪˈɡriː", intonation: "Falling", type: 'COGNATE' },
  { english: "Depend", spanish: "Depender", pronunciation: "dɪˈpend", intonation: "Falling", type: 'COGNATE' },
  { english: "Describe", spanish: "Describir", pronunciation: "dɪˈskraɪb", intonation: "Falling", type: 'COGNATE' },
  { english: "Desert", spanish: "Desierto", pronunciation: "ˈdezərt", intonation: "Falling", type: 'COGNATE' },
  { english: "Design", spanish: "Diseño", pronunciation: "dɪˈzaɪn", intonation: "Falling", type: 'COGNATE' },
  { english: "Detail", spanish: "Detalle", pronunciation: "ˈdiːteɪl", intonation: "Falling", type: 'COGNATE' },
  { english: "Detect", spanish: "Detectar", pronunciation: "dɪˈtekt", intonation: "Falling", type: 'COGNATE' },
  { english: "Digital", spanish: "Digital", pronunciation: "ˈdɪdʒɪtl", intonation: "Falling", type: 'COGNATE' },
  { english: "Direction", spanish: "Dirección", pronunciation: "dəˈrekʃn", intonation: "Falling", type: 'COGNATE' },
  { english: "Discard", spanish: "Descartar", pronunciation: "dɪˈskɑːrd", intonation: "Falling", type: 'COGNATE' },
  { english: "Discover", spanish: "Descubrir", pronunciation: "dɪˈskʌvər", intonation: "Falling", type: 'COGNATE' },
  { english: "Distribution", spanish: "Distribución", pronunciation: "ˌdɪstrɪˈbjuːʃn", intonation: "Falling", type: 'COGNATE' },
  { english: "Division", spanish: "División", pronunciation: "dɪˈvɪʒn", intonation: "Falling", type: 'COGNATE' },
  { english: "Document", spanish: "Documento", pronunciation: "ˈdɒkjumənt", intonation: "Falling", type: 'COGNATE' },
  { english: "Drama", spanish: "Drama", pronunciation: "ˈdrɑːmə", intonation: "Falling", type: 'COGNATE' },
  { english: "Economy", spanish: "Economía", pronunciation: "ɪˈkɒnəmi", intonation: "Falling", type: 'COGNATE' },
  { english: "Edition", spanish: "Edición", pronunciation: "ɪˈdɪʃn", intonation: "Falling", type: 'COGNATE' },
  { english: "Education", spanish: "Educación", pronunciation: "ˌedʒuˈkeɪʃn", intonation: "Falling", type: 'COGNATE' },
  { english: "Effect", spanish: "Efecto", pronunciation: "ɪˈfekt", intonation: "Falling", type: 'COGNATE' },
  { english: "Efficiency", spanish: "Eficiencia", pronunciation: "ɪˈfɪʃnsi", intonation: "Falling", type: 'COGNATE' },
  { english: "Electric", spanish: "Eléctrico", pronunciation: "ɪˈlektrɪk", intonation: "Falling", type: 'COGNATE' },
  { english: "Element", spanish: "Elemento", pronunciation: "ˈelɪmənt", intonation: "Falling", type: 'COGNATE' },
  { english: "Elevation", spanish: "Elevación", pronunciation: "ˌelɪˈveɪʃn", intonation: "Falling", type: 'COGNATE' },
  { english: "Elimination", spanish: "Eliminación", pronunciation: "ɪˌlɪmɪˈneɪʃn", intonation: "Falling", type: 'COGNATE' },
  { english: "Energy", spanish: "Energía", pronunciation: "ˈenədʒi", intonation: "Falling", type: 'COGNATE' },
  { english: "Entrance", spanish: "Entrada", pronunciation: "ˈentrəns", intonation: "Falling", type: 'COGNATE' },
  { english: "Equality", spanish: "Igualdad", pronunciation: "iˈkwɒləti", intonation: "Falling", type: 'COGNATE' },
  { english: "Equation", spanish: "Ecuación", pronunciation: "ɪˈkweɪʒn", intonation: "Falling", type: 'COGNATE' },
  { english: "Equivalence", spanish: "Equivalencia", pronunciation: "ɪˈkwɪvələns", intonation: "Falling", type: 'COGNATE' },
  { english: "Escaped", spanish: "Escapado", pronunciation: "ɪˈskeɪpt", intonation: "Falling", type: 'COGNATE' },
  { english: "Essential", spanish: "Esencial", pronunciation: "ɪˈsenʃl", intonation: "Falling", type: 'COGNATE' },
  { english: "Estimate", spanish: "Estimar", pronunciation: "ˈestɪmeɪt", intonation: "Falling", type: 'COGNATE' },
  { english: "Eventual", spanish: "Eventual", pronunciation: "ɪˈventʃuəl", intonation: "Falling", type: 'COGNATE' },
  { english: "Evident", spanish: "Evidente", pronunciation: "ˈevɪdənt", intonation: "Falling", type: 'COGNATE' },
  { english: "Evolution", spanish: "Evolución", pronunciation: "ˌiːvəˈluːʃn", intonation: "Falling", type: 'COGNATE' },
  { english: "Exaggerate", spanish: "Exagerar", pronunciation: "ɪɡˈzædʒəreɪt", intonation: "Falling", type: 'COGNATE' },
  { english: "Examine", spanish: "Examinar", pronunciation: "ɪɡˈzæmɪn", intonation: "Falling", type: 'COGNATE' },
  { english: "Exception", spanish: "Excepción", pronunciation: "ɪkˈsepʃn", intonation: "Falling", type: 'COGNATE' },
  { english: "Excessive", spanish: "Excesivo", pronunciation: "ɪkˈsesɪv", intonation: "Falling", type: 'COGNATE' },
  { english: "Exchange", spanish: "Canje", pronunciation: "ɪksˈtʃeɪndʒ", intonation: "Falling", type: 'COGNATE' },
  { english: "Exclusive", spanish: "Exclusivo", pronunciation: "ɪkˈskluːsɪv", intonation: "Falling", type: 'COGNATE' },
  { english: "Excursion", spanish: "Excursión", pronunciation: "ɪkˈskɜːrʒn", intonation: "Falling", type: 'COGNATE' },
  { english: "Execution", spanish: "Ejecución", pronunciation: "ˌeksɪˈkjuːʃn", intonation: "Falling", type: 'COGNATE' },
  { english: "Exhibition", spanish: "Exhibición", pronunciation: "ˌeksɪˈbɪʃn", intonation: "Falling", type: 'COGNATE' },
  { english: "Existence", spanish: "Existencia", pronunciation: "ɪɡˈzɪstəns", intonation: "Falling", type: 'COGNATE' },
  { english: "Exotic", spanish: "Exótico", pronunciation: "ɪɡˈzɒtɪk", intonation: "Falling", type: 'COGNATE' },
  { english: "Expansion", spanish: "Expansión", pronunciation: "ɪkˈspænʃn", intonation: "Falling", type: 'COGNATE' },
  { english: "Experiment", spanish: "Experimento", pronunciation: "ɪkˈsperɪmənt", intonation: "Falling", type: 'COGNATE' },
  { english: "Explosion", spanish: "Explosión", pronunciation: "ɪkˈspləʊʒn", intonation: "Falling", type: 'COGNATE' },
  { english: "Expressive", spanish: "Expresivo", pronunciation: "ɪkˈspresɪv", intonation: "Falling", type: 'COGNATE' },
  { english: "External", spanish: "Externo", pronunciation: "ɪkˈstɜːrnl", intonation: "Falling", type: 'COGNATE' },
  { english: "Fact", spanish: "Facto (Hecho)", pronunciation: "fækt", intonation: "Falling", type: 'COGNATE' },
  { english: "Facility", spanish: "Facilidad", pronunciation: "fəˈsɪləti", intonation: "Falling", type: 'COGNATE' },
  { english: "Factor", spanish: "Factor", pronunciation: "ˈfæktər", intonation: "Falling", type: 'COGNATE' },
  { english: "Fantasy", spanish: "Fantasía", pronunciation: "ˈfæntəsi", intonation: "Falling", type: 'COGNATE' },
  { english: "Festival", spanish: "Festival", pronunciation: "ˈfestɪvl", intonation: "Falling", type: 'COGNATE' },
  { english: "Fiction", spanish: "Ficción", pronunciation: "ˈfɪkʃn", intonation: "Falling", type: 'COGNATE' },
  { english: "Finance", spanish: "Finanzas", pronunciation: "ˈfaɪnæns", intonation: "Falling", type: 'COGNATE' },
  { english: "Flexible", spanish: "Flexible", pronunciation: "ˈfleksəbl", intonation: "Falling", type: 'COGNATE' },
  { english: "Form", spanish: "Forma", pronunciation: "fɔːrm", intonation: "Falling", type: 'COGNATE' },
  { english: "Fragile", spanish: "Frágil", pronunciation: "ˈfrædʒaɪl", intonation: "Falling", type: 'COGNATE' },
  { english: "Function", spanish: "Función", pronunciation: "ˈfʌŋkʃn", intonation: "Falling", type: 'COGNATE' },

  // --- FALSE COGNATES (1-80) ---
  { english: "Actually", spanish: "De hecho / En realidad", appearsToSay: "Actualmente", pronunciation: "ˈæktʃuəli", intonation: "Falling", type: 'FALSE_COGNATE', meaningActual: "Real fact, not current time" },
  { english: "Library", spanish: "Biblioteca", appearsToSay: "Librería", pronunciation: "ˈlaɪbrəri", intonation: "Falling", type: 'FALSE_COGNATE', meaningActual: "A place where books are kept, not sold" },
  { english: "Assist", spanish: "Ayudar", appearsToSay: "Asistir (ir)", pronunciation: "əˈsɪst", intonation: "Falling", type: 'FALSE_COGNATE', meaningActual: "To help someone" },
  { english: "Attend", spanish: "Asistir (ir)", appearsToSay: "Atender", pronunciation: "əˈtend", intonation: "Falling", type: 'FALSE_COGNATE', meaningActual: "To go to an event" },
  { english: "Exit", spanish: "Salida", appearsToSay: "Éxito", pronunciation: "ˈeɡzɪt", intonation: "Falling", type: 'FALSE_COGNATE', meaningActual: "A way out" },
  { english: "Embarrassed", spanish: "Avergonzado/a", appearsToSay: "Embarazada", pronunciation: "ɪmˈbærəst", intonation: "Falling", type: 'FALSE_COGNATE', meaningActual: "Feeling shame or shyness" },
  { english: "Fabric", spanish: "Tela / Tejido", appearsToSay: "Fábrica", pronunciation: "ˈfæbrɪk", intonation: "Falling", type: 'FALSE_COGNATE', meaningActual: "Material used for clothing" },
  { english: "Parents", spanish: "Padres", appearsToSay: "Parientes", pronunciation: "ˈpeərənts", intonation: "Falling", type: 'FALSE_COGNATE', meaningActual: "Father and mother" },
  { english: "Notice", spanish: "Anuncio / Aviso", appearsToSay: "Noticia", pronunciation: "ˈnəʊtɪs", intonation: "Falling", type: 'FALSE_COGNATE', meaningActual: "A sign or piece of information" },
  { english: "Carpet", spanish: "Alfombra", appearsToSay: "Carpeta", pronunciation: "ˈkɑːrpɪt", intonation: "Falling", type: 'FALSE_COGNATE', meaningActual: "Floor covering" },
  { english: "Actual", spanish: "Real / Verdadero", appearsToSay: "Actual (en este momento)", pronunciation: "ˈæktʃuəl", intonation: "Falling", type: 'FALSE_COGNATE', meaningActual: "Existing in fact" },
  { english: "Molest", spanish: "Abusar / Acosar", appearsToSay: "Molestar", pronunciation: "məˈlest", intonation: "Falling", type: 'FALSE_COGNATE', meaningActual: "To sexually assault" },
  { english: "Advertisement", spanish: "Anuncio publicitario", appearsToSay: "Advertencia", pronunciation: "ədˈvɜːrtɪsmənt", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Advice", spanish: "Consejo", appearsToSay: "Aviso", pronunciation: "ədˈvaɪs", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Arena", spanish: "Estadio / Plaza", appearsToSay: "Arena (playa)", pronunciation: "əˈriːnə", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Argument", spanish: "Discusión", appearsToSay: "Argumento", pronunciation: "ˈɑːrɡjumənt", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Billion", spanish: "Mil millones", appearsToSay: "Billón", pronunciation: "ˈbɪljən", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Casualty", spanish: "Víctima / Baja", appearsToSay: "Casualidad", pronunciation: "ˈkæʒuəlti", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Collar", spanish: "Cuello (camisa)", appearsToSay: "Collar (joya)", pronunciation: "ˈkɒlər", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Complexion", spanish: "Tez / Piel", appearsToSay: "Complexión (físico)", pronunciation: "kəmˈplekʃn", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Compromise", spanish: "Ceder / Llegar a un acuerdo", appearsToSay: "Compromiso", pronunciation: "ˈkɒmprəmaɪz", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Conductor", spanish: "Director de orquesta", appearsToSay: "Conductor (coche)", pronunciation: "kənˈdʌktər", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Contest", spanish: "Concurso", appearsToSay: "Contestar", pronunciation: "ˈkɒntest", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Curse", spanish: "Maldición / Jurar", appearsToSay: "Curso", pronunciation: "kɜːrs", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Deception", spanish: "Engaño", appearsToSay: "Decepción", pronunciation: "dɪˈsepʃn", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Dinner", spanish: "Cena", appearsToSay: "Dinero", pronunciation: "ˈdɪnər", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Disgrace", spanish: "Vergüenza / Deshonra", appearsToSay: "Desgracia", pronunciation: "dɪsˈɡreɪs", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Diversion", spanish: "Desvío", appearsToSay: "Diversión", pronunciation: "daɪˈvɜːrʒn", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Envelope", spanish: "Sobre", appearsToSay: "Envolver", pronunciation: "ˈenvələʊp", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Eventually", spanish: "Finalmente", appearsToSay: "Eventualmente", pronunciation: "ɪˈventʃuəli", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Idiom", spanish: "Modismo / Frase hecha", appearsToSay: "Idioma", pronunciation: "ˈɪdiəm", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Ingenuity", spanish: "Ingenio", appearsToSay: "Ingenuidad", pronunciation: "ˌɪndʒəˈnjuːəti", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Introduce", spanish: "Presentar a alguien", appearsToSay: "Introducir", pronunciation: "ˌɪntrəˈdjuːs", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Large", spanish: "Grande", appearsToSay: "Largo", pronunciation: "lɑːrdʒ", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Mayor", spanish: "Alcalde", appearsToSay: "Mayor", pronunciation: "meər", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Misery", spanish: "Tristeza extrema", appearsToSay: "Miseria (pobreza)", pronunciation: "ˈmɪzəri", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Nervous", spanish: "Inquieto / Ansioso", appearsToSay: "Nervioso (temperamento)", pronunciation: "ˈnɜːrvəs", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Realize", spanish: "Darse cuenta", appearsToSay: "Realizar", pronunciation: "ˈriːəlaɪz", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Record", spanish: "Grabar / Disco", appearsToSay: "Recordar", pronunciation: "ˈrekɔːrd", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Remove", spanish: "Quitar / Eliminar", appearsToSay: "Remover", pronunciation: "rɪˈmuːv", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Sane", spanish: "Cuerdo", appearsToSay: "Sano", pronunciation: "seɪn", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Signature", spanish: "Firma", appearsToSay: "Asignatura", pronunciation: "ˈsɪɡnətʃər", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Success", spanish: "Éxito", appearsToSay: "Suceso", pronunciation: "səkˈses", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Target", spanish: "Objetivo", appearsToSay: "Tarjeta", pronunciation: "ˈtɑːrɡɪt", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Terrific", spanish: "Genial", appearsToSay: "Terrorífico", pronunciation: "təˈrɪfɪk", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Topic", spanish: "Tema", appearsToSay: "Tópico", pronunciation: "ˈtɒpɪk", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Career", spanish: "Carrera profesional", appearsToSay: "Carrera (correr)", pronunciation: "kəˈrɪər", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Constipated", spanish: "Estreñido", appearsToSay: "Constipado (resfriado)", pronunciation: "ˈkɒnstɪpeɪtɪd", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Preservative", spanish: "Conservante", appearsToSay: "Preservativo (condón)", pronunciation: "prɪˈzɜːrvətɪv", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Rope", spanish: "Cuerda", appearsToSay: "Ropa", pronunciation: "rəʊp", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Soap", spanish: "Jabón", appearsToSay: "Sopa", pronunciation: "səʊp", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Vase", spanish: "Florero", appearsToSay: "Vaso", pronunciation: "vɑːz", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Gym", spanish: "Gimnasio", appearsToSay: "Gimnasio (escuela)", pronunciation: "dʒɪm", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Journal", spanish: "Diario / Revista", appearsToSay: "Jornal", pronunciation: "ˈdʒɜːrnl", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Lecture", spanish: "Conferencia", appearsToSay: "Lectura", pronunciation: "ˈlektʃər", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Pretend", spanish: "Fingir", appearsToSay: "Pretender (intentar)", pronunciation: "prɪˈtend", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Once", spanish: "Una vez", appearsToSay: "Once (número)", pronunciation: "wʌns", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Pan", spanish: "Sartén", appearsToSay: "Pan", pronunciation: "pæn", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Pie", spanish: "Pastel / Tarta", appearsToSay: "Pie", pronunciation: "paɪ", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Red", spanish: "Rojo", appearsToSay: "Red (malla)", pronunciation: "red", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Salty", spanish: "Salado", appearsToSay: "Saltar", pronunciation: "ˈsɔːlti", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Sensible", spanish: "Sensato", appearsToSay: "Sensible", pronunciation: "ˈsensəbl", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Sensitive", spanish: "Sensible", appearsToSay: "Sensitivo", pronunciation: "ˈsensətɪv", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Sort", spanish: "Ordenar / Tipo", appearsToSay: "Suerte", pronunciation: "sɔːrt", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Tuna", spanish: "Atún", appearsToSay: "Tuna (higo chumbo)", pronunciation: "ˈtjuːnə", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Used to", spanish: "Solía", appearsToSay: "Usado para", pronunciation: "juːst tuː", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Commodity", spanish: "Mercancía", appearsToSay: "Comodidad", pronunciation: "kəˈmɒdəti", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Compliment", spanish: "Cumplido", appearsToSay: "Complemento", pronunciation: "ˈkɒmplɪmənt", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Inhabitant", spanish: "Habitante", appearsToSay: "Inhabitante (vacío)", pronunciation: "ɪnˈhæbɪtənt", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Inhabitable", spanish: "Habitable", appearsToSay: "Inhabitable (no habitable)", pronunciation: "ɪnˈhæbɪtəbl", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Sanity", spanish: "Cordura", appearsToSay: "Sanidad (salud)", pronunciation: "ˈsænəti", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Scholastic", spanish: "Académico", appearsToSay: "Escolástico", pronunciation: "skəˈlæstɪk", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Spade", spanish: "Pala", appearsToSay: "Espada", pronunciation: "speɪd", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Supply", spanish: "Suministro", appearsToSay: "Suplicar", pronunciation: "səˈplaɪ", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Sympathy", spanish: "Compasión / Empatía", appearsToSay: "Simpatía", pronunciation: "ˈsɪmpəθi", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Trivial", spanish: "Insignificante", appearsToSay: "Trivial", pronunciation: "ˈtrɪviəl", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Ultimate", spanish: "Definitivo", appearsToSay: "Último", pronunciation: "ˈʌltɪmət", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Abstract", spanish: "Resumen", appearsToSay: "Abstracto", pronunciation: "ˈæbstrækt", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Avocado", spanish: "Aguacate", appearsToSay: "Abogado", pronunciation: "ˌævəˈkɑːdəʊ", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Balloon", spanish: "Globo", appearsToSay: "Balón", pronunciation: "bəˈluːn", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Blade", spanish: "Hoja", appearsToSay: "Helado", pronunciation: "bleɪd", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Brave", spanish: "Valiente", appearsToSay: "Bravo", pronunciation: "breɪv", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Cane", spanish: "Bastón", appearsToSay: "Caña", pronunciation: "keɪn", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Cartoon", spanish: "Dibujos animados", appearsToSay: "Cartón", pronunciation: "kɑːrˈtuːn", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Chili", spanish: "Guindilla", appearsToSay: "Chile", pronunciation: "ˈtʃɪli", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Comfort", spanish: "Consolar / Comodidad", appearsToSay: "Confort", pronunciation: "ˈkʌmfərt", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Complexion", spanish: "Tez", appearsToSay: "Complexión", pronunciation: "kəmˈplekʃn", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Conductor", spanish: "Director de orquesta", appearsToSay: "Conductor", pronunciation: "kənˈdʌktər", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Contest", spanish: "Concurso", appearsToSay: "Contestar", pronunciation: "ˈkɒntest", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Dam", spanish: "Presa", appearsToSay: "Dama", pronunciation: "dæm", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Date", spanish: "Cita", appearsToSay: "Dato", pronunciation: "deɪt", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Deceive", spanish: "Engañar", appearsToSay: "Decepcionar", pronunciation: "dɪˈsiːv", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Deface", spanish: "Deteriorar", appearsToSay: "Desfasar", pronunciation: "dɪˈfeɪs", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Degree", spanish: "Título", appearsToSay: "Degradado", pronunciation: "dɪˈɡriː", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Dependent", spanish: "Dependiente (adj)", appearsToSay: "Dependiente (tienda)", pronunciation: "dɪˈpendənt", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Digest", spanish: "Resumen / Digerir", appearsToSay: "Digesto", pronunciation: "ˈdaɪdʒest", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Disapprove", spanish: "Desaprobar", appearsToSay: "Desaprobar (examen)", pronunciation: "ˌdɪsəˈpruːv", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Disgusted", spanish: "Asco / Indignado", appearsToSay: "Disgustado", pronunciation: "dɪsˈɡʌstɪd", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Disturb", spanish: "Molestar / Interrumpir", appearsToSay: "Disturbar", pronunciation: "dɪˈstɜːrb", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Dress", spanish: "Vestido", appearsToSay: "Dirección", pronunciation: "dres", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Editor", spanish: "Redactor Jefe", appearsToSay: "Editor (casa editorial)", pronunciation: "ˈedɪtər", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Educate", spanish: "Instruir / Educar", appearsToSay: "Educado (males)", pronunciation: "ˈedʒukeɪt", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Effective", spanish: "Eficaz", appearsToSay: "Efectivo", pronunciation: "ɪˈfektɪv", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Embrace", spanish: "Abrazar", appearsToSay: "Embarazo", pronunciation: "ɪmˈbreɪs", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Estate", spanish: "Finca", appearsToSay: "Estado", pronunciation: "ɪˈsteɪt", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Exhibit", spanish: "Exponer", appearsToSay: "Exhibicionista", pronunciation: "ɪɡˈzɪbɪt", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Exposure", spanish: "Exposición", appearsToSay: "Exposición (arte)", pronunciation: "ɪkˈspəʊʒər", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Face", spanish: "Cara", appearsToSay: "Fase", pronunciation: "feɪs", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Factor", spanish: "Factor (matemáticas)", appearsToSay: "Factor (trabajador)", pronunciation: "ˈfæktər", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Fast", spanish: "Rápido", appearsToSay: "Fasto", pronunciation: "fɑːst", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Feet", spanish: "Pies", appearsToSay: "Fiesta", pronunciation: "fiːt", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "File", spanish: "Archivo", appearsToSay: "Fila", pronunciation: "faɪl", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Fin", spanish: "Aleta", appearsToSay: "Fin", pronunciation: "fɪn", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Fine", spanish: "Multa", appearsToSay: "Fino", pronunciation: "faɪn", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Foil", spanish: "Papel de aluminio", appearsToSay: "Follar", pronunciation: "fɔɪl", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Foot", spanish: "Pie", appearsToSay: "Foto", pronunciation: "fʊt", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Formal", spanish: "Elegante", appearsToSay: "Formal (persona)", pronunciation: "ˈfɔːrml", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Grape", spanish: "Uva", appearsToSay: "Grapa", pronunciation: "ɡreɪp", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Grave", spanish: "Tumba / Serio", appearsToSay: "Grave", pronunciation: "ɡreɪv", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Grime", spanish: "Mugre", appearsToSay: "Grito", pronunciation: "ɡraɪm", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Grocery", spanish: "Tienda comestibles", appearsToSay: "Grosería", pronunciation: "ˈɡrəʊsəri", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Habit", spanish: "Hábito (costumbre)", appearsToSay: "Hábito (monja)", pronunciation: "ˈhæbɪt", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Hand", spanish: "Mano", appearsToSay: "Hando", pronunciation: "hænd", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Hose", spanish: "Manguera", appearsToSay: "Jose", pronunciation: "həʊz", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Humor", spanish: "Hilaridad", appearsToSay: "Humor (ánimo)", pronunciation: "ˈhjuːmər", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Idiot", spanish: "Túpeto", appearsToSay: "Idiota", pronunciation: "ˈɪdiət", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Ignite", spanish: "Encender", appearsToSay: "Ignorar", pronunciation: "ɪɡˈnaɪt", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Ignore", spanish: "No hacer caso", appearsToSay: "Ignorar (desconocer)", pronunciation: "ɪɡˈnɔːr", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Impose", spanish: "Poner", appearsToSay: "Imponer", pronunciation: "ɪmˈpəʊz", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Inhabitant", spanish: "Morador", appearsToSay: "Inhabitante", pronunciation: "ɪnˈhæbɪtənt", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Injury", spanish: "Herida", appearsToSay: "Injuria", pronunciation: "ˈɪndʒəri", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Insulate", spanish: "Aislar", appearsToSay: "Insultar", pronunciation: "ˈɪnsjuleɪt", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Intend", spanish: "Tener la intención", appearsToSay: "Intentar", pronunciation: "ɪnˈtend", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Intoxicated", spanish: "Borracho", appearsToSay: "Intoxicado", pronunciation: "ɪnˈtɒksɪkeɪtɪd", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Jab", spanish: "Puyazo", appearsToSay: "Hablar", pronunciation: "dʒæb", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Jam", spanish: "Mermelada", appearsToSay: "Jamón", pronunciation: "dʒæm", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Journal", spanish: "Diario", appearsToSay: "Jornal", pronunciation: "ˈdʒɜːrnl", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Judge", spanish: "Juez", appearsToSay: "Jugo", pronunciation: "dʒʌdʒ", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Just", spanish: "Solo", appearsToSay: "Justo", pronunciation: "dʒʌst", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Knots", spanish: "Nudos", appearsToSay: "Notas", pronunciation: "nɒts", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Lame", spanish: "Cojera", appearsToSay: "Lamer", pronunciation: "leɪm", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Large", spanish: "Grande", appearsToSay: "Largo", pronunciation: "lɑːrdʒ", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Leaf", spanish: "Hoja", appearsToSay: "Leal", pronunciation: "liːf", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Lent", spanish: "Prestado", appearsToSay: "Lento", pronunciation: "lent", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Library", spanish: "Biblioteca", appearsToSay: "Librería", pronunciation: "ˈlaɪbrəri", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Lobby", spanish: "Vestíbulo", appearsToSay: "Lobo", pronunciation: "ˈlɒbi", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Luxury", spanish: "Lujo", appearsToSay: "Lujuria", pronunciation: "ˈlʌkʃəri", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Marsh", spanish: "Pantano", appearsToSay: "Marcha", pronunciation: "mɑːrʃ", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Mayor", spanish: "Alcalde", appearsToSay: "Mayor", pronunciation: "meər", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Men", spanish: "Hombres", appearsToSay: "Menú", pronunciation: "men", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Mere", spanish: "Puro", appearsToSay: "Mera", pronunciation: "mɪər", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Misery", spanish: "Tristeza", appearsToSay: "Miseria", pronunciation: "ˈmɪzəri", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Moan", spanish: "Gemido", appearsToSay: "Mono", pronunciation: "məʊn", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Modes", spanish: "Modos", appearsToSay: "Modas", pronunciation: "məʊdz", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Notice", spanish: "Aviso", appearsToSay: "Noticia", pronunciation: "ˈnəʊtɪs", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Novel", spanish: "Novela", appearsToSay: "Nobel", pronunciation: "ˈnɒvl", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Nude", spanish: "Desnudo", appearsToSay: "Nudo", pronunciation: "njuːd", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Once", spanish: "Una vez", appearsToSay: "Once (número)", pronunciation: "wʌns", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Pan", spanish: "Sartén", appearsToSay: "Pan", pronunciation: "pæn", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Petrol", spanish: "Gasolina", appearsToSay: "Petróleo", pronunciation: "ˈpetrəl", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Pie", spanish: "Pastel", appearsToSay: "Pie", pronunciation: "paɪ", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Preservative", spanish: "Conservante", appearsToSay: "Preservativo", pronunciation: "prɪˈzɜːrvətɪv", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Pretend", spanish: "Fingir", appearsToSay: "Pretender", pronunciation: "prɪˈtend", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Prune", spanish: "Ciruela pasa", appearsToSay: "Pruna", pronunciation: "pruːn", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Rare", spanish: "Poco común / Crudo (carne)", appearsToSay: "Raro", pronunciation: "reər", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Receipt", spanish: "Recibo", appearsToSay: "Receta", pronunciation: "rɪˈsiːt", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Recipe", spanish: "Receta (cocina)", appearsToSay: "Recibo", pronunciation: "ˈresəpi", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Red", spanish: "Rojo", appearsToSay: "Red", pronunciation: "red", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Resort", spanish: "Centro de vacaciones", appearsToSay: "Resorte", pronunciation: "rɪˈzɔːrt", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Rope", spanish: "Cuerda", appearsToSay: "Ropa", pronunciation: "rəʊp", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Sane", spanish: "Cuerdo", appearsToSay: "Sano", pronunciation: "seɪn", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Sensible", spanish: "Sensato", appearsToSay: "Sensible", pronunciation: "ˈsensəbl", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Sensitive", spanish: "Sensible", appearsToSay: "Sensitivo", pronunciation: "ˈsensətɪv", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Signature", spanish: "Firma", appearsToSay: "Asignatura", pronunciation: "ˈsɪɡnətʃər", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Soap", spanish: "Jabón", appearsToSay: "Sopa", pronunciation: "səʊp", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Success", spanish: "Éxito", appearsToSay: "Suceso", pronunciation: "səkˈses", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Support", spanish: "Apoyar", appearsToSay: "Soportar", pronunciation: "səˈpɔːrt", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Sympathy", spanish: "Empatía", appearsToSay: "Simpatía", pronunciation: "ˈsɪmpəθi", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Target", spanish: "Objetivo", appearsToSay: "Tarjeta", pronunciation: "ˈtɑːrɡɪt", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Terrific", spanish: "Estupendo", appearsToSay: "Terrorífico", pronunciation: "təˈrɪfɪk", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Topic", spanish: "Tema", appearsToSay: "Tópico", pronunciation: "ˈtɒpɪk", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Tuna", spanish: "Atún", appearsToSay: "Tuna", pronunciation: "ˈtjuːnə", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Ultimate", spanish: "Final", appearsToSay: "Último", pronunciation: "ˈʌltɪmət", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Vase", spanish: "Florero", appearsToSay: "Vaso", pronunciation: "vɑːz", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Vice", spanish: "Vicio (pero Vice- en cargos)", appearsToSay: "Vice", pronunciation: "vaɪs", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Violator", spanish: "Infractor", appearsToSay: "Violador", pronunciation: "ˈvaɪəleɪtər", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Wait", spanish: "Esperar", appearsToSay: "Vate", pronunciation: "weɪt", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Wine", spanish: "Vino", appearsToSay: "Winnie", pronunciation: "waɪn", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Zap", spanish: "Destruir / Moverse rápido", appearsToSay: "Sapo", pronunciation: "zæp", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Zero", spanish: "Cero", appearsToSay: "Serio", pronunciation: "ˈzɪərəʊ", intonation: "Falling", type: 'FALSE_COGNATE' },
  { english: "Zoo", spanish: "Zoológico", appearsToSay: "Su", pronunciation: "zuː", intonation: "Falling", type: 'FALSE_COGNATE' },
];
