
export interface ComplexWord {
  word: string;
  translation: string;
  pronunciation: string;
  ipaUS: string;
  ipaUK: string;
  meaning: string;
}

export const COMPLEX_WORDS: ComplexWord[] = [
  { word: "Aberrant", translation: "Deviant", pronunciation: "uh-BER-uhnt", ipaUS: "/ æˈberənt /", ipaUK: "/ əˈberənt /", meaning: "Departing from an accepted standard." },
  { word: "Accede", translation: "Agree", pronunciation: "uhk-seed", ipaUS: "/ əkˈsiːd /", ipaUK: "/ əkˈsiːd /", meaning: "Assent or agree to a demand, request, or treaty." },
  { word: "Accessory", translation: "Addition", pronunciation: "uhk-ses-uh-ree", ipaUS: "/ əkˈsesəri /", ipaUK: "/ əkˈsesəri /", meaning: "A thing which can be added to something else in order to make it more useful, versatile, or attractive." },
  { word: "Adamant", translation: "Stubborn", pronunciation: "AD-uh-muhnt", ipaUS: "/ ˈædəmənt /", ipaUK: "/ ˈædəmənt /", meaning: "Refusing to be persuaded or to change one's mind." },
  { word: "Adumbrate", translation: "Sketch", pronunciation: "ad-UHM-breyt", ipaUS: "/ ˈædəmbreɪt /", ipaUK: "/ ˈædəmbreɪt /", meaning: "Report or represent in outline." },
  { word: "Agoraphobia", translation: "Crowd fear", pronunciation: "uh-gaw-ruh-foh-bee-uh", ipaUS: "/ ˌæɡərəˈfəʊbiə /", ipaUK: "/ ˌæɡərəˈfəʊbiə /", meaning: "Extreme or irrational fear of entering open or crowded places." },
  { word: "Albeit", translation: "Although", pronunciation: "all-BEE-it", ipaUS: "/ ɒlˈbiːət /", ipaUK: "/ ɔːlˈbiːɪt /", meaning: "Though." },
  { word: "Alias", translation: "Pseudonym", pronunciation: "ay-lee-uhs", ipaUS: "/ ˈeɪliəs /", ipaUK: "/ ˈeɪliəs /", meaning: "Used to indicate that a person is also known by another name." },
  { word: "Almond", translation: "Nut type", pronunciation: "AL-muhnd", ipaUS: "/ ˈɑːmənd /", ipaUK: "/ ˈɑːmənd /", meaning: "The oval edible nutlike seed of the almond tree." },
  { word: "Anathema", translation: "Abomination", pronunciation: "uh-nath-uh-muh", ipaUS: "/ əˈnæθəmə /", ipaUK: "/ əˈnæθəmə /", meaning: "Something or someone that one vehemently dislikes." },
  { word: "Anemone", translation: "Flower", pronunciation: "uh-nem-uh-nee", ipaUS: "/ əˈneməni /", ipaUK: "/ əˈneməni /", meaning: "A plant of the buttercup family." },
  { word: "Anesthetist", translation: "Medical expert", pronunciation: "uh-neth-uh-tist", ipaUS: "/ əˈniːsθətɪst /", ipaUK: "/ əˈniːsθətɪst /", meaning: "A medical specialist who administers anesthetics." },
  { word: "Aneurysm", translation: "Swelling", pronunciation: "uh-nur-izm", ipaUS: "/ ˈænjəˌrɪzəm /", ipaUK: "/ ˈænjəˌrɪzəm /", meaning: "An excessive localized enlargement of an artery caused by a weakening of the artery wall." },
  { word: "Antarctic", translation: "South pole", pronunciation: "ant-ARK-tik", ipaUS: "/ ænˈtɑːktɪk /", ipaUK: "/ ænˈtɑːktɪk /", meaning: "The region around the South Pole." },
  { word: "Anthropomorphism", translation: "Personification", pronunciation: "an-thruh-puh-mawr-fiz-uhm", ipaUS: "/ ˌænθrəʊpəʊˈmɔːfˌɪzəm /", ipaUK: "/ ˌænθrəʊpəʊˈmɔːfˌɪzəm /", meaning: "The attribution of human characteristics or behavior to a god, animal, or object." },
  { word: "Antidisestablishmentarianism", translation: "Opposition", pronunciation: "an-teye-dis-es-tab-lish-muhnt-air-ee-uh-niz-uhm", ipaUS: "/ ˌæntidɪsəˌstæbləʃmənˈteriənɪzəm /", ipaUK: "/ ˌæntidɪsəˌstæbləʃmənˈteriənɪzəm /", meaning: "Opposition to the disestablishment of the Church of England." },
  { word: "Apocryphal", translation: "Unauthenticated", pronunciation: "uh-PAHK-ruh-fuhl", ipaUS: "/ əˈpɑːkrəfl̩ /", ipaUK: "/ əˈpɒkrɪfl /", meaning: "Of doubtful authenticity, although widely circulated as being true." },
  { word: "Archetype", translation: "Prototype", pronunciation: "AHR-kih-taip", ipaUS: "/ ˈɑːrkəˌtaɪp /", ipaUK: "/ ˈɑːkɪtaɪp /", meaning: "A very typical example of a certain person or thing." },
  { word: "Archipelago", translation: "Island group", pronunciation: "AHR-kih-pel-uh-goh", ipaUS: "/ ˌɑːrkəˈpeləˌɡoʊ /", ipaUK: "/ ˌɑːkɪˈpɛləɡəʊ /", meaning: "A group of islands." },
  { word: "Ascetic", translation: "Self-denying", pronunciation: "ass-et-ick", ipaUS: "/ əˈsetɪk /", ipaUK: "/ əˈsetɪk /", meaning: "Characterized by or suggesting the practice of severe self-discipline." },
  { word: "Asterisk", translation: "Star symbol", pronunciation: "AS-tuh-risk", ipaUS: "/ ˈæstərɪsk /", ipaUK: "/ ˈæstərɪsk /", meaning: "A symbol (*) used in text as a pointer to an annotation." },
  { word: "Athlete", translation: "Sportsman", pronunciation: "ATH-leet", ipaUS: "/ ˈæθˌlit /", ipaUK: "/ ˈæθliːt /", meaning: "A person who is proficient in sports and other forms of physical exercise." },
  { word: "Bacteriology", translation: "Study of bacteria", pronunciation: "bak-teer-ee-awl-uh-jee", ipaUS: "/ bækˌtɪəriˈɒlədʒi /", ipaUK: "/ bækˌtɪəriˈɒlədʒi /", meaning: "The study of bacteria." },
  { word: "Beguile", translation: "Charm", pronunciation: "bee-GYLE", ipaUS: "/ bɪˈɡaɪl /", ipaUK: "/ bɪˈɡaɪl /", meaning: "Charm or enchant (someone), sometimes in a deceptive way." },
  { word: "Blasphemy", translation: "Sacrilege", pronunciation: "blas-fuh-mee", ipaUS: "/ ˈblæsfəmi /", ipaUK: "/ ˈblæsfəmi /", meaning: "The act or offense of speaking sacrilegiously about God or sacred things." },
  { word: "Bouquet", translation: "Flower bunch", pronunciation: "boo-KAY", ipaUS: "/ buːˈkeɪ /", ipaUK: "/ buˈkeɪ /", meaning: "An attractively arranged bunch of flowers." },
  { word: "Bourbon", translation: "Whiskey type", pronunciation: "BER-buhn", ipaUS: "/ ˈbɝːbən /", ipaUK: "/ ˈbɜːbən /", meaning: "A straight whiskey distilled from a mash having at least 51 percent corn." },
  { word: "Brewery", translation: "Beer factory", pronunciation: "BREW-uh-ree", ipaUS: "/ ˈbruːəri /", ipaUK: "/ ˈbruːəri /", meaning: "A place where beer is made commercially." },
  { word: "Broccoli", translation: "Green vegetable", pronunciation: "BROK-uh-lee", ipaUS: "/ ˈbrɑːkəli /", ipaUK: "/ ˈbrɒkəli /", meaning: "A cultivated variety of cabbage." },
  { word: "Buoy", translation: "Marker", pronunciation: "BOO-ee", ipaUS: "/ ˈbuːi /", ipaUK: "/ bɔɪ /", meaning: "An anchored float serving as a navigation mark." },
  { word: "Bureaucracy", translation: "Administration", pronunciation: "byoo-rok-ruh-see", ipaUS: "/ bjʊəˈrɒkrəsi /", ipaUK: "/ bjʊəˈrɒkrəsi /", meaning: "A system of government in which most of the important decisions are made by state officials." },
  { word: "Bury", translation: "Inter", pronunciation: "BER-ee", ipaUS: "/ ˈberi /", ipaUK: "/ ˈberi /", meaning: "Put or hide under ground." },
  { word: "Cacciatore", translation: "Hunter style", pronunciation: "kuh-chuh-tawr-ee", ipaUS: "/ katʃəˈtɔːi /", ipaUK: "/ ˌkatʃəˈtɔːri /", meaning: "Prepared in a spicy tomato sauce with mushrooms and herbs." },
  { word: "Cache", translation: "Storage", pronunciation: "kash", ipaUS: "/ ˈkæʃ /", ipaUK: "/ ˈkæʃ /", meaning: "A collection of items of the same type stored in a hidden or inaccessible place." },
  { word: "Cacophony", translation: "Din", pronunciation: "kuh-kof-uh-nee", ipaUS: "/ kæˈkɒfəni /", ipaUK: "/ kəˈkɒfəni /", meaning: "A harsh, discordant mixture of sounds." },
  { word: "Cajole", translation: "Coax", pronunciation: "kuh-johl", ipaUS: "/ kəˈdʒoʊl /", ipaUK: "/ kəˈdʒəʊl /", meaning: "Persuade (someone) to do something by sustained coaxing or flattery." },
  { word: "Callous", translation: "Heartless", pronunciation: "kal-us", ipaUS: "/ ˈkæləs /", ipaUK: "/ ˈkæləs /", meaning: "Showing or having an insensitive and cruel disregard for others." },
  { word: "Camaraderie", translation: "Friendship", pronunciation: "kam-ruh-duh-ree", ipaUS: "/ ˌkæməˈrɑːdəri /", ipaUK: "/ ˌkæməˈrɑːdəri /", meaning: "Mutual trust and friendship among people who spend a lot of time together." },
  { word: "Candidate", translation: "Applicant", pronunciation: "KAND-uh-deyt", ipaUS: "/ ˈkændədet /", ipaUK: "/ ˈkændɪdət /", meaning: "A person who applies for a job or is nominated for election." },
  { word: "Caramel", translation: "Candy type", pronunciation: "kar-uh-mel", ipaUS: "/ ˈkerəməl /", ipaUK: "/ ˈkarəmɛl /", meaning: "Sugar or syrup heated until it turns brown, used as a flavoring or coloring for food or drink." },
  { word: "Caricature", translation: "Parody", pronunciation: "kuh-RIK-uh-cher", ipaUS: "/ ˈkerəkətʃər /", ipaUK: "/ ˈkarɪkətʃʊə /", meaning: "A picture, description, or imitation of a person in which certain striking characteristics are exaggerated." },
  { word: "Cavalry", translation: "Horse soldiers", pronunciation: "KAV-uhl-ree", ipaUS: "/ ˈkævəlri /", ipaUK: "/ ˈkævəlri /", meaning: "(In the past) soldiers who fought on horseback." },
  { word: "Chaos", translation: "Disorder", pronunciation: "KAY-ahs", ipaUS: "/ ˈkeɪas /", ipaUK: "/ ˈkeɪɒs /", meaning: "Complete disorder and confusion." },
  { word: "Charcuterie", translation: "Cured meat", pronunciation: "shahr-koo-tuh-REE", ipaUS: "/ ˌʃɑːrˈkuːtəri /", ipaUK: "/ ʃɑːˈkuːtəri /", meaning: "Cold cooked meats collectively." },
  { word: "Chauvinism", translation: "Jingoism", pronunciation: "shoh-vuh-niz-uhm", ipaUS: "/ ˈʃoʊvɪnɪzəm /", ipaUK: "/ ˈʃəʊvɪnɪzəm /", meaning: "Exaggerated or aggressive patriotism." },
  { word: "Chimpanzee", translation: "Ape type", pronunciation: "chimp-uhn-zee", ipaUS: "/ ˌtʃɪmpænˈziː /", ipaUK: "/ ˌtʃɪmpənˈziː /", meaning: "A great ape with large ears, mainly black coloration, and lighter skin on the face." },
  { word: "Chipotle", translation: "Pepper type", pronunciation: "chi-poat-lee", ipaUS: "/ tʃɪˈpoʊtleɪ /", ipaUK: "/ tʃɪˈpɒtleɪ /", meaning: "A smoked and dried jalapeño chili pepper, used in Mexican cooking." },
  { word: "Choir", translation: "Singers", pronunciation: "kwahy-er", ipaUS: "/ ˈkwaɪər /", ipaUK: "/ ˈkwaɪə /", meaning: "An organized group of singers, especially one that takes part in church services." },
  { word: "Clothes", translation: "Apparel", pronunciation: "klohz", ipaUS: "/ kloʊðz /", ipaUK: "/ kləʊðz /", meaning: "Items worn to cover the body." },
  { word: "Cocoa", translation: "Chocolate powder", pronunciation: "koh-KOH", ipaUS: "/ ˈkokoʊ /", ipaUK: "/ ˈkəʊkəʊ /", meaning: "A chocolate powder made from roasted and ground cacao seeds." },
  { word: "Colonel", pronunciation: "ker-nuhl", translation: "Officer", ipaUS: "/ ˈkɜːnl̩ /", ipaUK: "/ ˈkɜːnl /", meaning: "An officer of high rank in the army." },
  { word: "Comfortable", translation: "Cozy", pronunciation: "kum-fuhr-tuh-buhl", ipaUS: "/ ˈkʌmftəbl̩ /", ipaUK: "/ ˈkʌmftəbl /", meaning: "(Especially of clothes or a vehicle) providing physical ease and relaxation." },
  { word: "Coup", translation: "Takeover", pronunciation: "koo", ipaUS: "/ ˈkuː /", ipaUK: "/ ˈkuː /", meaning: "A sudden, violent, and illegal seizure of power from a government." },
  { word: "Data", translation: "Information", pronunciation: "day-tuh", ipaUS: "/ ˈdeɪtə /", ipaUK: "/ ˈdeɪtə /", meaning: "Facts and statistics collected together for reference or analysis." },
  { word: "Debris", translation: "Rubbish", pronunciation: "DEB-ree", ipaUS: "/ dəˈbriː /", ipaUK: "/ ˈdeɪbriː /", meaning: "Scattered pieces of waste or remains." },
  { word: "Debut", translation: "Opening", pronunciation: "dey-BYOO", ipaUS: "/ ˈdeɪbjuː /", ipaUK: "/ ˈdeɪbjuː /", meaning: "A person's first appearance or performance in a particular capacity or role." },
  { word: "February", translation: "Month", pronunciation: "feb-roo-air-ee", ipaUS: "/ ˈfebjʊəri /", ipaUK: "/ ˈfɛbrʊəri /", meaning: "The second month of the year." },
  { word: "GIF", translation: "Animation", pronunciation: "jif", ipaUS: "/ ɡɪf /", ipaUK: "/ dʒɪf /", meaning: "A lossless format for image files that supports both animated and static images." },
  { word: "Hierarchy", translation: "Rank", pronunciation: "HAHY-er-ahr-kee", ipaUS: "/ ˈhaɪəˌrɑːrki /", ipaUK: "/ ˈhaɪərɑːki /", meaning: "A system or organization in which people or groups are ranked one above the other according to status or authority." },
  { word: "Island", translation: "Atoll", pronunciation: "AYL-land", ipaUS: "/ ˈaɪlənd /", ipaUK: "/ ˈaɪlənd /", meaning: "A piece of land surrounded by water." },
  { word: "Pizza", translation: "Dish", pronunciation: "PEE-tsuh", ipaUS: "/ ˈpiːtsə /", ipaUK: "/ ˈpiːtsə /", meaning: "A dish of Italian origin consisting of a flat, round base of dough baked with a topping." },
  { word: "Queue", translation: "Line", pronunciation: "kyoo", ipaUS: "/ ˈkjuː /", ipaUK: "/ kjuː /", meaning: "A line or sequence of people or vehicles awaiting their turn." },
  { word: "Rhythm", translation: "Beat", pronunciation: "RITH-uhm", ipaUS: "/ ˈrɪðəm /", ipaUK: "/ ˈrɪðəm /", meaning: "A strong, regular, repeated pattern of movement or sound." },
  { word: "Salmon", translation: "Fish", pronunciation: "sam-un", ipaUS: "/ ˈsæmən /", ipaUK: "/ ˈsæmən /", meaning: "A large edible fish that is a popular food." },
  { word: "Subtle", pronunciation: "SUHT-l", translation: "Delicate", ipaUS: "/ ˈsʌtl̩ /", ipaUK: "/ ˈsʌtl /", meaning: "(Especially of a change or distinction) so delicate or precise as to be difficult to analyze or describe." }
];

