
export interface ComplexWord {
  word: string;
  translation: string;
  pronunciation: string;
  ipa: string;
  meaning: string;
}

export const COMPLEX_WORDS: ComplexWord[] = [
  { word: "Aberrant", translation: "Aberrante", pronunciation: "uh-BER-uhnt", ipa: "/ æˈberənt /", meaning: "Desviación de la norma o comportamiento típico." },
  { word: "Accede", translation: "Acceder a", pronunciation: "uhk-seed", ipa: "/ əkˈsiːd /", meaning: "Consentir, dar su aprobación; ceder a los deseos de otro." },
  { word: "Accessory", translation: "Accesorio", pronunciation: "uhk-ses-uh-ree", ipa: "/ əkˈsesəri /", meaning: "Pequeña cosa que se lleva con la ropa para añadir estilo." },
  { word: "Adamant", translation: "Inflexible", pronunciation: "AD-uh-muhnt", ipa: "/ ˈædəmənt /", meaning: "Negarse firmemente a cambiar de opinión." },
  { word: "Adumbrate", translation: "Adumbrate", pronunciation: "ad-UHM-breyt", ipa: "/ ˈædəmbreɪt /", meaning: "Dar un esquema vago o esquemático." },
  { word: "Agoraphobia", translation: "Agorafobia", pronunciation: "uh-gaw-ruh-foh-bee-uh", ipa: "/ ˌæɡərəˈfəʊbiə /", meaning: "Miedo a lugares o situaciones de los que no se puede escapar." },
  { word: "Albeit", translation: "Aunque", pronunciation: "all-BEE-it", ipa: "/ ɒlˈbiːət /", meaning: "A pesar de ello." },
  { word: "Alias", translation: "Alias", pronunciation: "ay-lee-uhs", ipa: "/ ˈeɪliəs /", meaning: "Nombre falso adoptado temporalmente." },
  { word: "Almond", translation: "Almendra", pronunciation: "AL-muhnd", ipa: "/ ˈɑːmənd /", meaning: "Una pequeña, ovalada." },
  { word: "Anathema", translation: "Anatema", pronunciation: "uh-nath-uh-muh", ipa: "/ əˈnæθəmə /", meaning: "Algo o alguien que a uno le desagrada vehementemente." },
  { word: "Anemone", translation: "Anémona", pronunciation: "uh-nem-uh-nee", ipa: "/ əˈneməni /", meaning: "Planta pequeña." },
  { word: "Anesthetist", translation: "Anestesista", pronunciation: "uh-neth-uh-tist", ipa: "/ əˈniːsθətɪst /", meaning: "Un médico anestesista." },
  { word: "Aneurysm", translation: "Aneurisma", pronunciation: "uh-nur-izm", ipa: "/ ˈænjəˌrɪzəm /", meaning: "Inflamación excesiva localizada de la pared de una arteria." },
  { word: "Antarctic", translation: "Antártida", pronunciation: "hormiguero-tik", ipa: "/ ænˈtɑːktɪk /", meaning: "Región extremadamente fría del sur del mundo." },
  { word: "Anthropomorphism", translation: "Antropomorfismo", pronunciation: "an-thruh-puh-mawr-fiz-uhm", ipa: "/ ˌænθrəʊpəʊˈmɔːfˌɪzəm /", meaning: "Atribución de características humanas a objetos." },
  { word: "Antidisestablishmentarianism", translation: "Antisistema", pronunciation: "an-teye-dis-es-tab-lish-muhnt-air-ee-uh-niz-uhm", ipa: "/ ˌæntidɪsəˌstæbləʃmənˈteriənɪzəm /", meaning: "Oposición a la desestructuración de la Iglesia." },
  { word: "Apocryphal", translation: "Apócrifo", pronunciation: "uh-PAHK-ruh-fuhl", ipa: "/ əˈpɑːkrəfl̩ /", meaning: "De autenticidad dudosa." },
  { word: "Archetype", translation: "Arquetipo", pronunciation: "AHR-kih-t", ipa: "/ ˈɑːrkəˌtaɪp /", meaning: "Un ejemplo muy típico de algo." },
  { word: "Archipelago", translation: "Archipiélago", pronunciation: "AHR-kih-pel-uh-goh", ipa: "/ ˌɑːrkəˈpeləˌɡoʊ /", meaning: "Un grupo de islas." },
  { word: "Ascetic", translation: "Asceta", pronunciation: "ass-et-ick", ipa: "/ əsetɪk /", meaning: "Persona que practica una autodisciplina extrema." },
  { word: "Asterisk", translation: "Asterisco", pronunciation: "ay-stuh-riesgo", ipa: "/ ˈæstərɪsk /", meaning: "El símbolo: *" },
  { word: "Athlete", translation: "Atleta", pronunciation: "ATH-leet", ipa: "/ ˈæθˌlit /", meaning: "Persona experta en deportes." },
  { word: "Bacteriology", translation: "Bacteriología", pronunciation: "bak-teer-ee-awl-uh-jee", ipa: "/ bækˌtɪəriˈɒlədʒi /", meaning: "El estudio de las bacterias." },
  { word: "Beguile", translation: "Seducir", pronunciation: "abeja-gyle", ipa: "/ bɪˈɡaɪl /", meaning: "Engañar o engañar a alguien." },
  { word: "Blasphemy", translation: "Blasfemia", pronunciation: "blas-fuh-mee", ipa: "/ ˈblæsfəmi /", meaning: "Hablar sacrílegamente de las cosas sagradas." },
  { word: "Bouquet", translation: "Ramo", pronunciation: "boo-KAY", ipa: "/ buːˈkeɪ /", meaning: "Un ramo de flores." },
  { word: "Bourbon", translation: "Bourbon", pronunciation: "BER-buhn", ipa: "/ ˈbɝːbən /", meaning: "Tipo de whisky elaborado con maíz." },
  { word: "Brewery", translation: "Cervecería", pronunciation: "BREW-uh-ree", ipa: "/ ˈbruːəri /", meaning: "Un lugar donde se produce cerveza." },
  { word: "Broccoli", translation: "Brócoli", pronunciation: "BROK-uh-lee", ipa: "/ ˈbrɑːkəli /", meaning: "Hortaliza verde con forma de árbol." },
  { word: "Buoy", translation: "Boya", pronunciation: "chico", ipa: "/ ˈbuːi /", meaning: "Dispositivo flotante para navegación." },
  { word: "Bureaucracy", translation: "Burocracia", pronunciation: "byoo-rok-ruh-see", ipa: "/ bjʊəˈrɒkrəsi /", meaning: "Procedimientos administrativos complejos." },
  { word: "Bury", translation: "Enterrar", pronunciation: "BER-ee", ipa: "/ ˈberi /", meaning: "Colocar bajo tierra." },
  { word: "Cacciatore", translation: "Cacciatore", pronunciation: "kuh-chuh-tawr-ee", ipa: "/ katʃəˈtɔːi /", meaning: "Salsa de tomate picante con champiñones." },
  { word: "Cache", translation: "Caché", pronunciation: "kash", ipa: "/ ˈkæʃ /", meaning: "Un escondite para guardar mercancías." },
  { word: "Cacophony", translation: "Cacofonía", pronunciation: "kuh-kof-uh-nee", ipa: "/ kæˈkɒfəni /", meaning: "Mezcla desagradable de sonidos." },
  { word: "Cajole", translation: "Engatusar", pronunciation: "kuh-johl", ipa: "/ kəˈdʒoʊl /", meaning: "Persuadir siendo muy amable." },
  { word: "Callous", translation: "Insensible", pronunciation: "kal-us", ipa: "/ ˈkæləs /", meaning: "No mostrar emoción o simpatía." },
  { word: "Camaraderie", translation: "Camaradería", pronunciation: "kam-ruh-duh-ree", ipa: "/ ˌkæməˈrɑːdəri /", meaning: "Familiaridad y amistad fáciles." },
  { word: "Candidate", translation: "Candidato", pronunciation: "KAND-uh-deyt", ipa: "/ ˈkændədet /", meaning: "Persona que aspira a un cargo." },
  { word: "Caramel", translation: "Caramelo", pronunciation: "kar-uh-mel", ipa: "/ ˈkerəməl /", meaning: "Dulce marrón elaborado con azúcar." },
  { word: "Caricature", translation: "Caricatura", pronunciation: "kuh-RIK-uh-cher", ipa: "/ ˈkerəkətʃər /", meaning: "Representación que exagera rasgos." },
  { word: "Cavalry", translation: "Caballería", pronunciation: "KAV-uhl-ree", ipa: "/ ˈkævəlri /", meaning: "Soldados entrenados a caballo." },
  { word: "Chaos", translation: "Caos", pronunciation: "KAY-ahs", ipa: "/ ˈkeɪas /", meaning: "Completo desorden y confusión." },
  { word: "Charcuterie", translation: "Charcutería", pronunciation: "shahr-koo-tuh-REE", ipa: "/ ˌʃɑːrˈkuːtəri /", meaning: "Productos cárnicos preparados." },
  { word: "Chauvinism", translation: "Chauvinismo", pronunciation: "shoh-vuh-niz-uhm", ipa: "/ ˈʃoʊvɪnɪzəm /", meaning: "Patriotismo excesivo." },
  { word: "Chimpanzee", translation: "Chimpancé", pronunciation: "chimp-uhn-zee", ipa: "/ ˌtʃɪmpænˈziː /", meaning: "Un tipo de simio." },
  { word: "Chipotle", translation: "Chipotle", pronunciation: "chi-poat-lee", ipa: "/tʃɪˈpɒtleɪ/", meaning: "Guindilla ahumada y seca." },
  { word: "Choir", translation: "Coro", pronunciation: "kwahy-er", ipa: "/ ˈkwaɪər /", meaning: "Grupo de cantantes." },
  { word: "Clothes", translation: "Ropa", pronunciation: "klohz", ipa: "/ kloʊðz /", meaning: "Prendas de vestir." },
  { word: "Cocoa", translation: "Cacao", pronunciation: "koh-KOH", ipa: "/ ˈkokoʊ /", meaning: "Polvo de granos de cacao." },
  { word: "Colonel", translation: "Coronel", pronunciation: "ker-nuhl", ipa: "/ ˈkɜːnl̩ /", meaning: "Oficial de alto rango." },
  { word: "Comfortable", translation: "Cómodo", pronunciation: "kum-fuhr-tuh-buhl", ipa: "/ ˈkʌmftəbl̩ /", meaning: "Me siento relajado." },
  { word: "Coup", translation: "Golpe de Estado", pronunciation: "koo", ipa: "/ ˈkuː /", meaning: "Toma de poder repentina." },
  { word: "Data", translation: "Datos", pronunciation: "día-tuh", ipa: "/ ˈdeɪtə /", meaning: "Información para cálculos." },
  { word: "Debris", translation: "Escombros", pronunciation: "DEB-ree", ipa: "/ dəˈbriː /", meaning: "Restos de algo destruido." },
  { word: "Debut", translation: "Debut", pronunciation: "dey-BYOO", ipa: "/ ˈdeɪbjuː /", meaning: "Primera representación pública." },
  { word: "February", translation: "Febrero", pronunciation: "feb-roo-air-ee", ipa: "/ ˈfebjʊəri /", meaning: "Segundo mes del año." },
  { word: "GIF", translation: "GIF", pronunciation: "jif", ipa: "/ gif /", meaning: "Tipo de imagen animada." },
  { word: "Hierarchy", translation: "Jerarquía", pronunciation: "HAHY-er-ahr-kee", ipa: "/ ˈhaɪəˌrɑːrki /", meaning: "Sistema de rangos." },
  { word: "Island", translation: "Isla", pronunciation: "AYL-land", ipa: "/ ˈaɪlənd /", meaning: "Tierra rodeada de agua." },
  { word: "Pizza", translation: "Pizza", pronunciation: "PEE-tsuh", ipa: "/ ˈpiːtsə /", meaning: "Plato italiano." },
  { word: "Queue", translation: "Cola", pronunciation: "kyoo", ipa: "/ ˈkjuː /", meaning: "Fila de personas." },
  { word: "Rhythm", translation: "Ritmo", pronunciation: "RITH-uhm", ipa: "/ ˈrɪðəm /", meaning: "Patrón de sonidos." },
  { word: "Salmon", translation: "Salmón", pronunciation: "sam-un", ipa: "/ ˈsæmən /", meaning: "Tipo de pescado." },
  { word: "Subtle", pronunciation: "suht-l", ipa: "/ ˈsʌtl̩ /", translation: "Sutil", meaning: "Preciso y difícil de describir." }
];
