export interface IdiomExpression {
  idioms_expressions_id: number;
  idiom_expression_in_english: string;
  idiom_expression_in_spanish: string;
}

export const IDIOMS_EXPRESSIONS: IdiomExpression[] = [
  { idioms_expressions_id: 1, idiom_expression_in_english: "Piece of cake", idiom_expression_in_spanish: "Pan comido" },
  { idioms_expressions_id: 2, idiom_expression_in_english: "Break a leg", idiom_expression_in_spanish: "Buena suerte" },
  { idioms_expressions_id: 3, idiom_expression_in_english: "Under the weather", idiom_expression_in_spanish: "Sentirse mal / Indispuesto" },
  { idioms_expressions_id: 4, idiom_expression_in_english: "Bite the bullet", idiom_expression_in_spanish: "Hacer de tripas corazón" },
  { idioms_expressions_id: 5, idiom_expression_in_english: "Better late than never", idiom_expression_in_spanish: "Más vale tarde que nunca" },
  { idioms_expressions_id: 6, idiom_expression_in_english: "Call it a day", idiom_expression_in_spanish: "Dar algo por terminado" },
  { idioms_expressions_id: 7, idiom_expression_in_english: "Cut corners", idiom_expression_in_spanish: "Escatimar / Ahorrar de mala manera" },
  { idioms_expressions_id: 8, idiom_expression_in_english: "Get out of hand", idiom_expression_in_spanish: "Irse de las manos" },
  { idioms_expressions_id: 9, idiom_expression_in_english: "Hang in there", idiom_expression_in_spanish: "Aguantar / No rendirse" },
  { idioms_expressions_id: 10, idiom_expression_in_english: "Hit the sack", idiom_expression_in_spanish: "Irse a dormir" },
  { idioms_expressions_id: 11, idiom_expression_in_english: "Let someone off the hook", idiom_expression_in_spanish: "Dejar a alguien libre de culpa" },
  { idioms_expressions_id: 12, idiom_expression_in_english: "No pain, no gain", idiom_expression_in_spanish: "Sin esfuerzo no hay recompensa" },
  { idioms_expressions_id: 13, idiom_expression_in_english: "On the ball", idiom_expression_in_spanish: "Estar alerta / Estar al tanto" },
  { idioms_expressions_id: 14, idiom_expression_in_english: "Pull someone's leg", idiom_expression_in_spanish: "Tomar el pelo" },
  { idioms_expressions_id: 15, idiom_expression_in_english: "So far so good", idiom_expression_in_spanish: "Hasta ahora todo bien" },
  { idioms_expressions_id: 16, idiom_expression_in_english: "Speak of the devil", idiom_expression_in_spanish: "Hablando del rey de Roma" },
  { idioms_expressions_id: 17, idiom_expression_in_english: "That's the last straw", idiom_expression_in_spanish: "Esa es la gota que colmó el vaso" },
  { idioms_expressions_id: 18, idiom_expression_in_english: "The best of both worlds", idiom_expression_in_spanish: "Lo mejor de ambos mundos" },
  { idioms_expressions_id: 19, idiom_expression_in_english: "Time flies", idiom_expression_in_spanish: "El tiempo vuela" },
  { idioms_expressions_id: 20, idiom_expression_in_english: "To make matters worse", idiom_expression_in_spanish: "Para empeorar las cosas" },
  { idioms_expressions_id: 21, idiom_expression_in_english: "Under the weather", idiom_expression_in_spanish: "Un poco enfermo" },
  { idioms_expressions_id: 22, idiom_expression_in_english: "Wrap your head around something", idiom_expression_in_spanish: "Entender algo complejo" },
  { idioms_expressions_id: 23, idiom_expression_in_english: "You can say that again", idiom_expression_in_spanish: "Tienes toda la razón" },
  { idioms_expressions_id: 24, idiom_expression_in_english: "Beat around the bush", idiom_expression_in_spanish: "Andarse con rodeos" },
  { idioms_expressions_id: 25, idiom_expression_in_english: "Break the ice", idiom_expression_in_spanish: "Romper el hielo" },
  { idioms_expressions_id: 26, idiom_expression_in_english: "By the skin of your teeth", idiom_expression_in_spanish: "Por los pelos" },
  { idioms_expressions_id: 27, idiom_expression_in_english: "Cost an arm and a leg", idiom_expression_in_spanish: "Costar un ojo de la cara" },
  { idioms_expressions_id: 28, idiom_expression_in_english: "Cutting corners", idiom_expression_in_spanish: "Hacer las cosas rápido y mal" },
  { idioms_expressions_id: 29, idiom_expression_in_english: "Easy does it", idiom_expression_in_spanish: "Con cuidado / Despacio" },
  { idioms_expressions_id: 30, idiom_expression_in_english: "Get your act together", idiom_expression_in_spanish: "Ponerse las pilas" },
  { idioms_expressions_id: 31, idiom_expression_in_english: "Give someone the benefit of the doubt", idiom_expression_in_spanish: "Dar el beneficio de la duda" },
  { idioms_expressions_id: 32, idiom_expression_in_english: "Go back to the drawing board", idiom_expression_in_spanish: "Empezar de cero" },
  { idioms_expressions_id: 33, idiom_expression_in_english: "It's not rocket science", idiom_expression_in_spanish: "No es tan difícil" },
  { idioms_expressions_id: 34, idiom_expression_in_english: "Let the cat out of the bag", idiom_expression_in_spanish: "Revelar un secreto" },
  { idioms_expressions_id: 35, idiom_expression_in_english: "Make a long story short", idiom_expression_in_spanish: "En resumen" },
  { idioms_expressions_id: 36, idiom_expression_in_english: "Miss the boat", idiom_expression_in_spanish: "Perder la oportunidad" },
  { idioms_expressions_id: 37, idiom_expression_in_english: "Once in a blue moon", idiom_expression_in_spanish: "Muy de vez en cuando" },
  { idioms_expressions_id: 38, idiom_expression_in_english: "Pull yourself together", idiom_expression_in_spanish: "Cálmate / Recomponte" },
  { idioms_expressions_id: 39, idiom_expression_in_english: "Sit on the fence", idiom_expression_in_spanish: "No tomar partido" },
  { idioms_expressions_id: 40, idiom_expression_in_english: "The elephant in the room", idiom_expression_in_spanish: "Un problema obvio que nadie menciona" },
  { idioms_expressions_id: 41, idiom_expression_in_english: "To get bent out of shape", idiom_expression_in_spanish: "Enojarse o molestarse" },
  { idioms_expressions_id: 42, idiom_expression_in_english: "To hit the nail on the head", idiom_expression_in_spanish: "Dar en el clavo" },
  { idioms_expressions_id: 43, idiom_expression_in_english: "To kill two birds with one stone", idiom_expression_in_spanish: "Matar dos pájaros de un tiro" },
  { idioms_expressions_id: 44, idiom_expression_in_english: "To leave no stone unturned", idiom_expression_in_spanish: "No dejar piedra por mover" },
  { idioms_expressions_id: 45, idiom_expression_in_english: "To see eye to eye", idiom_expression_in_spanish: "Estar de acuerdo" },
  { idioms_expressions_id: 46, idiom_expression_in_english: "To spill the beans", idiom_expression_in_spanish: "Irse de la lengua" },
  { idioms_expressions_id: 47, idiom_expression_in_english: "A blessing in disguise", idiom_expression_in_spanish: "No hay mal que por bien no venga" },
  { idioms_expressions_id: 48, idiom_expression_in_english: "A dime a dozen", idiom_expression_in_spanish: "Algo muy común y barato" },
  { idioms_expressions_id: 49, idiom_expression_in_english: "Add insult to injury", idiom_expression_in_spanish: "Echar sal a la herida" },
  { idioms_expressions_id: 50, idiom_expression_in_english: "Beat a dead horse", idiom_expression_in_spanish: "Perder el tiempo en algo inútil" },
  { idioms_expressions_id: 51, idiom_expression_in_english: "Bite off more than you can chew", idiom_expression_in_spanish: "Abarcar más de lo que se puede apretar" },
  { idioms_expressions_id: 52, idiom_expression_in_english: "Burn bridges", idiom_expression_in_spanish: "Quemar naves / Romper relaciones" },
  { idioms_expressions_id: 53, idiom_expression_in_english: "Don't count your chickens before they hatch", idiom_expression_in_spanish: "No cantes victoria antes de tiempo" },
  { idioms_expressions_id: 54, idiom_expression_in_english: "Don't cry over spilled milk", idiom_expression_in_spanish: "A lo hecho, pecho" },
  { idioms_expressions_id: 55, idiom_expression_in_english: "Don't give up the day job", idiom_expression_in_spanish: "No te dediques a eso (ironía)" },
  { idioms_expressions_id: 56, idiom_expression_in_english: "Don't put all your eggs in one basket", idiom_expression_in_spanish: "No te lo juegues todo a una carta" },
  { idioms_expressions_id: 57, idiom_expression_in_english: "Every cloud has a silver lining", idiom_expression_in_spanish: "Siempre hay un lado positivo" },
  { idioms_expressions_id: 58, idiom_expression_in_english: "Get a taste of your own medicine", idiom_expression_in_spanish: "Probar tu propia medicina" },
  { idioms_expressions_id: 59, idiom_expression_in_english: "Give someone the cold shoulder", idiom_expression_in_spanish: "Hacer el vacío a alguien" },
  { idioms_expressions_id: 60, idiom_expression_in_english: "Go on a wild goose chase", idiom_expression_in_spanish: "Buscar una aguja en un pajar" },
  { idioms_expressions_id: 61, idiom_expression_in_english: "Heard it through the grapevine", idiom_expression_in_spanish: "Me lo ha dicho un pajarito" },
  { idioms_expressions_id: 62, idiom_expression_in_english: "Hit the books", idiom_expression_in_spanish: "Hinchar los codos / Estudiar" },
  { idioms_expressions_id: 63, idiom_expression_in_english: "Keep your chin up", idiom_expression_in_spanish: "Mantener la cabeza alta" },
  { idioms_expressions_id: 64, idiom_expression_in_english: "Kill two birds with one stone", idiom_expression_in_spanish: "Matar dos pájaros de un tiro" },
  { idioms_expressions_id: 65, idiom_expression_in_english: "Method to my madness", idiom_expression_in_spanish: "Tener un plan dentro del caos" },
  { idioms_expressions_id: 66, idiom_expression_in_english: "Off the top of my head", idiom_expression_in_spanish: "Así de memoria" },
  { idioms_expressions_id: 67, idiom_expression_in_english: "Piece of cake", idiom_expression_in_spanish: "Pan comido" },
  { idioms_expressions_id: 68, idiom_expression_in_english: "Rain on someone's parade", idiom_expression_in_spanish: "Aguar la fiesta a alguien" },
  { idioms_expressions_id: 69, idiom_expression_in_english: "Steal someone's thunder", idiom_expression_in_spanish: "Quitarle el protagonismo a alguien" },
  { idioms_expressions_id: 70, idiom_expression_in_english: "Straight from the horse's mouth", idiom_expression_in_spanish: "De buena tinta / De primera mano" },
  { idioms_expressions_id: 71, idiom_expression_in_english: "Take it with a grain of salt", idiom_expression_in_spanish: "Coger algo con pinzas" },
  { idioms_expressions_id: 72, idiom_expression_in_english: "The ball is in your court", idiom_expression_in_spanish: "La pelota está en tu tejado" },
  { idioms_expressions_id: 73, idiom_expression_in_english: "The whole nine yards", idiom_expression_in_spanish: "Hasta el final / Por completo" },
  { idioms_expressions_id: 74, idiom_expression_in_english: "Through thick and thin", idiom_expression_in_spanish: "En las buenas y en las malas" },
  { idioms_expressions_id: 75, idiom_expression_in_english: "To play devil's advocate", idiom_expression_in_spanish: "Hacer de abogado del diablo" },
  { idioms_expressions_id: 76, idiom_expression_in_english: "To sit tight", idiom_expression_in_spanish: "Esperar pacientemente" },
  { idioms_expressions_id: 77, idiom_expression_in_english: "To throw under the bus", idiom_expression_in_spanish: "Traicionar a alguien" },
  { idioms_expressions_id: 78, idiom_expression_in_english: "Under the weather", idiom_expression_in_spanish: "Estar un poco pachucho" },
  { idioms_expressions_id: 79, idiom_expression_in_english: "Up in the air", idiom_expression_in_spanish: "Estar en el aire / Sin decidir" },
  { idioms_expressions_id: 80, idiom_expression_in_english: "When pigs fly", idiom_expression_in_spanish: "Cuando las ranas críen pelo" },
  { idioms_expressions_id: 81, idiom_expression_in_english: "Your guess is as good as mine", idiom_expression_in_spanish: "Ni idea / Sé tanto como tú" },
  { idioms_expressions_id: 82, idiom_expression_in_english: "Barking up the wrong tree", idiom_expression_in_spanish: "Estar equivocado / Seguir la pista falsa" },
  { idioms_expressions_id: 83, idiom_expression_in_english: "Beat around the bush", idiom_expression_in_spanish: "Andarse por las ramas" },
  { idioms_expressions_id: 84, idiom_expression_in_english: "Best thing since sliced bread", idiom_expression_in_spanish: "Lo mejor que se ha inventado" },
  { idioms_expressions_id: 85, idiom_expression_in_english: "Blessing in disguise", idiom_expression_in_spanish: "No hay mal que por bien no venga" },
  { idioms_expressions_id: 86, idiom_expression_in_english: "Burn the midnight oil", idiom_expression_in_spanish: "Quedarse hasta las tantas estudiando" },
  { idioms_expressions_id: 87, idiom_expression_in_english: "Don't judge a book by its cover", idiom_expression_in_spanish: "No juzgues por las apariencias" },
  { idioms_expressions_id: 88, idiom_expression_in_english: "Fit as a fiddle", idiom_expression_in_spanish: "Sano como una manzana" },
  { idioms_expressions_id: 89, idiom_expression_in_english: "Go the extra mile", idiom_expression_in_spanish: "Esforzarse un poco más" },
  { idioms_expressions_id: 90, idiom_expression_in_english: "Jump on the bandwagon", idiom_expression_in_spanish: "Subirse al carro" },
  { idioms_expressions_id: 91, idiom_expression_in_english: "Keep something at bay", idiom_expression_in_spanish: "Mantener algo a raya" },
  { idioms_expressions_id: 92, idiom_expression_in_english: "Leave someone in the lurch", idiom_expression_in_spanish: "Dejar a alguien en la estacada" },
  { idioms_expressions_id: 93, idiom_expression_in_english: "Let bygones be bygones", idiom_expression_in_spanish: "Lo pasado, pasado está" },
  { idioms_expressions_id: 94, idiom_expression_in_english: "Live and learn", idiom_expression_in_spanish: "Vivir para aprender" },
  { idioms_expressions_id: 95, idiom_expression_in_english: "Look before you leap", idiom_expression_in_spanish: "Míratelo bien antes de actuar" },
  { idioms_expressions_id: 96, idiom_expression_in_english: "Make a mountain out of a molehill", idiom_expression_in_spanish: "Hacer una montaña de un grano de arena" },
  { idioms_expressions_id: 97, idiom_expression_in_english: "On cloud nine", idiom_expression_in_spanish: "Estar en el séptimo cielo" },
  { idioms_expressions_id: 98, idiom_expression_in_english: "Spill the beans", idiom_expression_in_spanish: "Contar el secreto" },
  { idioms_expressions_id: 99, idiom_expression_in_english: "The icing on the cake", idiom_expression_in_spanish: "La guinda del pastel" },
  { idioms_expressions_id: 100, idiom_expression_in_english: "To blow off steam", idiom_expression_in_spanish: "Desahogarse" }
];
