export interface RegularVerb {
  id: number;
  infinitive: string;
  pronunciation: string;
  past: string;
  pastParticiple: string;
  example: string;
  spanish: string;
}

export const REGULAR_VERBS_RAW = `Accept;/əkˈsɛpt/;Accepted;Accepted;Accept the invitation;Aceptar;
Achieve;/əˈtʃiːv/;Achieved;Achieved;Achieve your goal;Lograr;
Acknowledge;/əkˈnɑːlɪdʒ/;Acknowledged;Acknowledged;Acknowledge the mistake;Reconocer;
Acquire;/əˈkwaɪər/;Acquired;Acquired;Acquire new skills;Adquirir;
Act;/ækt/;Acted;Acted;Act quickly;Actuar;
Add;/æd/;Added;Added;Add sugar to tea;Añadir;
Admire;/ədˈmaɪr/;Admired;Admired;Admire the view;Admirar;
Admit;/ədˈmɪt/;Admitted;Admitted;Admit the error;Admitir;
Adopt;/əˈdɑːpt/;Adopted;Adopted;Adopt a puppy;Adoptar;
Adore;/əˈdɔːr/;Adored;Adored;Adore your grandparents;Adorar;
Advise;/ədˈvaɪz/;Advised;Advised;Advise the client;Aconsejar;
Afford;/əˈfɔːrd/;Afforded;Afforded;Afford a new car;Permitir;
Aim;/eɪm/;Aimed;Aimed;Aim at the target;Apuntar;
Alarm;/əˈlɑːrm/;Alarmed;Alarmed;Alarm the staff;Alarmar;
Alert;/əˈlɜːrt/;Alerted;Alerted;Alert the authorities;Alertar;
Allow;/əˈlaʊ/;Allowed;Allowed;Allow entry;Permitir;
Amaze;/əˈmeɪz/;Amazed;Amazed;Amaze the audience;Asombrar;
Amend;/əˈmɛnd/;Amended;Amended;Amend the contract;Enmendar;
Analyze;/ˈænəlaɪz/;Analyzed;Analyzed;Analyze the data;Analizar;
Announce;/əˈnaʊns/;Announced;Announced;Announce the news;Anunciar;
Annoy;/əˈnɔɪ/;Annoyed;Annoyed;Annoy the cat;Molestar;
Answer;/ˈænsər/;Answered;Answered;Answer the phone;Responder;
Apologize;/əˈpɑːlədʒaɪz/;Apologized;Apologized;Apologize for the delay;Disculparse;
Appear;/əˈpɪr/;Appeared;Appeared;Appear on stage;Aparecer;
Appreciate;/əˈpriːʃieɪt/;Appreciated;Appreciated;Appreciate the help;Agradecer;
Approach;/əˈproʊtʃ/;Approached;Approached;Approach the problem;Abordar;
Approve;/əˈpruv/;Approved;Approved;Approve the plan;Aprobar;
Argue;/ˈɑːrɡjuː/;Argued;Argued;Argue a point;Discutir;
Arrange;/əˈreɪndʒ/;Arranged;Arranged;Arrange a meeting;Organizar;
Arrest;/əˈrɛst/;Arrested;Arrested;Arrest the suspect;Arrestar;
Arrive;/əˈraɪv/;Arrived;Arrived;Arrive on time;Llegar;
Ask;/æsk/;Asked;Asked;Ask a question;Preguntar;
Assume;/əˈsuːm/;Assumed;Assumed;Assume responsibility;Asumir;
Assure;/əˈʃʊr/;Assured;Assured;Assure the client;Asegurar;
Attach;/əˈtætʃ/;Attached;Attached;Attach the file;Adjuntar;
Attempt;/əˈtɛmpt/;Attempted;Attempted;Attempt the jump;Intentar;
Attend;/əˈtɛnd/;Attended;Attended;Attend the concert;Asistir;
Attract;/əˈtrækt/;Attracted;Attracted;Attract customers;Atraer;
Avoid;/əˈvɔɪ/;Avoided;Avoided;Avoid the mistake;Evitar;
Bake;/beɪk/;Baked;Baked;Bake a cake;Hornear;
Balance;/ˈbæl.əns/;Balanced;Balanced;Balance the budget;Equilibrar;
Ban;/bæn/;Banned;Banned;Ban the entry;Prohibir;
Bathe;/beɪð/;Bathed;Bathed;Bathe the baby;Bañar;
Beautify;/ˈbjuːtəfaɪ/;Beautified;Beautified;Beautify the garden;Embellecer;
Behave;/bɪˈheɪv/;Behaved;Behaved;Behave yourself;Comportarse;
Believe;/bɪˈliːv/;Believed;Believed;Believe in yourself;Creer;
Belong;/bɪˈlɔːŋ/;Belonged;Belonged;Belong to the team;Pertenecer;
Benefit;/ˈbɛnɪfɪt/;Benefited;Benefited;Benefit from the program;Beneficiar;
Betray;/bɪˈtreɪ/;Betrayed;Betrayed;Betray a trust;Traicionar;
Bloom;/blum/;Bloomed;Bloomed;Bloom in spring;Florecer;
Boil;/bɔɪl/;Boiled;Boiled;Boil the water;Hervir;
Bother;/ˈbɑːðər/;Bothered;Bothered;Bother the neighbor;Molestar;
Bounce;/baʊns/;Bounced;Bounced;Bounce the ball;Rebotar;
Brag;/bræɡ/;Bragged;Bragged;Brag about success;Presumir;
Brake;/breɪk/;Braked;Braked;Brake gently;Frenar;
Breathe;/briːð/;Breathed;Breathed;Breathe deeply;Respirar;
Brighten;/ˈbraɪtn/;Brightened;Brightened;Brighten the room;Iluminar;
Brief;/briːf/;Briefed;Briefed;Brief the team;Informar;
Brush;/brʌʃ/;Brushed;Burushed;Brush the teeth;Cepillar;
Bump;/bʌmp/;Bumped;Bumped;Bump into a wall;Chocar;
Calculate;/ˈkælkjʊleɪt/;Calculated;Calculated;Calculate the sum;Calcular;
Call;/kɔːl/;Called;Called;Call a friend;Llamar;
Calm;/kɑːm/;Calmed;Calmed;Calm the child;Calmar;
Campaign;/kæmˈpeɪn/;Campaigned;Campaigned;Campaign for change;Campañear;
Cancel;/ˈkænsəl/;Canceled;Canceled;Cancel the appointment;Cancelar;
Capture;/ˈkæptʃɚ/;Captured;Captured;Capture the moment;Capturar;
Care;/keər/;Cared;Cared;Care for the plants;Cuidar;
Carry;/ˈkæri/;Carried;Carried;Carry the bags;Transportar;
Carve;/kɑːrv/;Carved;Carved;Carve the pumpkin;Tallado;
Cash;/kæʃ/;Cashed;Cashed;Cash the check;Cobrar;
Cause;/kɔːz/;Caused;Caused;Cause a delay;Causar;
Celebrate;/ˈsɛlɪbreɪt/;Celebrated;Celebrated;Celebrate victory;Celebrar;
Center;/ˈsɛntɚ/;Centered;Centered;Center the image;Centrar;
Certify;/ˈsɝtəfaɪ/;Certified;Certified;Certify the document;Certificar;
Challenge;/ˈtʃælɪndʒ/;Challenged;Challenged;Challenge the idea;Desafiar;
Change;/tʃeɪndʒ/;Changed;Changed;Change the tire;Cambiar;
Charge;/tʃɑːrdʒ/;Charged;Charged;Charge the battery;Cargar;
Chase;/tʃeɪs/;Chased;Chased;Chase the cat;Perseguir;
Cheat;/tʃiːt/;Cheated;Cheated;Cheat on the test;Engañar;
Check;/tʃɛk/;Checked;Checked;Check the email;Revisar;
Cheer;/tʃɪər/;Cheered;Cheered;Cheer the team;Animar;
Chew;/tʃuː/;Chewed;Chewed;Chew gum;Masticar;
Chill;/tʃɪl/;Chilled;Chilled;Chill the drink;Enfriar;
Chuck;/tʃʌk/;Chucked;Chucked;Chuck the rope;Tirar;
Circulate;/ˈsɝkjəleɪt/;Circulated;Circulated;Circulate the flyer;Distribuir;
Claim;/kleɪm/;Claimed;Claimed;Claim the prize;Reclamar;
Clap;/klæp/;Clapped;Clapped;Clap your hands;Aplaudir;
Clarify;/ˈklærɪfaɪ/;Clarified;Clarified;Clarify the rules;Aclarar;
Classify;/ˈklæsɪfaɪ/;Classified;Classified;Classify the items;Clasificar;
Clean;/kliːn/;Cleaned;Cleaned;Clean the room;Limpiar;
Clear;/klɪr/;Cleared;Cleared;Clear the table;Despejar;
Click;/klɪk/;Clicked;Clicked;Click the link;Clicar;
Climb;/klaɪm/;Climbed;Climbed;Climb the hill;Escalar;
Close;/kloʊz/;Closed;Closed;Close the door;Cerrar;
Coach;/koʊtʃ/;Coached;Coached;Coach the team;Entrenar;
Code;/koʊd/;Coded;Coded;Code the app;Programar;
Collect;/kəˈlɛkt/;Collected;Collected;Collect the stamps;Recoger;
Combine;/kəmˈbaɪn/;Combined;Combined;Combine the ingredients;Combinar;
Comment;/ˈkɑːmənt/;Commented;Commented;Comment on the article;Comentar;
Compare;/kəmˈpɛr/;Compared;Compared;Compare the prices;Comparar;
Compete;/kəmˈpiːt/;Competed;Competed;Compete in the race;Competir;
Complain;/kəmˈpleɪn/;Complained;Complained;Complain about the noise;Quejarse;
Complete;/kəmˈpliːt/;Completed;Completed;Complete the task;Completar;
Concentrate;/ˈkɑːnsəntreɪt/;Concentrated;Concentrated;Concentrate on work;Concentrarse;
Concern;/kənˈsɜːrn/;Concerned;Concerned;Concern the public;Preocupar;
Confess;/kənˈfɛs/;Confessed;Confessed;Confess the truth;Confesar;
Confuse;/kənˈfjuːz/;Confused;Confused;Confuse the students;Confundir;
Connect;/kəˈnɛkt/;Connected;Connected;Connect the cables;Conectar;
Consider;/kənˈsɪdər/;Considered;Considered;Consider the options;Considerar;
Consist;/kənˈsɪst/;Consisted;Consisted;Consist of water;Consistir;
Contain;/kənˈteɪn/;Contained;Contained;Contain the spill;Contener;
Continue;/kənˈtɪnjuː/;Continued;Continued;Continue the story;Continuar;
Convince;/kənˈvɪns/;Convinced;Convinced;Convince the jury;Convencer;
Cook;/kʊk/;Cooked;Cooked;Cook dinner;Cocinar;
Copy;/ˈkɑːpi/;Copied;Copied;Copy the text;Copiar;
Correct;/kəˈrɛkt/;Corrected;Corrected;Correct the mistakes;Corregir;
Cough;/kɔːf/;Coughed;Coughed;Cough loudly;Toser;
Count;/kaʊnt/;Counted;Counted;Count the money;Contar;
Cover;/ˈkʌvər/;Covered;Covered;Cover the box;Cubrir;
Crack;/kræk/;Cracked;Cracked;Crack the code;Romper;
Crash;/kræʃ/;Crashed;Crashed;Crash the car;Chocar;
Crawl;/krɔːl/;Crawled;Crawled;Crawl on the floor;Gatear;
Create;/kriˈeɪt/;Created;Created;Create a masterpiece;Crear;
Cross;/krɔːs/;Crossed;Crossed;Cross the street;Cruzar;
Crush;/krʌʃ/;Crushed;Crushed;Crush the garlic;Aplastar;
Cry;/kraɪ/;Cried;Cried;Cry for help;Llorar;
Cure;/kjʊr/;Cured;Cured;Cure the disease;Curar;
Curl;/kɜːrl/;Curled;Curled;Curl the hair;Rizar;
Curve;/kɜːrv/;Curved;Curved;Curve the ball;Curvar;
Cycle;/ˈsaɪkəl/;Cycled;Cycled;Cycle to work;Andar en bicicleta;
Damage;/ˈdæmɪdʒ/;Damaged;Damaged;Damage the property;Dañar;
Dance;/dæns/;Danced;Danced;Dance all night;Bailar;
Dare;/dɛr/;Dared;Dared;Dare to dream;Atreverse;
Decay;/dɪˈkeɪ/;Decayed;Decayed;Decay over time;Descomponerse;
Deceive;/dɪˈsiːv/;Deceived;Deceived;Deceive the enemy;Engañar;
Decide;/dɪˈsaɪd/;Decided;Decided;Decide what to do;Decidir;
Decorate;/ˈdɛkəreɪt/;Decorated;Decorated;Decorate the tree;Decorar;
Delay;/dɪˈleɪ/;Delayed;Delayed;Delay the flight;Retrasar;
Delight;/dɪˈlaɪt/;Delighted;Delighted;Delight the kids;Deleitar;
Deliver;/dɪˈlɪvər/;Delivered;Delivered;Deliver the package;Entregar;
Demand;/dɪˈmænd/;Demanded;Demanded;Demand an answer;Exigir;
Depend;/dɪˈpɛnd/;Depended;Depended;Depend on you;Depender;
Describe;/dɪˈskraɪb/;Described;Described;Describe the scene;Describir;
Deserve;/dɪˈzɜːrv/;Deserved;Deserved;Deserve a reward;Merecer;
Destroy;/dɪˈstrɔɪ/;Destroyed;Destroyed;Destroy the building;Destruir;
Detect;/dɪˈtɛkt/;Detected;Detected;Detect a smell;Detectar;
Develop;/dɪˈvɛləp/;Developed;Developed;Develop a plan;Desarrollar;
Disagree;/ˌdɪsəˈɡriː/;Disagreed;Disagreed;Disagree with him;Discrepar;
Disappear;/ˌdɪsəˈpɪr/;Disappeared;Disappeared;Disappear quickly;Desaparecer;
Disapprove;/ˌdɪsəˈpruv/;Disapproved;Disapproved;Disapprove the action;Desaprobar;
Discover;/dɪˈskʌvər/;Discovered;Discovered;Discover a new place;Descubrir;
Discuss;/dɪˈskʌs/;Discussed;Discussed;Discuss the issue;Discutir;
Dislike;/dɪsˈlaɪk/;Disliked;Disliked;Dislike the taste;Desagradar;
Divide;/dɪˈvaɪd/;Divided;Divided;Divide the cake;Dividir;
Doubt;/daʊt/;Doubted;Doubted;Doubt the story;Dudar;
Drag;/dræɡ/;Dragged;Dragged;Drag the box;Arrastrar;
Drain;/dreɪn/;Drained;Drained;Drain the pool;Drenar;
Dress;/drɛs/;Dressed;Dressed;Dress nicely;Vestirse;
Drop;/drɑːp/;Dropped;Dropped;Drop the glass;Dejar caer;
Dry;/draɪ/;Dried;Dried;Dry the clothes;Secar;
Earn;/ɜːrn/;Earned;Earned;Earn money;Ganar;
Educate;/ˈɛdʒʊkeɪt/;Educated;Educated;Educate the youth;Educar;
Embarrass;/ɪmˈbærəs/;Embarrassed;Embarrassed;Embarrass the friend;Avergonzar;
Employ;/ɪmˈplɔɪ/;Employed;Employed;Employ new staff;Emplear;
Empty;/ˈɛmpti/;Emptied;Emptied;Empty the trash;Vaciar;
Encourage;/ɪnˈkɜːrɪdʒ/;Encouraged;Encouraged;Encourage the team;Animar;
End;/ɛnd/;Ended;Ended;End the game;Terminar;
Enjoy;/ɪnˈdʒɔɪ/;Enjoyed;Enjoyed;Enjoy the party;Disfrutar;
Enter;/ˈɛntər/;Entered;Entered;Enter the room;Entrar;
Entertain;/ˌɛntərˈteɪn/;Entertained;Entertained;Entertain the guests;Entretener;
Escape;/ɪˈskeɪp/;Escaped;Escaped;Escape the maze;Escapar;
Examine;/ɪɡˈzæmɪn/;Examined;Examined;Examine the patient;Examinar;
Excite;/ɪkˈsaɪt/;Excited;Excited;Excite the fans;Emocionar;
Excuse;/ɪkˈskjuːz/;Excused;Excused;Excuse the interruption;Disculpar;
Exercise;/ˈɛksərsaɪz/;Exercised;Exercised;Exercise daily;Ejercitar;
Exist;/ɪɡˈzɪst/;Existed;Existed;Exist in nature;Existir;
Expand;/ɪkˈspænd/;Expanded;Expanded;Expand the business;Expandir;
Expect;/ɪkˈspɛkt/;Expected;Expected;Expect a visitor;Esperar;
Explain;/ɪkˈspleɪn/;Explained;Explained;Explain the rules;Explicar;
Explode;/ɪkˈsploʊd/;Exploded;Exploded;Explode the bomb;Explotar;
Extend;/ɪkˈstɛnd/;Extended;Extended;Extend the deadline;Extender;
Face;/feɪs/;Faced;Faced;Face the fear;Enfrentar;
Fade;/feɪd/;Faded;Faded;Fade away;Desvanecerse;
Fail;/feɪl/;Failed;Failed;Fail the test;Fallar;
Fancy;/ˈfænsi/;Fancied;Fancied;Fancy a drink;Apetecer;
Fasten;/ˈfæsən/;Fastened;Fastened;Fasten the seatbelt;Abrochar;
Fear;/fɪr/;Feared;Feared;Fear the dark;Temer;
Fence;/fɛns/;Fenced;Fenced;Fence the yard;Cercar;
Fetch;/fɛtʃ/;Fetched;Fetched;Fetch the ball;Ir a buscar;
File;/faɪl/;Filed;Filed;File the documents;Archivar;
Fill;/fɪl/;Filled;Filled;Fill the cup;Llenar;
Film;/fɪlm/;Filmed;Filmed;Film a movie;Filmar;
Fire;/faɪr/;Fired;Fired;Fire the employee;Despedir;
Fix;/fɪks/;Fixed;Fixed;Fix the broken car;Arreglar;
Flash;/flæʃ/;Flashed;Flashed;Flash the lights;Destellar;
Float;/floʊt/;Floated;Floated;Float on water;Flotar;
Flood;/flʌd/;Flooded;Flooded;Flood the streets;Inundar;
Flow;/floʊ/;Flowed;Flowed;Flow smoothly;Fluir;
Fold;/foʊld/;Folded;Folded;Fold the paper;Doblar;
Follow;/ˈfɑːloʊ/;Followed;Followed;Follow the leader;Seguir;
Fool;/fuːl/;Fooled;Fooled;Fool the enemy;Engañar;
Force;/fɔːrs/;Forced;Forced;Force the door;Forzar;
Form;/fɔːrm/;Formed;Formed;Form a group;Formar;
Found;/faʊnd/;Founded;Founded;Found a company;Fundar;
Frame;/freɪm/;Framed;Framed;Frame the picture;Enmarcar;
Frighten;/ˈfraɪtn/;Frightened;Frightened;Frighten the cat;Asustar;
Fry;/fraɪ/;Fried;Fried;Fry the potatoes;Freír;
Gather;/ˈɡæðər/;Gathered;Gathered;Gather the team;Reunir;
Gaze;/ɡeɪz/;Gazed;Gazed;Gaze at the stars;Contemplar;
Glow;/ɡloʊ/;Glowed;Glowed;Glow in the dark;Brillar;
Glue;/ɡluː/;Glued;Glued;Glue the pieces;Pegar;
Grab;/ɡræb/;Grabbed;Grabbed;Grab the bag;Agarrar;
Grant;/ɡrænt/;Granted;Granted;Grant permission;Conceder;
Grate;/ɡreɪt/;Grated;Grated;Grate the cheese;Rallar;
Grease;/ɡriːs/;Greased;Greased;Grease the pan;Engrasar;
Greet;/ɡriːt/;Greeted;Greeted;Greet the guests;Saludar;
Grin;/ɡrɪn/;Grinned;Grinned;Grin widely;Sonreír;
Grip;/ɡrɪp/;Gripped;Gripped;Grip the handle;Sujetar;
Groan;/ɡroʊn/;Groaned;Groaned;Groan in pain;Gemir;
Guarantee;/ˌɡærənˈtiː/;Guaranteed;Guaranteed;Guarantee the product;Garantizar;
Guard;/ɡɑːrd/;Guarded;Guarded;Guard the entrance;Vigilar;
Guess;/ɡɛs/;Guessed;Guessed;Guess the answer;Adivinar;
Guide;/ɡaɪd/;Guided;Guided;Guide the tourists;Guiar;
Hammer;/ˈhæmər/;Hammered;Hammered;Hammer the nail;Martillar;
Hand;/hænd/;Handed;Handed;Hand the pen;Entregar;
Handle;/ˈhændəl/;Handled;Handled;Handle the situation;Manejar;
Happen;/ˈhæpən/;Happened;Happened;Happen suddenly;Suceder;
Harass;/həˈræs/;Harassed;Harassed;Harass the worker;Acosar;
Harm;/hɑːrm/;Harmed;Harmed;Harm the environment;Dañar;
Hate;/heɪt/;Hated;Hated;Hate the weather;Odiar;
Haunt;/hɔːnt/;Haunted;Haunted;Haunt the house;Embrujar;
Head;/hɛd/;Headed;Headed;Head north;Dirigirse;
Heal;/hiːl/;Healed;Healed;Heal the wound;Sanar;
Heap;/hiːp/;Heaped;Heaped;Heap the clothes;Apilar;
Heat;/hiːt/;Heated;Heated;Heat the soup;Calentar;
Help;/hɛlp/;Helped;Helped;Help a friend;Ayudar;
Hook;/hʊk/;Hooked;Hooked;Hook the fish;Enganchar;
Hop;/hɑːp/;Hopped;Hopped;Hop on one foot;Saltar;
Hope;/hoʊp/;Hoped;Hoped;Hope for the best;Esperar;
Hover;/ˈhʌvər/;Hovered;Hovered;Hover above ground;Flotar;
Hug;/hʌɡ/;Hugged;Hugged;Hug tightly;Abrazar;
Hum;/hʌm/;Hummed;Hummed;Hum a tune;Tararear;
Hunt;/hʌnt/;Hunted;Hunted;Hunt for food;Cazar;
Hurry;/ˈhɜːri/;Hurried;Hurried;Hurry up;Apresurarse;
Identify;/aɪˈdɛntɪfaɪ/;Identified;Identified;Identify the suspect;Identificar;
Ignore;/ɪɡˈnɔːr/;Ignored;Ignored;Ignore the noise;Ignorar;
Illustrate;/ˈɪləstreɪt/;Illustrated;Illustrated;Illustrate the book;Ilustrar;
Imagine;/ɪˈmædʒɪn/;Imagined;Imagined;Imagine the future;Imaginar;
Imply;/ɪmˈplaɪ/;Implied;Implied;Imply a meaning;Implicar;
Impress;/ɪmˈprɛs/;Impressed;Impressed;Impress the boss;Impresionar;
Improve;/ɪmˈpruːv/;Improved;Improved;Improve your skills;Mejorar;
Include;/ɪnˈkluːd/;Included;Included;Include everyone;Incluir;
Increase;/ɪnˈkriːs/;Increased;Increased;Increase the price;Aumentar;
Influence;/ˈɪnfluəns/;Influenced;Influenced;Influence people;Influenciar;
Inform;/ɪnˈfɔːrm/;Informed;Informed;Inform the public;Informar;
Inject;/ɪnˈdʒɛkt/;Injected;Injected;Inject the medicine;Inyectar;
Injure;/ˈɪndʒər/;Injured;Injured;Injure the leg;Lesionar;
Insert;/ɪnˈsɜːrt/;Inserted;Inserted;Insert the coin;Insertar;
Inspect;/ɪnˈspɛkt/;Inspected;Inspected;Inspect the car;Inspeccionar;
Inspire;/ɪnˈspaɪər/;Inspired;Inspired;Inspire the team;Inspirar;
Install;/ɪnˈstɔːl/;Installed;Installed;Install the software;Instalar;
Intend;/ɪnˈtɛnd/;Intended;Intended;Intend to go;Tener la intención;
Interest;/ˈɪntrəst/;Interested;Interested;Interest the buyer;Interesar;
Interfere;/ˌɪntərˈfɪr/;Interfered;Interfered;Interfere in matters;Interferir;
Interrupt;/ˌɪntəˈrʌpt/;Interrupted;Interrupted;Interrupt the speech;Interrumpir;
Introduce;/ˌɪntəˈduːs/;Introduced;Introduced;Introduce a friend;Presentar;
Invent;/ɪnˈvɛnt/;Invented;Invented;Invent a machine;Inventar;
Invite;/ɪnˈvaɪt/;Invited;Invited;Invite to dinner;Invitar;
Irritate;/ˈɪrɪteɪt/;Irritated;Irritated;Irritate the skin;Irritar;
Itch;/ɪtʃ/;Itched;Itched;Itch constantly;Picar;
Jail;/dʒeɪl/;Jailed;Jailed;Jail the criminal;Encarcelar;
Jam;/dʒæm/;Jammed;Jammed;Jam the printer;Atascar;
Jog;/dʒɑːɡ/;Jogged;Jogged;Jog in the park;Trotar;
Join;/dʒɔɪn/;Joined;Joined;Join the club;Unirse;
Joke;/dʒoʊk/;Joked;Joked;Joke around;Bromear;
Judge;/dʒʌdʒ/;Judged;Judged;Judge the contest;Juzgar;
Juggle;/ˈdʒʌɡəl/;Juggled;Juggled;Juggle the balls;Malabarear;
Jump;/dʒʌmp/;Jumped;Jumped;Jump high;Saltar;
Kick;/kɪk/;Kicked;Kicked;Kick the ball;Patear;
Kill;/kɪl/;Killed;Killed;Kill the bugs;Matar;
Kiss;/kɪs/;Kissed;Kissed;Kiss the bride;Besar;
Knock;/nɑːk/;Knocked;Knocked;Knock on wood;Tocar;
Knot;/nɑːt/;Knotted;Knotted;Knot the tie;Anudar;
Label;/ˈleɪbəl/;Labeled;Labeled;Label the boxes;Etiquetar;
Lack;/læk/;Lacked;Lacked;Lack experience;Carecer;
Land;/lænd/;Landed;Landed;Land the plane;Aterrizar;
Last;/læst/;Lasted;Lasted;Last for hours;Durar;
Laugh;/læf/;Laughed;Laughed;Laugh out loud;Reír;
Launch;/lɔːntʃ/;Launched;Launched;Launch a rocket;Lanzar;
Level;/ˈlɛvəl/;Leveled;Leveled;Level the ground;Nivelar;
Lighten;/ˈlaɪtən/;Lightened;Lightened;Lighten the load;Aligerar;
Like;/laɪk/;Liked;Liked;Like the video;Gustar;
Limit;/ˈlɪmɪt/;Limited;Limited;Limit the speed;Limitar;
Link;/lɪŋk/;Linked;Linked;Link the pages;Enlazar;
List;/lɪst/;Listed;Listed;List the items;Listar;
Listen;/ˈlɪsən/;Listened;Listened;Listen to music;Escuchar;
Live;/lɪv/;Lived;Lived;Live in peace;Vivir;
Load;/loʊd/;Loaded;Loaded;Load the truck;Cargar;
Lock;/lɑːk/;Locked;Locked;Lock the door;Bloquear;
Look;/lʊk/;Looked;Looked;Look at this;Mirar;
Mail;/meɪl/;Mailed;Mailed;Mail the letter;Enviar por correo;
Maintain;/meɪnˈteɪn/;Maintained;Maintained;Maintain order;Mantener;
Manage;/ˈmænɪdʒ/;Managed;Managed;Manage a team;Gestionar;
March;/mɑːrtʃ/;Marched;Marched;March together;Marchar;
Mark;/mɑːrk/;Marked;Marked;Mark the spot;Marcar;
Marry;/ˈmæri/;Married;Married;Marry your love;Casarse;
Match;/mætʃ/;Matched;Matched;Match the colors;Emparejar;
Matter;/ˈmætər/;Mattered;Mattered;Matter to me;Importar;
Measure;/ˈmɛʒər/;Measured;Measured;Measure the length;Medir;
Melt;/mɛlt/;Melted;Melted;Melt the ice;Derretir;
Memorize;/ˈmɛməraɪz/;Memorized;Memorized;Memorize the poem;Memorizar;
Mend;/mɛnd/;Mended;Mended;Mend the tear;Remendar;
Mention;/ˈmɛnʃən/;Mentioned;Mentioned;Mention a fact;Mencionar;
Merge;/mɜːrdʒ/;Merged;Merged;Merge the files;Fusionar;
Milk;/mɪlk/;Milked;Milked;Milk the cow;Ordeñar;
Mine;/maɪn/;Mined;Mined;Mine for gold;Minar;
Miss;/mɪs/;Missed;Missed;Miss the bus;Extrañar;
Mix;/mɪks/;Mixed;Mixed;Mix the colors;Mezclar;
Moan;/moʊn/;Moaned;Moaned;Moan in pain;Gemir;
Mourn;/mɔːrn/;Mourned;Mourned;Mourn the loss;Lamentar;
Move;/muːv/;Moved;Moved;Move the chair;Mover;
Mug;/mʌɡ/;Mugged;Mugged;Mug the tourist;Asaltar;
Multiply;/ˈmʌltɪplaɪ/;Multiplied;Multiplied;Multiply by two;Multiplicar;
Murder;/ˈmɜːrdər/;Murdered;Murdered;Murder the victim;Asesinar;
Nail;/neɪl/;Nailed;Nailed;Nail the board;Clavar;
Name;/neɪm/;Named;Named;Name the baby;Nombrar;
Need;/niːd/;Needed;Needed;Need some rest;Necesitar;
Nest;/nɛst/;Nested;Nested;Nest in the tree;Anidar;
Nod;/nɑːd/;Nodded;Nodded;Nod your head;Asentir;
Note;/noʊt/;Noted;Noted;Note the details;Anotar;
Notice;/ˈnoʊtɪs/;Noticed;Noticed;Notice the sign;Notar;
Number;/ˈnʌmbər/;Numbered;Numbered;Number the pages;Numerar;
Obey;/oʊˈbeɪ/;Obeyed;Obeyed;Obey the rules;Obedecer;
Object;/əbˈdʒɛkt/;Objected;Objected;Object to the plan;Objetar;
Observe;/əbˈzɜːrv/;Observed;Observed;Observe the stars;Observar;
Obtain;/əbˈteɪn/;Obtained;Obtained;Obtain a copy;Obtener;
Occur;/əˈkɜːr/;Occurred;Occurred;Occur suddenly;Ocurrir;
Offend;/əˈfɛnd/;Offended;Offended;Ofender a un amigo;Ofender;
Offer;/ˈɔːfər/;Offered;Offered;Offer a drink;Ofrecer;
Open;/ˈoʊpən/;Opened;Opened;Open the window;Abrir;
Order;/ˈɔːrdər/;Ordered;Ordered;Order some food;Ordenar;
Overload;/ˌoʊvərˈloʊd/;Overloaded;Overloaded;Overload the system;Sobrecargar;
Owe;/oʊ/;Owed;Owed;Owe him money;Deber;
Own;/oʊn/;Owned;Owned;Own a house;Poseer;
Pack;/pæk/;Packed;Packed;Pack the bags;Empacar;
Paddle;/ˈpædəl/;Paddled;Paddled;Paddle the boat;Remar;
Park;/pɑːrk/;Parked;Parked;Park the car;Estacionar;
Part;/pɑːrt/;Parted;Parted;Part ways;Separar;
Pass;/pæs/;Passed;Passed;Pass the exam;Pasar;
Paste;/peɪst/;Pasted;Pasted;Paste the text;Pegar;
Pat;/pæt/;Patted;Patted;Pat the dog;Acariciar;
Pause;/pɔːz/;Paused;Paused;Pause the video;Pausar;
Peck;/pɛk/;Pecked;Pecked;Peck the seed;Picotear;
Pedal;/ˈpɛdəl/;Pedaled;Pedaled;Pedal the bike;Pedalear;
Peel;/piːl/;Peeled;Peeled;Peel the apple;Pelar;
Peep;/piːp/;Peeped;Peeped;Peep through the hole;Asomarse;
Perform;/pərˈfɔːrm/;Performed;Performed;Perform a trick;Realizar;
Permit;/pərˈmɪt/;Permitted;Permitted;Permit entry;Permitir;
Phone;/foʊn/;Phoned;Phoned;Phone your mom;Llamar;
Pick;/pɪk/;Picked;Picked;Pick a card;Elegir;
Pinch;/pɪntʃ/;Pinched;Pinched;Pinch the skin;Pellizcar;
Place;/pleɪs/;Placed;Placed;Place the book;Colocar;
Plan;/plæn/;Planned;Planned;Plan a trip;Planear;
Plant;/plænt/;Planted;Planted;Plant a tree;Plantar;
Play;/pleɪ/;Played;Played;Play guitar;Jugar;
Please;/pliːz/;Pleased;Pleased;Please the crowd;Complacer;
Plug;/plʌɡ/;Plugged;Plugged;Plug the cord;Enchufar;
Point;/pɔɪnt/;Pointed;Pointed;Point the finger;Apuntar;
Poke;/poʊk/;Poked;Poked;Poke the fire;Hurgar;
Polish;/ˈpɑːlɪʃ/;Polished;Polished;Polish the shoes;Pulir;
Pop;/pɑːp/;Popped;Popped;Pop the balloon;Estallar;
Possess;/pəˈzɛs/;Possessed;Possessed;Possess magic;Poseer;
Post;/poʊst/;Posted;Posted;Post a letter;Publicar;
Pour;/pɔːr/;Poured;Poured;Pour the milk;Verter;
Practice;/ˈpræktɪs/;Practiced;Practiced;Practice piano;Practicar;
Pray;/preɪ/;Prayed;Prayed;Pray for peace;Orar;
Preach;/priːtʃ/;Preached;Preached;Preach the word;Predicar;
Precede;/prɪˈsiːd/;Preceded;Preceded;Precede the event;Preceder;
Prefer;/prɪˈfɜːr/;Preferred;Preferred;Prefer tea;Preferir;
Prepare;/prɪˈpɛr/;Prepared;Prepared;Prepare the meal;Preparar;
Present;/prɪˈzɛnt/;Presented;Presented;Present the award;Presentar;
Preserve;/prɪˈzɜːrv/;Preserved;Preserved;Preserve nature;Preservar;
Press;/prɛs/;Pressed;Pressed;Press the button;Presionar;
Pretend;/prɪˈtɛnd/;Pretended;Pretended;Pretend to sleep;Fingir;
Prevent;/prɪˈvɛnt/;Prevented;Prevented;Prevent accidents;Prevenir;
Prick;/prɪk/;Pricked;Pricked;Prick your finger;Pinchar;
Print;/prɪnt/;Printed;Printed;Print the file;Imprimir;
Produce;/prəˈduːs/;Produced;Produced;Produce goods;Producir;
Program;/ˈproʊɡræm/;Programmed;Programmed;Program a game;Programar;
Promise;/ˈprɑːmɪs/;Promised;Promised;Promise to help;Prometer;
Protect;/prəˈtɛkt/;Protected;Protected;Protect the weak;Proteger;
Provide;/prəˈvaɪd/;Provided;Provided;Provide food;Proveer;
Pull;/pʊl/;Pulled;Pulled;Pull the rope;Tirar;
Pump;/pʌmp/;Pumped;Pumped;Pump the water;Bombear;
Punch;/pʌntʃ/;Punched;Punched;Punch the bag;Golpear;
Punish;/ˈpʌnɪʃ/;Punished;Punished;Punish the crime;Castigar;
Push;/pʊʃ/;Pushed;Pushed;Push the cart;Empujar;
Question;/ˈkwɛstʃən/;Questioned;Questioned;Question the logic;Cuestionar;
Queue;/kjuː/;Queued;Queued;Queue for tickets;Hacer fila;
Quote;/kwoʊt/;Quoted;Quoted;Quote the author;Citar;
Race;/reɪs/;Raced;Raced;Race to the finish;Correr;
Rain;/reɪn/;Rained;Rained;Rain all day;Llover;
Raise;/reɪz/;Raised;Raised;Raise your hand;Levantar;
Reach;/riːtʃ/;Reached;Reached;Reach the top;Alcanzar;
Realize;/ˈriːəlaɪz/;Realized;Realized;Realize the truth;Darse cuenta;
Receive;/rɪˈsiːv/;Received;Received;Receive a gift;Recibir;
Recognize;/ˈrɛkəɡnaɪz/;Recognized;Recognized;Recognize a face;Reconocer;
Record;/rɪˈkɔːrd/;Recorded;Recorded;Record a song;Grabar;
Reduce;/rɪˈduːs/;Reduced;Reduced;Reduce the cost;Reducir;
Reflect;/rɪˈflɛkt/;Reflected;Reflected;Reflect the light;Reflejar;
Refuse;/rɪˈfjuːz/;Refused;Refused;Refuse the offer;Rechazar;
Regret;/rɪˈɡrɛt/;Regretted;Regretted;Regret the choice;Arrepentirse;
Relax;/rɪˈlæks/;Relaxed;Relaxed;Relax at home;Relajarse;
Release;/rɪˈliːs/;Released;Released;Release the bird;Liberar;
Rely;/rɪˈlaɪ/;Relied;Relied;Rely on friends;Confiar;
Remain;/rɪˈmeɪn/;Remained;Remained;Remain calm;Permanecer;
Remember;/rɪˈmɛmbər/;Remembered;Remembered;Remember the day;Recordar;
Remind;/rɪˈmaɪnd/;Reminded;Reminded;Remind me later;Recordar;
Remove;/rɪˈmuːv/;Removed;Removed;Remove the stain;Quitar;
Rent;/rɛnt/;Rented;Rented;Rent a car;Alquilar;
Repair;/rɪˈpɛr/;Repaired;Repaired;Repair the bike;Reparar;
Repeat;/rɪˈpiːt/;Repeated;Repeated;Repeat the word;Repetir;
Replace;/rɪˈpleɪs/;Replaced;Replaced;Replace the bulb;Reemplazar;
Reply;/rɪˈplaɪ/;Replied;Replied;Reply to email;Responder;
Report;/rɪˈpɔːrt/;Reported;Reported;Report the issue;Reportar;
Reproduce;/ˌriːprəˈduːs/;Reproduced;Reproduced;Reproduce the sound;Reproducir;
Request;/rɪˈkwɛst/;Requested;Requested;Request a song;Solicitar;
Rescue;/ˈrɛskjuː/;Rescued;Rescued;Rescue the cat;Rescatar;
Retire;/rɪˈtaɪr/;Retired;Retired;Retire from work;Jubilarse;
Return;/rɪˈtɜːrn/;Returned;Returned;Return the book;Devolver;
Rhyme;/raɪm/;Rhymed;Rhymed;Rhyme the words;Rimar;
Rinse;/rɪns/;Rinsed;Rinsed;Rinse the cup;Enjuagar;
Risk;/rɪsk/;Risked;Risked;Risk your life;Arriesgar;
Roast;/roʊst/;Roasted;Roasted;Roast the meat;Asar;
Rob;/rɑːb/;Robbed;Robbed;Rob a bank;Robar;
Rock;/rɑːk/;Rocked;Rocked;Rock the baby;Mecer;
Roll;/roʊl/;Rolled;Rolled;Roll the dice;Rodar;
Rub;/rʌb/;Rubbed;Rubbed;Rub your hands;Frotar;
Ruin;/ˈruːɪn/;Ruined;Ruined;Ruin the surprise;Arruinar;
Rule;/ruːl/;Ruled;Ruled;Rule the country;Gobernar;
Rush;/rʌʃ/;Rushed;Rushed;Rush to work;Apresurarse;
Sack;/sæk/;Sacked;Sacked;Sack the worker;Despedir;
Sail;/seɪl/;Sailed;Sailed;Sail the boat;Navegar;
Satisfy;/ˈsætɪsfaɪ/;Satisfied;Satisfied;Satisfy the hunger;Satisfacer;
Save;/seɪv/;Saved;Saved;Save the file;Guardar;
Scan;/skæn/;Scanned;Scanned;Scan the document;Escanear;
Scare;/skɛr/;Scared;Scared;Scare the birds;Asustar;
Scatter;/ˈskætər/;Scattered;Scattered;Scatter the seeds;Esparcir;
Scold;/skoʊld/;Scolded;Scolded;Scold the child;Regañar;
Scorch;/skɔːrtʃ/;Scorched;Scorched;Scorch the shirt;Chamuscar;
Scrape;/skreɪp/;Scraped;Scraped;Scrape the dirt;Raspar;
Scrace;/skrætʃ/;Scratched;Scratched;Scratch the surface;Rascar;
Scream;/skriːm/;Screamed;Screamed;Scream loudly;Gritar;
Screw;/skruː/;Screwed;Screwed;Screw the lid;Atornillar;
Scrub;/skrʌb/;Scrubbed;Scrubbed;Scrub the floor;Fregar;
Seal;/siːl/;Sealed;Sealed;Seal the envelope;Sellar;
Search;/sɜːrtʃ/;Searched;Searched;Search the web;Buscar;
Separate;/ˈsɛpəreɪt/;Separated;Separated;Separate the trash;Separar;
Serve;/sɜːrv/;Served;Served;Serve the dinner;Servir;
Settle;/ˈsɛtəl/;Settled;Settled;Settle the bill;Liquidar;
Shade;/ʃeɪd/;Shaded;Shaded;Shade the drawing;Sombrear;
Share;/ʃɛr/;Shared;Shared;Share the pizza;Compartir;
Shave;/ʃeɪv/;Shaved;Shaved;Shave your beard;Afeitar;
Shelter;/ˈʃɛltər/;Sheltered;Sheltered;Shelter from rain;Refugiar;
Shiver;/ˈʃɪvər/;Shivered;Shivered;Shiver with cold;Temblar;
Shock;/ʃɑːk/;Shocked;Shocked;Shock the crowd;Conmocionar;
Shop;/ʃɑːp/;Shopped;Shopped;Shop for clothes;Comprar;
Shrug;/ʃrʌɡ/;Shrugged;Shrugged;Shrug your shoulders;Encogerse;
Sigh;/saɪ/;Sighed;Sighed;Sigh deeply;Suspirar;
Sign;/saɪn/;Signed;Signed;Sign the contract;Firmar;
Signal;/ˈsɪɡnəl/;Signaled;Signaled;Signal for help;Señalizar;
Sin;/sɪn/;Sinned;Sinned;Sin against God;Pecar;
Sip;/sɪp/;Sipped;Sipped;Sip the tea;Sorber;
Ski;/skiː/;Skied;Skied;Ski down the mountain;Esquiar;
Skip;/skɪp/;Skipped;Skipped;Skip the intro;Omitir;
Slap;/slæp/;Slapped;Slapped;Slap the table;Abofetear;
Slip;/slɪp/;Slipped;Slipped;Slip on ice;Resbalar;
Slow;/sloʊ/;Slowed;Slowed;Slow the pace;Ralentizar;
Smash;/smæʃ/;Smashed;Smashed;Smash the glass;Destrozar;
Smile;/smaɪl/;Smiled;Smiled;Smile at me;Sonreír;
Smoke;/smoʊk/;Smoked;Smoked;Smoke a pipe;Fumar;
Snatch;/snætʃ/;Snatched;Snatched;Snatch the bag;Arrebatar;
Sneeze;/sniːz/;Sneezed;Sneezed;Sneeze loudly;Estornudar;
Sniff;/snɪf/;Sniffed;Sniffed;Sniff the flower;Olfatear;
Snore;/snɔːr/;Snored;Snored;Snore at night;Roncar;
Snow;/snoʊ/;Snowed;Snowed;Snow in winter;Nevar;
Soothe;/suːð/;Soothed;Soothed;Soothe the baby;Calmar;
Sound;/saʊnd/;Sounded;Sounded;Sound the alarm;Sonar;
Spare;/spɛr/;Spared;Spared;Spare some change;Ceder;
Spark;/spɑːrk/;Sparked;Sparked;Spark a fire;Chispear;
Sparkle;/ˈspɑːrkəl/;Sparkled;Sparkled;Sparkle bright;Brillar;
Spot;/spɑːt/;Spotted;Spotted;Spot the difference;Detectar;
Spray;/spreɪ/;Sprayed;Sprayed;Spray the paint;Rociar;
Sprout;/spraʊt/;Sprouted;Sprouted;Sprout new leaves;Brotar;
Squash;/skwɑːʃ/;Squashed;Squashed;Squash the bug;Aplastar;
Squeak;/skwiːk/;Squeaked;Squeaked;Squeak like a mouse;Chirriar;
Squeal;/skwiːl/;Squealed;Squealed;Squeal with joy;Gritar;
Squeeze;/skwiːz/;Squeezed;Squeezed;Squeeze the lemon;Exprimir;
Stain;/steɪn/;Stained;Stained;Stain the shirt;Manchar;
Stamp;/stæmp/;Stamped;Stamped;Stamp the passport;Sellar;
Stare;/stɛr/;Stared;Stared;Stare at the wall;Mirar fijamente;
Start;/stɑːrt/;Started;Started;Start the engine;Empezar;
Stay;/steɪ/;Stayed;Stayed;Stay at home;Quedarse;
Step;/stɛp/;Stepped;Stepped;Step outside;Dar un paso;
Stop;/stɑːp/;Stopped;Stopped;Stop the car;Detener;
Store;/stɔːr/;Stored;Stored;Store the food;Almacenar;
Stretch;/strɛtʃ/;Stretched;Stretched;Stretch your legs;Estirar;
Stroke;/stroʊk/;Stroked;Stroked;Stroke the cat;Acariciar;
Stuff;/stʌf/;Stuffed;Stuffed;Stuff the turkey;Rellenar;
Subtract;/səbˈtrækt/;Subtracted;Subtracted;Subtract the numbers;Restar;
Succeed;/səkˈsiːd/;Succeeded;Succeeded;Succeed in life;Tener éxito;
Suck;/sʌk/;Sucked;Sucked;Suck the juice;Chupar;
Suffer;/ˈsʌfər/;Suffered;Suffered;Suffer from cold;Sufrir;
Suggest;/səɡˈdʒɛst/;Suggested;Suggested;Suggest an idea;Sugerir;
Suit;/suːt/;Suited;Suited;Suit your needs;Adaptarse;
Supply;/səˈplaɪ/;Supplied;Supplied;Supply the water;Suministrar;
Support;/səˈpɔːrt/;Supported;Supported;Support the team;Apoyar;
Suppose;/səˈpoʊz/;Supposed;Supposed;Suppose it rains;Suponer;
Surprise;/sərˈpraɪz/;Surprised;Surprised;Surprise your friend;Sorprender;
Surround;/səˈraʊnd/;Surrounded;Surrounded;Surround the building;Rodear;
Suspect;/səˈspɛkt/;Suspected;Suspected;Suspect a crime;Sospechar;
Suspend;/səˈspɛnd/;Suspended;Suspended;Suspend the rules;Suspender;
Swallow;/ˈswɑːloʊ/;Swallowed;Swallowed;Swallow the pill;Tragar;
Switch;/swɪtʃ/;Switched;Switched;Switch the lights;Cambiar;
Talk;/tɔːk/;Talked;Talked;Talk to me;Hablar;
Tame;/teɪm/;Tamed;Tamed;Tame the lion;Domesticar;
Tap;/tæp/;Tapped;Tapped;Tap the screen;Tocar levemente;
Taste;/teɪst/;Tasted;Tasted;Taste the soup;Probar;
Tax;/tæks/;Taxed;Taxed;Tax the income;Someter a impuestos;
Tease;/tiːz/;Teased;Teased;Tease your brother;Burlarse;
Telephone;/ˈtɛləˌfoʊn/;Telephoned;Telephoned;Telephone a doctor;Telefonear;
Tempt;/tɛmpt/;Tempted;Tempted;Tempt with chocolate;Tentar;
Terrify;/ˈtɛrəˌfaɪ/;Terrified;Terrified;Terrify the children;Aterrorizar;
Test;/tɛst/;Tested;Tested;Test the limits;Probar;
Thank;/θæŋk/;Thanked;Thanked;Thank the host;Agradecer;
Thaw;/θɔː/;Thawed;Thawed;Thaw the meat;Descongelar;
Tick;/tɪk/;Ticked;Ticked;Tick the box;Marcar;
Tickle;/ˈtɪkəl/;Tickled;Tickled;Tickle the baby;Hacer cosquillas;
Tie;/taɪ/;Tied;Tied;Tie your shoes;Atar;
Time;/taɪm/;Timed;Timed;Time the race;Cronometrar;
Tire;/taɪr/;Tired;Tired;Tire the muscles;Cansar;
Touch;/tʌtʃ/;Touched;Touched;Touch the screen;Tocar;
Tour;/tʊr/;Toured;Toured;Tour the city;Recorrer;
Tow;/toʊ/;Towed;Towed;Tow the car;Remolcar;
Trace;/treɪs/;Traced;Traced;Trace the outline;Rastrear;
Trade;/treɪd/;Traded;Traded;Trade the cards;Intercambiar;
Train;/treɪn/;Trained;Trained;Train the dog;Entrenar;
Transfer;/trænsˈfɜːr/;Transferred;Transferred;Transfer the money;Transferir;
Transform;/trænsˈfɔːrm/;Transformed;Transformed;Transform the room;Transformar;
Translate;/trænsˈleɪt/;Translated;Translated;Translate the book;Traducir;
Transport;/trænsˈpɔːrt/;Transported;Transported;Transport the goods;Transportar;
Trap;/træp/;Trapped;Trapped;Trap the mouse;Atrapar;
Travel;/ˈtrævəl/;Traveled;Traveled;Travel the world;Viajar;
Treat;/triːt/;Treated;Treated;Treat the patient;Tratar;
Tremble;/ˈtrɛmbəl/;Trembled;Trembled;Tremble with fear;Temblar;
Trick;/trɪk/;Tricked;Tricked;Trick the eye;Engañar;
Trip;/trɪp/;Tripped;Tripped;Trip over a wire;Tropezar;
Trot;/trɑːt/;Trotted;Trotted;Trot on the horse;Trotar;
Trouble;/ˈtrʌbəl/;Troubled;Troubled;Trouble your mind;Preocupar;
Trust;/trʌst/;Trusted;Trusted;Trust your gut;Confiar;
Try;/traɪ/;Tried;Tried;Try your best;Intentar;
Tug;/tʌɡ/;Tugged;Tugged;Tug the rope;Tirar;
Tumble;/ˈtʌmbəl/;Tumbled;Tumbled;Tumble down stairs;Caer;
Turn;/tɜːrn/;Turned;Turned;Turn the page;Girar;
Twist;/twɪst/;Twisted;Twisted;Twist the cap;Torcer;
Type;/taɪp/;Typed;Typed;Type a letter;Escribir a máquina;
Undress;/ʌnˈdrɛs/;Undressed;Undressed;Undress for bed;Desvestirse;
Unfasten;/ʌnˈfæsən/;Unfastened;Unfastened;Unfasten the belt;Desabrochar;
Unite;/juˈnaɪt/;United;United;Unite the people;Unir;
Unlock;/ʌnˈlɑːk/;Unlocked;Unlocked;Unlock the door;Desbloquear;
Unpack;/ʌnˈpæk/;Unpacked;Unpacked;Unpack the bags;Desempacar;
Untie;/ʌnˈtaɪ/;Untied;Untied;Untie the knot;Desatar;
Use;/juːz/;Used;Used;Use the tool;Usar;
Vanish;/ˈvænɪʃ/;Vanished;Vanished;Vanish into thin air;Desaparecer;
Visit;/ˈvɪzɪt/;Visited;Visited;Visit a museum;Visitar;
Vote;/voʊt/;Voted;Voted;Vote for him;Votar;
Wait;/weɪt/;Waited;Waited;Wait for me;Esperar;
Walk;/wɔːk/;Walked;Walked;Walk the dog;Caminar;
Wander;/ˈwɑːndər/;Wandered;Wandered;Wander around;Deambular;
Want;/wɑːnt/;Wanted;Wanted;Want some coffee;Querer;
Warm;/wɔːrm/;Warmed;Warmed;Warm your hands;Calentar;
Warn;/wɔːrn/;Warned;Warned;Warn the driver;Advertir;
Wash;/wɑːʃ/;Washed;Washed;Wash the dishes;Lavar;
Waste;/weɪst/;Wasted;Wasted;Waste your time;Desperdiciar;
Watch;/wɑːtʃ/;Watched;Watched;Watch a movie;Mirar;
Water;/ˈwɔːtər/;Watered;Watered;Water the plants;Regar;
Wave;/weɪv/;Waved;Waved;Wave goodbye;Saludar con la mano;
Weigh;/weɪ/;Weighed;Weighed;Weigh the options;Pesar;
Welcome;/ˈwɛlkəm/;Welcomed;Welcomed;Welcome the guests;Dar la bienvenida;
Whisper;/ˈhwɪspər/;Whispered;Whispered;Whisper a secret;Susurrar;
Whistle;/ˈhwɪsəl/;Whistled;Whistled;Whistle a tune;Silbar;
Wipe;/waɪp/;Wiped;Wiped;Wipe the table;Limpiar;
Wish;/wɪʃ/;Wished;Wished;Wish upon a star;Desear;
Wonder;/ˈwʌndər/;Wondered;Wondered;Wonder about life;Preguntarse;
Work;/wɜːrk/;Worked;Worked;Work hard;Trabajar;
Worry;/ˈwɜːri/;Worried;Worried;Worry too much;Preocuparse;
Wrap;/ræp/;Wrapped;Wrapped;Wrap the gift;Envolver;
Wreck;/rɛk/;Wrecked;Wrecked;Wreck the car;Destrozar;
Yawn;/jɔːn/;Yawned;Yawned;Yawn loudly;Bostezar;
Yell;/jɛl/;Yelled;Yelled;Yell for help;Gritar;`

export const parseRegularVerbs = (): RegularVerb[] => {
  return REGULAR_VERBS_RAW.trim().split('\n').map((line, index) => {
    const [infinitive, pronunciation, past, pastParticiple, example, spanish] = line.split(';');
    return {
      id: index + 1,
      infinitive,
      pronunciation,
      past,
      pastParticiple,
      example,
      spanish
    };
  });
};

export const REGULAR_VERBS = parseRegularVerbs();
