export interface Slang {
  id: number;
  word: string;
  ipa: string;
  meaning: string;
  meaning_ipa: string;
  spanish: string;
  example: string;
}

export const SLANGS: Slang[] = [
  { id: 1, word: "Gonna", ipa: "/ˈgʌnə/", meaning: "Going to", meaning_ipa: "/ˈgoʊɪŋ tu/", spanish: "Voy a / Va a", example: "I am gonna leave" },
  { id: 2, word: "Gotta", ipa: "/ˈgɑtə/", meaning: "Got to / Have to", meaning_ipa: "/gɑt tu/ / /hæv tu/", spanish: "Tengo que", example: "I gotta go now" },
  { id: 3, word: "Lemme", ipa: "/ˈlɛmi/", meaning: "Let me", meaning_ipa: "/lɛt mi/", spanish: "Déjame", example: "Lemme see that" },
  { id: 4, word: "Karen", ipa: "/ˈkærən/", meaning: "Entitled woman", meaning_ipa: "/ɪnˈtaɪtəld ˈwʊmən/", spanish: "Mujer quejumbrosa", example: "She acted like a Karen" },
  { id: 5, word: "Ain't", ipa: "/eɪnt/", meaning: "Am not / Is not", meaning_ipa: "/æm nɑt/ / /ɪz nɑt/", spanish: "No soy / No estoy", example: "I ain't doing that" },
  { id: 6, word: "Gimme", ipa: "/ˈgɪmi/", meaning: "Give me", meaning_ipa: "/gɪv mi/", spanish: "Dame", example: "Gimme a break" },
  { id: 7, word: "Kinda", ipa: "/ˈkaɪndə/", meaning: "Kind of", meaning_ipa: "/kaɪnd ʌv/", spanish: "Un poco / Más o menos", example: "I am kinda tired" },
  { id: 8, word: "Sorta", ipa: "/ˈsɔrtə/", meaning: "Sort of", meaning_ipa: "/sɔrt ʌv/", spanish: "Una especie de", example: "It is sorta crazy" },
  { id: 9, word: "Outta", ipa: "/ˈaʊtə/", meaning: "Out of", meaning_ipa: "/aʊt ʌv/", spanish: "Fuera de", example: "Get outta here" },
  { id: 10, word: "Dunno", ipa: "/dəˈnoʊ/", meaning: "Don't know", meaning_ipa: "/doʊnt noʊ/", spanish: "No sé", example: "I dunno what happened" },
  { id: 11, word: "Awesome", ipa: "/ˈɔːsəm/", meaning: "Very good", meaning_ipa: "/ˈvɛri ɡʊd/", spanish: "Increíble", example: "This car is awesome" },
  { id: 12, word: "Bail", ipa: "/beɪl/", meaning: "To leave", meaning_ipa: "/tə liːv/", spanish: "Irse o cancelar", example: "I have to bail early" },
  { id: 13, word: "Basic", ipa: "/ˈbeɪsɪk/", meaning: "Unoriginal", meaning_ipa: "/ˌʌnəˈrɪdʒənəl/", spanish: "Predecible o común", example: "That outfit is too basic" },
  { id: 14, word: "Bet", ipa: "/bɛt/", meaning: "Agreement", meaning_ipa: "/əˈɡriːmənt/", spanish: "Claro que sí", example: "Bet, see you there" },
  { id: 15, word: "Binge", ipa: "/bɪndʒ/", meaning: "Consume excess", meaning_ipa: "/kənˈsum ˈɛkˌsɛs/", spanish: "Maratón (de series)", example: "I will binge this show" },
  { id: 16, word: "Bougie", ipa: "/uːʒi/", meaning: "High class", meaning_ipa: "/haɪ klæs/", spanish: "Refinado o esnob", example: "She likes bougie places" },
  { id: 17, word: "Bro", ipa: "/broʊ/", meaning: "Friend", meaning_ipa: "/frɛnd/", spanish: "Hermano/Amigo", example: "What's up, bro?" },
  { id: 18, word: "Buck", ipa: "/bʌk/", meaning: "Dollar", meaning_ipa: "/ˈdɑlər/", spanish: "Dólar", example: "It costs one buck" },
  { id: 19, word: "Bummer", ipa: "/ˈbʌmər/", meaning: "Disappointment", meaning_ipa: "/ˌdɪsəˈpɔɪntmənt/", spanish: "Decepción", example: "That is such a bummer" },
  { id: 20, word: "Bust", ipa: "/bʌst/", meaning: "Failure", meaning_ipa: "/ˈfeɪljər/", spanish: "Fracaso", example: "The plan was a bust" },
  { id: 21, word: "Cap", ipa: "/kæp/", meaning: "Lie", meaning_ipa: "/laɪ/", spanish: "Mentira", example: "No cap, I saw it" },
  { id: 22, word: "Cheesy", ipa: "/ˈtʃiːzi/", meaning: "Tacky", meaning_ipa: "/ˈtæki/", spanish: "Cursi o de mal gusto", example: "That movie was cheesy" },
  { id: 23, word: "Chill", ipa: "/tʃɪl/", meaning: "Relax", meaning_ipa: "/rɪˈlæks/", spanish: "Relajarse", example: "Let's just chill today" },
  { id: 24, word: "Clout", ipa: "/ˈklaʊt/", meaning: "Influence", meaning_ipa: "/ˈɪnfluəns/", spanish: "Influencia/Fama", example: "He does it for clout" },
  { id: 25, word: "Cool", ipa: "/kuːl/", meaning: "Great", meaning_ipa: "/ɡreɪt/", spanish: "Genial", example: "That shirt is cool" },
  { id: 26, word: "Cop", ipa: "/kɑp/", meaning: "To buy", meaning_ipa: "/tə baɪ/", spanish: "Comprar", example: "I want to cop those shoes" },
  { id: 27, word: "Cram", ipa: "/kræm/", meaning: "Study hard", meaning_ipa: "/ˈstʌdi hɑrd/", spanish: "Estudiar a última hora", example: "I need to cram tonight" },
  { id: 28, word: "Crash", ipa: "/kræʃ/", meaning: "Go to sleep", meaning_ipa: "/ɡoʊ tə sliːp/", spanish: "Dormir de golpe", example: "I am going to crash" },
  { id: 29, word: "Creep", ipa: "/kriːp/", meaning: "Weird person", meaning_ipa: "/wɪrd ˈpɜrsən/", spanish: "Persona rara", example: "He is a creep" },
  { id: 30, word: "Cringe", ipa: "/krɪndʒ/", meaning: "Embarrassing", meaning_ipa: "/ɪmˈbærəsɪŋ/", spanish: "Vergüenza ajena", example: "That joke was cringe" },
  { id: 31, word: "Dead", ipa: "/dɛd/", meaning: "Very funny", meaning_ipa: "/ˈvɛri ˈfʌni/", spanish: "Muerto de risa", example: "That meme has me dead" },
  { id: 32, word: "Dime", ipa: "/daɪm/", meaning: "Beautiful", meaning_ipa: "/ˈbjutəfəl/", spanish: "Persona atractiva", example: "She is a dime" },
  { id: 33, word: "Ditch", ipa: "/dɪtʃ/", meaning: "Abandon", meaning_ipa: "/əˈbændən/", spanish: "Dejar botado", example: "Don't ditch me here" },
  { id: 34, word: "Dope", ipa: "/doʊp/", meaning: "Excellent", meaning_ipa: "/ˈɛksələnt/", spanish: "Genial", example: "This song is dope" },
  { id: 35, word: "Down", ipa: "/daʊn/", meaning: "Willing", meaning_ipa: "/ˈwɪlɪŋ/", spanish: "Dispuesto", example: "I am down to go" },
  { id: 36, word: "Drag", ipa: "/dræɡ/", meaning: "Boring", meaning_ipa: "/ˈbɔrɪŋ/", spanish: "Algo aburrido", example: "Waiting here is a drag" },
  { id: 37, word: "Drama", ipa: "/ˈdrɑmə/", meaning: "Conflict", meaning_ipa: "/ˈkɑnflɪkt/", spanish: "Conflicto", example: "I avoid the drama" },
  { id: 38, word: "Drip", ipa: "/drɪp/", meaning: "Style", meaning_ipa: "/staɪl/", spanish: "Estilo/Ropa genial", example: "Look at his drip" },
  { id: 39, word: "Dude", ipa: "/dud/", meaning: "Person", meaning_ipa: "/ˈpɜrsən/", spanish: "Amigo/Sujeto", example: "Hey dude, what's up?" },
  { id: 40, word: "Extra", ipa: "/ˈɛkstrə/", meaning: "Over the top", meaning_ipa: "/ˈoʊvər ðə tɑp/", spanish: "Exagerado", example: "Don't be so extra" },
  { id: 41, word: "Fam", ipa: "/fæm/", meaning: "Family", meaning_ipa: "/ˈfæməli/", spanish: "Familia/Amigos", example: "What are we doing, fam?" },
  { id: 42, word: "Finesse", ipa: "/fɪˈnɛs/", meaning: "Trick", meaning_ipa: "/trɪk/", spanish: "Manejar con astucia", example: "I will finesse the system" },
  { id: 43, word: "Fire", ipa: "/faɪər/", meaning: "Amazing", meaning_ipa: "/əˈmeɪzɪŋ/", spanish: "Increíble/Fuego", example: "This food is fire" },
  { id: 44, word: "Flake", ipa: "/fleɪk/", meaning: "Unreliable", meaning_ipa: "/ˌʌnrɪˈlaɪəbəl/", spanish: "Persona que cancela", example: "He is a flake" },
  { id: 45, word: "Flex", ipa: "/flɛks/", meaning: "Show off", meaning_ipa: "/ʃoʊ ɔf/", spanish: "Presumir", example: "Weird flex, but okay" },
  { id: 46, word: "Ghost", ipa: "/ɡoʊst/", meaning: "Disappear", meaning_ipa: "/ˌdɪsəˈpɪr/", spanish: "Desaparecer sin avisar", example: "He ghosted me" },
  { id: 47, word: "Gig", ipa: "/ɡɪɡ/", meaning: "Job", meaning_ipa: "/dʒɑb/", spanish: "Trabajo o evento", example: "I got a new gig" },
  { id: 48, word: "GOAT", ipa: "/ɡoʊt/", meaning: "Greatest", meaning_ipa: "/ˈɡreɪtəst/", spanish: "El mejor de todos", example: "Messi is the GOAT" },
  { id: 49, word: "Grand", ipa: "/ɡrænd/", meaning: "Thousand", meaning_ipa: "/ˈθaʊzənd/", spanish: "Mil dólares", example: "It costs two grand" },
  { id: 50, word: "Grub", ipa: "/ɡrʊb/", meaning: "Food", meaning_ipa: "/fud/", spanish: "Comida", example: "Let's get some grub" },
  { id: 51, word: "Gucci", ipa: "/ˈɡutʃi/", meaning: "Good", meaning_ipa: "/ɡʊd/", spanish: "Todo bien", example: "It's all Gucci" },
  { id: 52, word: "Hangry", ipa: "/ˈhæŋɡri/", meaning: "Hungry angry", meaning_ipa: "/ˈhʌŋɡri ˈæŋɡri/", spanish: "Enojado por hambre", example: "I am hangry" },
  { id: 53, word: "Hater", ipa: "/ˈheɪtər/", meaning: "Negative person", meaning_ipa: "/ˈnɛɡətɪv ˈpɜrsən/", spanish: "Envidioso", example: "Ignore the hater" },
  { id: 54, word: "Hooked", ipa: "/hʊkt/", meaning: "Addicted", meaning_ipa: "/əˈdɪktɪd/", spanish: "Enganchado", example: "I am hooked on this show" },
  { id: 55, word: "Hype", ipa: "/haɪp/", meaning: "Excited", meaning_ipa: "/ɪkˈsaɪtɪd/", spanish: "Emocionado", example: "I am so hype" },
  { id: 56, word: "Iffy", ipa: "/ˈɪfi/", meaning: "Uncertain", meaning_ipa: "/ənˈsɜrtən/", spanish: "Dudoso", example: "The weather looks iffy" },
  { id: 57, word: "Jacked", ipa: "/dʒækt/", meaning: "Muscular", meaning_ipa: "/ˈmʌskjələr/", spanish: "Musculoso", example: "He got totally jacked" },
  { id: 58, word: "Jam", ipa: "/dʒæm/", meaning: "Song", meaning_ipa: "/sɔŋ/", spanish: "Canción favorita", example: "This is my jam" },
  { id: 59, word: "Jerk", ipa: "/dʒɜrk/", meaning: "Mean person", meaning_ipa: "/min ˈpɜrsən/", spanish: "Idiota o cretino", example: "Don't be a jerk" },
  { id: 60, word: "Jock", ipa: "/dʒɑk/", meaning: "Athlete", meaning_ipa: "/ˈæθlit/", spanish: "Atleta/Deportista", example: "He is a typical jock" },
  { id: 61, word: "Junkie", ipa: "/dʒʌŋki/", meaning: "Addict", meaning_ipa: "/ˈædɪkt/", spanish: "Adicto/Fanático", example: "I am a coffee junkie" },
  { id: 62, word: "Kick back", ipa: "/kɪk bæk/", meaning: "Relax", meaning_ipa: "/rɪˈlæks/", spanish: "Relajarse", example: "We are kicking back" },
  { id: 63, word: "Killer", ipa: "/ˈkɪlər/", meaning: "Awesome", meaning_ipa: "/ˈɔːsəm/", spanish: "Brutal/Genial", example: "That was a killer party" },
  { id: 64, word: "Knockoff", ipa: "/ˈnɑkˌɔf/", meaning: "Fake", meaning_ipa: "/feɪk/", spanish: "Falsificación", example: "This bag is a knockoff" },
  { id: 65, word: "Lame", ipa: "/lame/", meaning: "Boring", meaning_ipa: "/ˈbɔrɪŋ/", spanish: "Aburrido/Patético", example: "That excuse is lame" },
  { id: 66, word: "Legit", ipa: "/ləˈdʒɪt/", meaning: "Real", meaning_ipa: "/riəl/", spanish: "Auténtico", example: "That store is legit" },
  { id: 67, word: "Lit", ipa: "/lɪt/", meaning: "Exciting", meaning_ipa: "/ɪkˈsaɪtɪŋ/", spanish: "Prendido/Genial", example: "The concert was lit" },
  { id: 68, word: "Lowkey", ipa: "/loʊˈki/", meaning: "Secretly", meaning_ipa: "/ˈsikrətli/", spanish: "Secretamente", example: "I lowkey love this" },
  { id: 69, word: "My bad", ipa: "/maɪ bæd/", meaning: "My mistake", meaning_ipa: "/maɪ mɪˈsteɪk/", spanish: "Mi culpa", example: "My bad, I forgot" },
  { id: 70, word: "Nerd", ipa: "/nɜrd/", meaning: "Smart", meaning_ipa: "/smɑrt/", spanish: "Nerd/Inteligente", example: "He is a math nerd" },
  { id: 71, word: "Noob", ipa: "/nub/", meaning: "Beginner", meaning_ipa: "/bɪˈɡɪnər/", spanish: "Novato", example: "He plays like a noob" },
  { id: 72, word: "Nuts", ipa: "/nʌts/", meaning: "Crazy", meaning_ipa: "/ˈkreɪzi/", spanish: "Loco", example: "This idea is nuts" },
  { id: 73, word: "Peeps", ipa: "/pips/", meaning: "People", meaning_ipa: "/ˈpipəl/", spanish: "Amigos/Gente", example: "Where are my peeps?" },
  { id: 74, word: "Picky", ipa: "/ˈpɪki/", meaning: "Choosy", meaning_ipa: "/ˈtʃuzi/", spanish: "Exigente", example: "She is a picky eater" },
  { id: 75, word: "Pop", ipa: "/pɑp/", meaning: "Soda", meaning_ipa: "/ˈsoʊdə/", spanish: "Gaseosa", example: "I want a pop" },
  { id: 76, word: "Psycho", ipa: "/ˈsaɪkoʊ/", meaning: "Crazy person", meaning_ipa: "/ˈkreɪzi ˈpɜrsən/", spanish: "Loco", example: "She acts like a psycho" },
  { id: 77, word: "Pumped", ipa: "/pʌmpt/", meaning: "Excited", meaning_ipa: "/ɪkˈsaɪtɪd/", spanish: "Entusiasmado", example: "I am pumped for the game" },
  { id: 78, word: "Rad", ipa: "/ræd/", meaning: "Cool", meaning_ipa: "/kul/", spanish: "Genial", example: "That trick was rad" },
  { id: 79, word: "Ripped", ipa: "/rɪpt/", meaning: "Muscular", meaning_ipa: "/ˈmʌskjələr/", spanish: "Musculoso", example: "He got ripped" },
  { id: 80, word: "Rip-off", ipa: "/ˈrɪpˌɔf/", meaning: "Overpriced", meaning_ipa: "/ˌoʊvərˈpraɪst/", spanish: "Estafa", example: "That price is a rip-off" },
  { id: 81, word: "Roast", ipa: "/roʊst/", meaning: "Insult", meaning_ipa: "/ɪnˈsʌlt/", spanish: "Insultar (en broma)", example: "He roasted me" },
  { id: 82, word: "Rookie", ipa: "/ˈrʊki/", meaning: "Beginner", meaning_ipa: "/bɪˈɡɪnər/", spanish: "Novato", example: "That was a rookie mistake" },
  { id: 83, word: "Salty", ipa: "/ˈsɔlti/", meaning: "Bitter", meaning_ipa: "/ˈbɪtər/", spanish: "Molesto/Resentido", example: "Why are you so salty?" },
  { id: 84, word: "Savage", ipa: "/ˈsævɪdʒ/", meaning: "Ruthless", meaning_ipa: "/ˈruθləs/", spanish: "Despiadado", example: "That reply was savage" },
  { id: 85, word: "Score", ipa: "/skɔr/", meaning: "To get", meaning_ipa: "/tə ɡɛt/", spanish: "Conseguir", example: "I scored free tickets" },
  { id: 86, word: "Shady", ipa: "/ˈʃeɪdi/", meaning: "Suspicious", meaning_ipa: "/əˈpɪʃəs/", spanish: "Sospechoso", example: "That guy looks shady" },
  { id: 87, word: "Sick", ipa: "/sɪk/", meaning: "Cool", meaning_ipa: "/kul/", spanish: "Enfermo/Genial", example: "Those shoes are sick" },
  { id: 88, word: "Simp", ipa: "/sɪmp/", meaning: "Submissive", meaning_ipa: "/səbˈmɪsɪv/", spanish: "Persona sumisa por amor", example: "Stop being a simp" },
  { id: 89, word: "Sketchy", ipa: "/ˈskɛtʃi/", meaning: "Dangerous", meaning_ipa: "/ˈdeɪndʒərəs/", spanish: "Turbio", example: "This alley is sketchy" },
  { id: 90, word: "Slay", ipa: "/sleɪ/", meaning: "Do great", meaning_ipa: "/du ɡreɪt/", spanish: "Arrasar/Hacerlo bien", example: "You slay that outfit" },
  { id: 91, word: "Snag", ipa: "/snæɡ/", meaning: "Catch", meaning_ipa: "/kætʃ/", spanish: "Atrapar", example: "I managed to snag a seat" },
  { id: 92, word: "Squad", ipa: "/skwɑd/", meaning: "Group", meaning_ipa: "/ɡrup/", spanish: "Grupo de amigos", example: "I am going with the squad" },
  { id: 93, word: "Stan", ipa: "/stæn/", meaning: "Fan", meaning_ipa: "/fæn/", spanish: "Fanático obsesivo", example: "I stan this band" },
  { id: 94, word: "Sucks", ipa: "/sʌks/", meaning: "Is bad", meaning_ipa: "/ɪz bæd/", spanish: "Apesta", example: "This situation sucks" },
  { id: 95, word: "Sus", ipa: "/sʌs/", meaning: "Suspicious", meaning_ipa: "/səˈpɪʃəs/", spanish: "Sospechoso", example: "He is acting very sus" },
  { id: 96, word: "Swag", ipa: "/swæɡ/", meaning: "Style", meaning_ipa: "/staɪl/", spanish: "Estilo/Onda", example: "He has a lot of swag" },
  { id: 97, word: "Trash", ipa: "/træʃ/", meaning: "Terrible", meaning_ipa: "/ˈtɛrəbəl/", spanish: "Basura/Pésimo", example: "That movie was trash" },
  { id: 98, word: "Vibes", ipa: "/vaɪbz/", meaning: "Atmosphere", meaning_ipa: "/ˈætməˌsfɪr/", spanish: "Vibras/Ambiente", example: "This place has good vibes" },
  { id: 99, word: "Wack", ipa: "/wæk/", meaning: "Bad", meaning_ipa: "/bæd/", spanish: "Pésimo/Malo", example: "That rule is wack" },
  { id: 100, word: "Whip", ipa: "/wɪp/", meaning: "Car", meaning_ipa: "/kɑr/", spanish: "Automóvil", example: "Look at my new whip" }
];
