// ============================================================
// suaveData.ts — AUTO-GENERATED by generate_suave_data.cjs
// Version 0.0.1 feature 0.0.26
//
// This file contains ONLY tense formulas and 3 fallback seed
// questions per tense. All real questions are generated at
// runtime by local Gemma AI (generateSuaveQuestions in analysisService.ts).
// DO NOT add hardcoded questions here.
// ============================================================

export interface SuaveQuestion {
  id: string;
  spanish: string;
  difficulty: 'easy' | 'medium' | 'hard';
}

export interface SuaveTense {
  id: string;
  nameEs: string;
  nameEn: string;
  explanation: string;
  questions: SuaveQuestion[]; // Only seed fallback questions
}

export const SUAVE_DATA: SuaveTense[] = [
  {
    id: 'past_simple',
    nameEs: 'Pasado Simple',
    nameEn: 'Past Simple',
    explanation: `Método SUAVE para el Pasado Simple (Past Simple)

🔥 Fórmula General: S + U + A + V + E
   • S (Sujeto)   : ¿Quién hace la acción?
   • U (Uso)      : Acciones completadas en el pasado
   • A (Auxiliar) : "Did" — ¡Este es tu clave!
   • V (Verbo)    : La acción principal
   • E (Extra)    : El complemento

✨ Las 4 Formas:
Afirmativo:            S + V-ed  (ej: She walked)
Negativo:              S + Did not + Verb  (ej: She did not walk)
Interrogativo:         Did + S + Verb?  (ej: Did she walk?)
Negativo-Interrogativo: Did not + S + Verb?  (ej: Did not she walk?)

💡 Tip Maestro: Domina el auxiliar "Did" y dominarás este tiempo verbal.`,
    questions: [
    {
        "id": "seed_past_simple_1",
        "spanish": "Yo estudiar inglés todos los días",
        "difficulty": "easy"
    },
    {
        "id": "seed_past_simple_2",
        "spanish": "Mi amigo trabajar mucho la semana pasada",
        "difficulty": "medium"
    },
    {
        "id": "seed_past_simple_3",
        "spanish": "Nosotros aprender cosas nuevas constantemente",
        "difficulty": "hard"
    }
]
  },
  {
    id: 'present_simple',
    nameEs: 'Presente Simple',
    nameEn: 'Present Simple',
    explanation: `Método SUAVE para el Presente Simple (Present Simple)

🔥 Fórmula General: S + U + A + V + E
   • S (Sujeto)   : ¿Quién hace la acción?
   • U (Uso)      : Hábitos, hechos y verdades generales
   • A (Auxiliar) : "Do / Does" — ¡Este es tu clave!
   • V (Verbo)    : La acción principal
   • E (Extra)    : El complemento

✨ Las 4 Formas:
Afirmativo:            S + Verb(s)  (ej: He walks)
Negativo:              S + Do/Does not + Verb  (ej: He does not walk)
Interrogativo:         Do/Does + S + Verb?  (ej: Does he walk?)
Negativo-Interrogativo: Do/Does not + S + Verb?  (ej: Does not he walk?)

💡 Tip Maestro: Domina el auxiliar "Do / Does" y dominarás este tiempo verbal.`,
    questions: [
    {
        "id": "seed_present_simple_1",
        "spanish": "Yo estudiar inglés todos los días",
        "difficulty": "easy"
    },
    {
        "id": "seed_present_simple_2",
        "spanish": "Mi amigo trabajar mucho la semana pasada",
        "difficulty": "medium"
    },
    {
        "id": "seed_present_simple_3",
        "spanish": "Nosotros aprender cosas nuevas constantemente",
        "difficulty": "hard"
    }
]
  },
  {
    id: 'future_simple',
    nameEs: 'Futuro Simple',
    nameEn: 'Future Simple',
    explanation: `Método SUAVE para el Futuro Simple (Future Simple)

🔥 Fórmula General: S + U + A + V + E
   • S (Sujeto)   : ¿Quién hace la acción?
   • U (Uso)      : Acciones o decisiones futuras
   • A (Auxiliar) : "Will" — ¡Este es tu clave!
   • V (Verbo)    : La acción principal
   • E (Extra)    : El complemento

✨ Las 4 Formas:
Afirmativo:            S + Will + Verb  (ej: I will go)
Negativo:              S + Will not + Verb  (ej: I will not go)
Interrogativo:         Will + S + Verb?  (ej: Will you go?)
Negativo-Interrogativo: Will not + S + Verb?  (ej: Will not you go?)

💡 Tip Maestro: Domina el auxiliar "Will" y dominarás este tiempo verbal.`,
    questions: [
    {
        "id": "seed_future_simple_1",
        "spanish": "Yo estudiar inglés todos los días",
        "difficulty": "easy"
    },
    {
        "id": "seed_future_simple_2",
        "spanish": "Mi amigo trabajar mucho la semana pasada",
        "difficulty": "medium"
    },
    {
        "id": "seed_future_simple_3",
        "spanish": "Nosotros aprender cosas nuevas constantemente",
        "difficulty": "hard"
    }
]
  },
  {
    id: 'past_perfect',
    nameEs: 'Pasado Perfecto',
    nameEn: 'Past Perfect',
    explanation: `Método SUAVE para el Pasado Perfecto (Past Perfect)

🔥 Fórmula General: S + U + A + V + E
   • S (Sujeto)   : ¿Quién hace la acción?
   • U (Uso)      : Acción terminada antes de otra en el pasado
   • A (Auxiliar) : "Had" — ¡Este es tu clave!
   • V (Verbo)    : La acción principal
   • E (Extra)    : El complemento

✨ Las 4 Formas:
Afirmativo:            S + Had + V-pp  (ej: She had eaten)
Negativo:              S + Had not + V-pp  (ej: She had not eaten)
Interrogativo:         Had + S + V-pp?  (ej: Had she eaten?)
Negativo-Interrogativo: Had not + S + V-pp?  (ej: Had not she eaten?)

💡 Tip Maestro: Domina el auxiliar "Had" y dominarás este tiempo verbal.`,
    questions: [
    {
        "id": "seed_past_perfect_1",
        "spanish": "Yo estudiar inglés todos los días",
        "difficulty": "easy"
    },
    {
        "id": "seed_past_perfect_2",
        "spanish": "Mi amigo trabajar mucho la semana pasada",
        "difficulty": "medium"
    },
    {
        "id": "seed_past_perfect_3",
        "spanish": "Nosotros aprender cosas nuevas constantemente",
        "difficulty": "hard"
    }
]
  },
  {
    id: 'present_perfect',
    nameEs: 'Presente Perfecto',
    nameEn: 'Present Perfect',
    explanation: `Método SUAVE para el Presente Perfecto (Present Perfect)

🔥 Fórmula General: S + U + A + V + E
   • S (Sujeto)   : ¿Quién hace la acción?
   • U (Uso)      : Acción pasada con resultado presente
   • A (Auxiliar) : "Have / Has" — ¡Este es tu clave!
   • V (Verbo)    : La acción principal
   • E (Extra)    : El complemento

✨ Las 4 Formas:
Afirmativo:            S + Have/Has + V-pp  (ej: I have lived)
Negativo:              S + Have/Has not + V-pp  (ej: I have not lived)
Interrogativo:         Have/Has + S + V-pp?  (ej: Have you lived?)
Negativo-Interrogativo: Have/Has not + S + V-pp?  (ej: Have not you lived?)

💡 Tip Maestro: Domina el auxiliar "Have / Has" y dominarás este tiempo verbal.`,
    questions: [
    {
        "id": "seed_present_perfect_1",
        "spanish": "Yo estudiar inglés todos los días",
        "difficulty": "easy"
    },
    {
        "id": "seed_present_perfect_2",
        "spanish": "Mi amigo trabajar mucho la semana pasada",
        "difficulty": "medium"
    },
    {
        "id": "seed_present_perfect_3",
        "spanish": "Nosotros aprender cosas nuevas constantemente",
        "difficulty": "hard"
    }
]
  },
  {
    id: 'future_perfect',
    nameEs: 'Futuro Perfecto',
    nameEn: 'Future Perfect',
    explanation: `Método SUAVE para el Futuro Perfecto (Future Perfect)

🔥 Fórmula General: S + U + A + V + E
   • S (Sujeto)   : ¿Quién hace la acción?
   • U (Uso)      : Acción que habrá terminado antes de un punto futuro
   • A (Auxiliar) : "Will have" — ¡Este es tu clave!
   • V (Verbo)    : La acción principal
   • E (Extra)    : El complemento

✨ Las 4 Formas:
Afirmativo:            S + Will have + V-pp  (ej: I will have finished)
Negativo:              S + Will not have + V-pp  (ej: I will not have finished)
Interrogativo:         Will + S + have + V-pp?  (ej: Will you have finished?)
Negativo-Interrogativo: Will not + S + have + V-pp?  (ej: Will not you have finished?)

💡 Tip Maestro: Domina el auxiliar "Will have" y dominarás este tiempo verbal.`,
    questions: [
    {
        "id": "seed_future_perfect_1",
        "spanish": "Yo estudiar inglés todos los días",
        "difficulty": "easy"
    },
    {
        "id": "seed_future_perfect_2",
        "spanish": "Mi amigo trabajar mucho la semana pasada",
        "difficulty": "medium"
    },
    {
        "id": "seed_future_perfect_3",
        "spanish": "Nosotros aprender cosas nuevas constantemente",
        "difficulty": "hard"
    }
]
  },
  {
    id: 'past_progressive',
    nameEs: 'Pasado Progresivo',
    nameEn: 'Past Progressive',
    explanation: `Método SUAVE para el Pasado Progresivo (Past Progressive)

🔥 Fórmula General: S + U + A + V + E
   • S (Sujeto)   : ¿Quién hace la acción?
   • U (Uso)      : Acción en progreso en un momento del pasado
   • A (Auxiliar) : "Was / Were" — ¡Este es tu clave!
   • V (Verbo)    : La acción principal
   • E (Extra)    : El complemento

✨ Las 4 Formas:
Afirmativo:            S + Was/Were + V-ing  (ej: She was running)
Negativo:              S + Was/Were not + V-ing  (ej: She was not running)
Interrogativo:         Was/Were + S + V-ing?  (ej: Was she running?)
Negativo-Interrogativo: Was/Were not + S + V-ing?  (ej: Was not she running?)

💡 Tip Maestro: Domina el auxiliar "Was / Were" y dominarás este tiempo verbal.`,
    questions: [
    {
        "id": "seed_past_progressive_1",
        "spanish": "Yo estudiar inglés todos los días",
        "difficulty": "easy"
    },
    {
        "id": "seed_past_progressive_2",
        "spanish": "Mi amigo trabajar mucho la semana pasada",
        "difficulty": "medium"
    },
    {
        "id": "seed_past_progressive_3",
        "spanish": "Nosotros aprender cosas nuevas constantemente",
        "difficulty": "hard"
    }
]
  },
  {
    id: 'present_progressive',
    nameEs: 'Presente Progresivo',
    nameEn: 'Present Progressive',
    explanation: `Método SUAVE para el Presente Progresivo (Present Progressive)

🔥 Fórmula General: S + U + A + V + E
   • S (Sujeto)   : ¿Quién hace la acción?
   • U (Uso)      : Acción en progreso ahora mismo
   • A (Auxiliar) : "Am / Is / Are" — ¡Este es tu clave!
   • V (Verbo)    : La acción principal
   • E (Extra)    : El complemento

✨ Las 4 Formas:
Afirmativo:            S + Am/Is/Are + V-ing  (ej: I am studying)
Negativo:              S + Am/Is/Are not + V-ing  (ej: I am not studying)
Interrogativo:         Am/Is/Are + S + V-ing?  (ej: Are you studying?)
Negativo-Interrogativo: Am/Is/Are not + S + V-ing?  (ej: Are not you studying?)

💡 Tip Maestro: Domina el auxiliar "Am / Is / Are" y dominarás este tiempo verbal.`,
    questions: [
    {
        "id": "seed_present_progressive_1",
        "spanish": "Yo estudiar inglés todos los días",
        "difficulty": "easy"
    },
    {
        "id": "seed_present_progressive_2",
        "spanish": "Mi amigo trabajar mucho la semana pasada",
        "difficulty": "medium"
    },
    {
        "id": "seed_present_progressive_3",
        "spanish": "Nosotros aprender cosas nuevas constantemente",
        "difficulty": "hard"
    }
]
  },
  {
    id: 'future_progressive',
    nameEs: 'Futuro Progresivo',
    nameEn: 'Future Progressive',
    explanation: `Método SUAVE para el Futuro Progresivo (Future Progressive)

🔥 Fórmula General: S + U + A + V + E
   • S (Sujeto)   : ¿Quién hace la acción?
   • U (Uso)      : Acción en progreso en un momento futuro
   • A (Auxiliar) : "Will be" — ¡Este es tu clave!
   • V (Verbo)    : La acción principal
   • E (Extra)    : El complemento

✨ Las 4 Formas:
Afirmativo:            S + Will be + V-ing  (ej: I will be working)
Negativo:              S + Will not be + V-ing  (ej: I will not be working)
Interrogativo:         Will + S + be + V-ing?  (ej: Will you be working?)
Negativo-Interrogativo: Will not + S + be + V-ing?  (ej: Will not you be working?)

💡 Tip Maestro: Domina el auxiliar "Will be" y dominarás este tiempo verbal.`,
    questions: [
    {
        "id": "seed_future_progressive_1",
        "spanish": "Yo estudiar inglés todos los días",
        "difficulty": "easy"
    },
    {
        "id": "seed_future_progressive_2",
        "spanish": "Mi amigo trabajar mucho la semana pasada",
        "difficulty": "medium"
    },
    {
        "id": "seed_future_progressive_3",
        "spanish": "Nosotros aprender cosas nuevas constantemente",
        "difficulty": "hard"
    }
]
  },
  {
    id: 'past_perfect_progressive',
    nameEs: 'Pasado Perfecto Progresivo',
    nameEn: 'Past Perfect Progressive',
    explanation: `Método SUAVE para el Pasado Perfecto Progresivo (Past Perfect Progressive)

🔥 Fórmula General: S + U + A + V + E
   • S (Sujeto)   : ¿Quién hace la acción?
   • U (Uso)      : Acción continua que ocurrió antes de otra en el pasado
   • A (Auxiliar) : "Had been" — ¡Este es tu clave!
   • V (Verbo)    : La acción principal
   • E (Extra)    : El complemento

✨ Las 4 Formas:
Afirmativo:            S + Had been + V-ing  (ej: She had been crying)
Negativo:              S + Had not been + V-ing  (ej: She had not been crying)
Interrogativo:         Had + S + been + V-ing?  (ej: Had she been crying?)
Negativo-Interrogativo: Had not + S + been + V-ing?  (ej: Had not she been crying?)

💡 Tip Maestro: Domina el auxiliar "Had been" y dominarás este tiempo verbal.`,
    questions: [
    {
        "id": "seed_past_perfect_progressive_1",
        "spanish": "Yo estudiar inglés todos los días",
        "difficulty": "easy"
    },
    {
        "id": "seed_past_perfect_progressive_2",
        "spanish": "Mi amigo trabajar mucho la semana pasada",
        "difficulty": "medium"
    },
    {
        "id": "seed_past_perfect_progressive_3",
        "spanish": "Nosotros aprender cosas nuevas constantemente",
        "difficulty": "hard"
    }
]
  },
  {
    id: 'present_perfect_progressive',
    nameEs: 'Presente Perfecto Progresivo',
    nameEn: 'Present Perfect Progressive',
    explanation: `Método SUAVE para el Presente Perfecto Progresivo (Present Perfect Progressive)

🔥 Fórmula General: S + U + A + V + E
   • S (Sujeto)   : ¿Quién hace la acción?
   • U (Uso)      : Acción que empezó en el pasado y continúa ahora
   • A (Auxiliar) : "Have been / Has been" — ¡Este es tu clave!
   • V (Verbo)    : La acción principal
   • E (Extra)    : El complemento

✨ Las 4 Formas:
Afirmativo:            S + Have/Has been + V-ing  (ej: I have been waiting)
Negativo:              S + Have/Has not been + V-ing  (ej: I have not been waiting)
Interrogativo:         Have/Has + S + been + V-ing?  (ej: Has she been waiting?)
Negativo-Interrogativo: Have/Has not + S + been + V-ing?  (ej: Has not she been waiting?)

💡 Tip Maestro: Domina el auxiliar "Have been / Has been" y dominarás este tiempo verbal.`,
    questions: [
    {
        "id": "seed_present_perfect_progressive_1",
        "spanish": "Yo estudiar inglés todos los días",
        "difficulty": "easy"
    },
    {
        "id": "seed_present_perfect_progressive_2",
        "spanish": "Mi amigo trabajar mucho la semana pasada",
        "difficulty": "medium"
    },
    {
        "id": "seed_present_perfect_progressive_3",
        "spanish": "Nosotros aprender cosas nuevas constantemente",
        "difficulty": "hard"
    }
]
  },
  {
    id: 'future_perfect_progressive',
    nameEs: 'Futuro Perfecto Progresivo',
    nameEn: 'Future Perfect Progressive',
    explanation: `Método SUAVE para el Futuro Perfecto Progresivo (Future Perfect Progressive)

🔥 Fórmula General: S + U + A + V + E
   • S (Sujeto)   : ¿Quién hace la acción?
   • U (Uso)      : Acción continua que habrá ocurrido antes de un punto futuro
   • A (Auxiliar) : "Will have been" — ¡Este es tu clave!
   • V (Verbo)    : La acción principal
   • E (Extra)    : El complemento

✨ Las 4 Formas:
Afirmativo:            S + Will have been + V-ing  (ej: I will have been working)
Negativo:              S + Will not have been + V-ing  (ej: I will not have been working)
Interrogativo:         Will + S + have been + V-ing?  (ej: Will you have been working?)
Negativo-Interrogativo: Will not + S + have been + V-ing?  (ej: Will not you have been working?)

💡 Tip Maestro: Domina el auxiliar "Will have been" y dominarás este tiempo verbal.`,
    questions: [
    {
        "id": "seed_future_perfect_progressive_1",
        "spanish": "Yo estudiar inglés todos los días",
        "difficulty": "easy"
    },
    {
        "id": "seed_future_perfect_progressive_2",
        "spanish": "Mi amigo trabajar mucho la semana pasada",
        "difficulty": "medium"
    },
    {
        "id": "seed_future_perfect_progressive_3",
        "spanish": "Nosotros aprender cosas nuevas constantemente",
        "difficulty": "hard"
    }
]
  },
];
